libliftracc: src/plugins/cblas_plugin.c File Reference
src/plugins/cblas_plugin.c File Reference
[generated file]
Functions
void __attribute__ ((constructor))
void __attribute__ ((destructor))
decision_data_t liftracc_plugin_getdecision (liftracc_selector_funcid_t id, int index)
int liftracc_plugin_calltest_dynamic (int a, int b, int c)
float liftracc_plugin_sdsdot (const int n, const float alpha, const float *x, const int incx, const float *y, const int incy)
double liftracc_plugin_dsdot (const int n, const float *x, const int incx, const float *y, const int incy)
float liftracc_plugin_sdot (const int n, const float *x, const int incx, const float *y, const int incy)
double liftracc_plugin_ddot (const int n, const double *x, const int incx, const double *y, const int incy)
void liftracc_plugin_cdotu_sub (const int n, const void *x, const int incx, const void *y, const int incy, void *dotu)
void liftracc_plugin_cdotc_sub (const int n, const void *x, const int incx, const void *y, const int incy, void *dotc)
void liftracc_plugin_zdotu_sub (const int n, const void *x, const int incx, const void *y, const int incy, void *dotu)
void liftracc_plugin_zdotc_sub (const int n, const void *x, const int incx, const void *y, const int incy, void *dotc)
float liftracc_plugin_snrm2 (const int n, const float *x, const int incx)
float liftracc_plugin_sasum (const int n, const float *x, const int incx)
double liftracc_plugin_dnrm2 (const int n, const double *x, const int incx)
double liftracc_plugin_dasum (const int n, const double *x, const int incx)
float liftracc_plugin_scnrm2 (const int n, const void *x, const int incx)
float liftracc_plugin_scasum (const int n, const void *x, const int incx)
double liftracc_plugin_dznrm2 (const int n, const void *x, const int incx)
double liftracc_plugin_dzasum (const int n, const void *x, const int incx)
liftracc_index_t liftracc_plugin_isamax (const int n, const float *x, const int incx)
liftracc_index_t liftracc_plugin_idamax (const int n, const double *x, const int incx)
liftracc_index_t liftracc_plugin_icamax (const int n, const void *x, const int incx)
liftracc_index_t liftracc_plugin_izamax (const int n, const void *x, const int incx)
void liftracc_plugin_sswap (const int n, float *x, const int incx, float *y, const int incy)
void liftracc_plugin_scopy (const int n, const float *x, const int incx, float *y, const int incy)
void liftracc_plugin_saxpy (const int n, const float alpha, const float *x, const int incx, float *y, const int incy)
void liftracc_plugin_dswap (const int n, double *x, const int incx, double *y, const int incy)
void liftracc_plugin_dcopy (const int n, const double *x, const int incx, double *y, const int incy)
void liftracc_plugin_daxpy (const int n, const double alpha, const double *x, const int incx, double *y, const int incy)
void liftracc_plugin_cswap (const int n, void *x, const int incx, void *y, const int incy)
void liftracc_plugin_ccopy (const int n, const void *x, const int incx, void *y, const int incy)
void liftracc_plugin_caxpy (const int n, const void *alpha, const void *x, const int incx, void *y, const int incy)
void liftracc_plugin_zswap (const int n, void *x, const int incx, void *y, const int incy)
void liftracc_plugin_zcopy (const int n, const void *x, const int incx, void *y, const int incy)
void liftracc_plugin_zaxpy (const int n, const void *alpha, const void *x, const int incx, void *y, const int incy)
void liftracc_plugin_srotg (float *a, float *b, float *c, float *s)
void liftracc_plugin_srotmg (float *d1, float *d2, float *b1, const float b2, float *p)
void liftracc_plugin_srot (const int n, float *x, const int incx, float *y, const int incy, const float c, const float s)
void liftracc_plugin_srotm (const int n, float *x, const int incx, float *y, const int incy, const float *p)
void liftracc_plugin_drotg (double *a, double *b, double *c, double *s)
void liftracc_plugin_drotmg (double *d1, double *d2, double *b1, const double b2, double *p)
void liftracc_plugin_drot (const int n, double *x, const int incx, double *y, const int incy, const double c, const double s)
void liftracc_plugin_drotm (const int n, double *x, const int incx, double *y, const int incy, const double *p)
void liftracc_plugin_sscal (const int n, const float alpha, float *x, const int incx)
void liftracc_plugin_dscal (const int n, const double alpha, double *x, const int incx)
void liftracc_plugin_cscal (const int n, const void *alpha, void *x, const int incx)
void liftracc_plugin_zscal (const int n, const void *alpha, void *x, const int incx)
void liftracc_plugin_csscal (const int n, const float alpha, void *x, const int incx)
void liftracc_plugin_zdscal (const int n, const double alpha, void *x, const int incx)
void liftracc_plugin_sgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const float alpha, const float *a, const int lda, const float *x, const int incx, const float beta, float *y, const int incy)
void liftracc_plugin_sgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const float alpha, const float *a, const int lda, const float *x, const int incx, const float beta, float *y, const int incy)
void liftracc_plugin_strmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float *a, const int lda, float *x, const int incx)
void liftracc_plugin_stbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const float *a, const int lda, float *x, const int incx)
void liftracc_plugin_stpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float *ap, float *x, const int incx)
void liftracc_plugin_strsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float *a, const int lda, float *x, const int incx)
void liftracc_plugin_stbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const float *a, const int lda, float *x, const int incx)
void liftracc_plugin_stpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float *ap, float *x, const int incx)
void liftracc_plugin_dgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const double alpha, const double *a, const int lda, const double *x, const int incx, const double beta, double *y, const int incy)
void liftracc_plugin_dgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const double alpha, const double *a, const int lda, const double *x, const int incx, const double beta, double *y, const int incy)
void liftracc_plugin_dtrmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double *a, const int lda, double *x, const int incx)
void liftracc_plugin_dtbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const double *a, const int lda, double *x, const int incx)
void liftracc_plugin_dtpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double *ap, double *x, const int incx)
void liftracc_plugin_dtrsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double *a, const int lda, double *x, const int incx)
void liftracc_plugin_dtbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const double *a, const int lda, double *x, const int incx)
void liftracc_plugin_dtpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double *ap, double *x, const int incx)
void liftracc_plugin_cgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_plugin_cgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_plugin_ctrmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *a, const int lda, void *x, const int incx)
void liftracc_plugin_ctbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void *a, const int lda, void *x, const int incx)
void liftracc_plugin_ctpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *ap, void *x, const int incx)
void liftracc_plugin_ctrsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *a, const int lda, void *x, const int incx)
void liftracc_plugin_ctbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void *a, const int lda, void *x, const int incx)
void liftracc_plugin_ctpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *ap, void *x, const int incx)
void liftracc_plugin_zgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_plugin_zgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_plugin_ztrmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *a, const int lda, void *x, const int incx)
void liftracc_plugin_ztbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void *a, const int lda, void *x, const int incx)
void liftracc_plugin_ztpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *ap, void *x, const int incx)
void liftracc_plugin_ztrsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *a, const int lda, void *x, const int incx)
void liftracc_plugin_ztbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void *a, const int lda, void *x, const int incx)
void liftracc_plugin_ztpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *ap, void *x, const int incx)
void liftracc_plugin_ssymv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float *a, const int lda, const float *x, const int incx, const float beta, float *y, const int incy)
void liftracc_plugin_ssbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const float alpha, const float *a, const int lda, const float *x, const int incx, const float beta, float *y, const int incy)
void liftracc_plugin_sspmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float *ap, const float *x, const int incx, const float beta, float *y, const int incy)
void liftracc_plugin_sger (const liftracc_order_t order, const int m, const int n, const float alpha, const float *x, const int incx, const float *y, const int incy, float *a, const int lda)
void liftracc_plugin_ssyr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float *x, const int incx, float *a, const int lda)
void liftracc_plugin_sspr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float *x, const int incx, float *ap)
void liftracc_plugin_ssyr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float *x, const int incx, const float *y, const int incy, float *a, const int lda)
void liftracc_plugin_sspr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float *x, const int incx, const float *y, const int incy, float *a)
void liftracc_plugin_dsymv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double *a, const int lda, const double *x, const int incx, const double beta, double *y, const int incy)
void liftracc_plugin_dsbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const double alpha, const double *a, const int lda, const double *x, const int incx, const double beta, double *y, const int incy)
void liftracc_plugin_dspmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double *ap, const double *x, const int incx, const double beta, double *y, const int incy)
void liftracc_plugin_dger (const liftracc_order_t order, const int m, const int n, const double alpha, const double *x, const int incx, const double *y, const int incy, double *a, const int lda)
void liftracc_plugin_dsyr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double *x, const int incx, double *a, const int lda)
void liftracc_plugin_dspr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double *x, const int incx, double *ap)
void liftracc_plugin_dsyr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double *x, const int incx, const double *y, const int incy, double *a, const int lda)
void liftracc_plugin_dspr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double *x, const int incx, const double *y, const int incy, double *a)
void liftracc_plugin_chemv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_plugin_chbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_plugin_chpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *ap, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_plugin_cgeru (const liftracc_order_t order, const int m, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *a, const int lda)
void liftracc_plugin_cgerc (const liftracc_order_t order, const int m, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *a, const int lda)
void liftracc_plugin_cher (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const void *x, const int incx, void *a, const int lda)
void liftracc_plugin_chpr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const void *x, const int incx, void *a)
void liftracc_plugin_cher2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *a, const int lda)
void liftracc_plugin_chpr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *ap)
void liftracc_plugin_zhemv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_plugin_zhbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_plugin_zhpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *ap, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_plugin_zgeru (const liftracc_order_t order, const int m, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *a, const int lda)
void liftracc_plugin_zgerc (const liftracc_order_t order, const int m, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *a, const int lda)
void liftracc_plugin_zher (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const void *x, const int incx, void *a, const int lda)
void liftracc_plugin_zhpr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const void *x, const int incx, void *a)
void liftracc_plugin_zher2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *a, const int lda)
void liftracc_plugin_zhpr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *ap)
void liftracc_plugin_sgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const float alpha, const float *a, const int lda, const float *b, const int ldb, const float beta, float *c, const int ldc)
void liftracc_plugin_ssymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const float alpha, const float *a, const int lda, const float *b, const int ldb, const float beta, float *c, const int ldc)
void liftracc_plugin_ssyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const float alpha, const float *a, const int lda, const float beta, float *c, const int ldc)
void liftracc_plugin_ssyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const float alpha, const float *a, const int lda, const float *b, const int ldb, const float beta, float *c, const int ldc)
void liftracc_plugin_strmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const float alpha, const float *a, const int lda, float *b, const int ldb)
void liftracc_plugin_strsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const float alpha, const float *a, const int lda, float *b, const int ldb)
void liftracc_plugin_dgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const double alpha, const double *a, const int lda, const double *b, const int ldb, const double beta, double *c, const int ldc)
void liftracc_plugin_dsymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const double alpha, const double *a, const int lda, const double *b, const int ldb, const double beta, double *c, const int ldc)
void liftracc_plugin_dsyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const double alpha, const double *a, const int lda, const double beta, double *c, const int ldc)
void liftracc_plugin_dsyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const double alpha, const double *a, const int lda, const double *b, const int ldb, const double beta, double *c, const int ldc)
void liftracc_plugin_dtrmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const double alpha, const double *a, const int lda, double *b, const int ldb)
void liftracc_plugin_dtrsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const double alpha, const double *a, const int lda, double *b, const int ldb)
void liftracc_plugin_cgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
void liftracc_plugin_csymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
void liftracc_plugin_csyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void *alpha, const void *a, const int lda, const void *beta, void *c, const int ldc)
void liftracc_plugin_csyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
void liftracc_plugin_ctrmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void *alpha, const void *a, const int lda, void *b, const int ldb)
void liftracc_plugin_ctrsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void *alpha, const void *a, const int lda, void *b, const int ldb)
void liftracc_plugin_zgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
void liftracc_plugin_zsymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
void liftracc_plugin_zsyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void *alpha, const void *a, const int lda, const void *beta, void *c, const int ldc)
void liftracc_plugin_zsyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
void liftracc_plugin_ztrmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void *alpha, const void *a, const int lda, void *b, const int ldb)
void liftracc_plugin_ztrsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void *alpha, const void *a, const int lda, void *b, const int ldb)
void liftracc_plugin_chemm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
void liftracc_plugin_cherk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const float alpha, const void *a, const int lda, const float beta, void *c, const int ldc)
void liftracc_plugin_cher2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const float beta, void *c, const int ldc)
void liftracc_plugin_zhemm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
void liftracc_plugin_zherk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const double alpha, const void *a, const int lda, const double beta, void *c, const int ldc)
void liftracc_plugin_zher2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const double beta, void *c, const int ldc)
void liftracc_plugin_xerbla (int p, const char *rout, const char *form)
Variables
profiling_data_t function_profiling_data [LIFTRACC_FUNCTIONS_COUNT] = { }
decision_data_t decision_data [FUNCTION_COUNT *ARRAY_SIZE] = { }
void * liftracc_plugin_fptr [CBLAS_FUNCTIONS_COUNT] = { }
plugin_info_t liftracc_plugin_info
void * handle = 0
char * error = 0
Detailed Description
[generated file]
This file is generated automatically, do not edit manually!
Definition in file cblas_plugin.c.
Function Documentation
void __attribute__ ((constructor))
Definition at line 44 of file cblas_plugin.c.
References CBLAS_FUNCTIONS_COUNT, decision_data, handle, liftracc_cblas_function_names, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_INIT, liftracc_plugin_fptr, liftracc_selector_loadinfo(), and plugin_info_t::name.
void __attribute__ ((destructor))
Definition at line 85 of file cblas_plugin.c.
References decision_data, handle, LIFTRACC_FINI, liftracc_function_names, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTIONS_COUNT, liftracc_selector_saveinfo(), plugin_info_t::name, and print_profiling_data().
int liftracc_plugin_calltest_dynamic (int a, int b, int c)
Definition at line 125 of file cblas_plugin.c.
References CALL_DYNAMIC, liftracc_function_timing_stop(), and liftracc_profiling_data.
void liftracc_plugin_caxpy (const int n, const void * alpha, const void * x, const int incx, void * y, const int incy)
Definition at line 1026 of file cblas_plugin.c.
References CBLAS_FUNCTION_CAXPY, decision_data, LIFTRACC_FUNCTION_CAXPY, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CAXPY, and set_decision_data().
void liftracc_plugin_ccopy (const int n, const void * x, const int incx, void * y, const int incy)
Definition at line 997 of file cblas_plugin.c.
References CBLAS_FUNCTION_CCOPY, decision_data, LIFTRACC_FUNCTION_CCOPY, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CCOPY, and set_decision_data().
void liftracc_plugin_cdotc_sub (const int n, const void * x, const int incx, const void * y, const int incy, void * dotc)
Definition at line 299 of file cblas_plugin.c.
References CBLAS_FUNCTION_CDOTC_SUB, decision_data, LIFTRACC_FUNCTION_CDOTC_SUB, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CDOTC_SUB, and set_decision_data().
void liftracc_plugin_cdotu_sub (const int n, const void * x, const int incx, const void * y, const int incy, void * dotu)
Definition at line 270 of file cblas_plugin.c.
References CBLAS_FUNCTION_CDOTU_SUB, decision_data, LIFTRACC_FUNCTION_CDOTU_SUB, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CDOTU_SUB, and set_decision_data().
void liftracc_plugin_cgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 2041 of file cblas_plugin.c.
References CBLAS_FUNCTION_CGBMV, decision_data, LIFTRACC_FUNCTION_CGBMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CGBMV, and set_decision_data().
void liftracc_plugin_cgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
Definition at line 3810 of file cblas_plugin.c.
References CBLAS_FUNCTION_CGEMM, decision_data, LIFTRACC_FUNCTION_CGEMM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CGEMM, and set_decision_data().
void liftracc_plugin_cgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 2012 of file cblas_plugin.c.
References CBLAS_FUNCTION_CGEMV, decision_data, LIFTRACC_FUNCTION_CGEMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CGEMV, and set_decision_data().
void liftracc_plugin_cgerc (const liftracc_order_t order, const int m, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * a, const int lda)
Definition at line 3056 of file cblas_plugin.c.
References CBLAS_FUNCTION_CGERC, decision_data, LIFTRACC_FUNCTION_CGERC, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CGERC, and set_decision_data().
void liftracc_plugin_cgeru (const liftracc_order_t order, const int m, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * a, const int lda)
Definition at line 3027 of file cblas_plugin.c.
References CBLAS_FUNCTION_CGERU, decision_data, LIFTRACC_FUNCTION_CGERU, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CGERU, and set_decision_data().
void liftracc_plugin_chbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 2969 of file cblas_plugin.c.
References CBLAS_FUNCTION_CHBMV, decision_data, LIFTRACC_FUNCTION_CHBMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CHBMV, and set_decision_data().
void liftracc_plugin_chemm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
Definition at line 4158 of file cblas_plugin.c.
References CBLAS_FUNCTION_CHEMM, decision_data, LIFTRACC_FUNCTION_CHEMM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CHEMM, and set_decision_data().
void liftracc_plugin_chemv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 2940 of file cblas_plugin.c.
References CBLAS_FUNCTION_CHEMV, decision_data, LIFTRACC_FUNCTION_CHEMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CHEMV, and set_decision_data().
void liftracc_plugin_cher (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const void * x, const int incx, void * a, const int lda)
Definition at line 3085 of file cblas_plugin.c.
References CBLAS_FUNCTION_CHER, decision_data, LIFTRACC_FUNCTION_CHER, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CHER, and set_decision_data().
void liftracc_plugin_cher2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * a, const int lda)
Definition at line 3143 of file cblas_plugin.c.
References CBLAS_FUNCTION_CHER2, decision_data, LIFTRACC_FUNCTION_CHER2, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CHER2, and set_decision_data().
void liftracc_plugin_cher2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const float beta, void * c, const int ldc)
Definition at line 4216 of file cblas_plugin.c.
References CBLAS_FUNCTION_CHER2K, decision_data, LIFTRACC_FUNCTION_CHER2K, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CHER2K, and set_decision_data().
void liftracc_plugin_cherk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const float alpha, const void * a, const int lda, const float beta, void * c, const int ldc)
Definition at line 4187 of file cblas_plugin.c.
References CBLAS_FUNCTION_CHERK, decision_data, LIFTRACC_FUNCTION_CHERK, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CHERK, and set_decision_data().
void liftracc_plugin_chpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * ap, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 2998 of file cblas_plugin.c.
References CBLAS_FUNCTION_CHPMV, decision_data, LIFTRACC_FUNCTION_CHPMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CHPMV, and set_decision_data().
void liftracc_plugin_chpr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const void * x, const int incx, void * a)
Definition at line 3114 of file cblas_plugin.c.
References CBLAS_FUNCTION_CHPR, decision_data, LIFTRACC_FUNCTION_CHPR, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CHPR, and set_decision_data().
void liftracc_plugin_chpr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * ap)
Definition at line 3172 of file cblas_plugin.c.
References CBLAS_FUNCTION_CHPR2, decision_data, LIFTRACC_FUNCTION_CHPR2, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CHPR2, and set_decision_data().
void liftracc_plugin_cscal (const int n, const void * alpha, void * x, const int incx)
Definition at line 1432 of file cblas_plugin.c.
References CBLAS_FUNCTION_CSCAL, decision_data, LIFTRACC_FUNCTION_CSCAL, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CSCAL, and set_decision_data().
void liftracc_plugin_csscal (const int n, const float alpha, void * x, const int incx)
Definition at line 1490 of file cblas_plugin.c.
References CBLAS_FUNCTION_CSSCAL, decision_data, LIFTRACC_FUNCTION_CSSCAL, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CSSCAL, and set_decision_data().
void liftracc_plugin_cswap (const int n, void * x, const int incx, void * y, const int incy)
Definition at line 968 of file cblas_plugin.c.
References CBLAS_FUNCTION_CSWAP, decision_data, LIFTRACC_FUNCTION_CSWAP, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CSWAP, and set_decision_data().
void liftracc_plugin_csymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
Definition at line 3839 of file cblas_plugin.c.
References CBLAS_FUNCTION_CSYMM, decision_data, LIFTRACC_FUNCTION_CSYMM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CSYMM, and set_decision_data().
void liftracc_plugin_csyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
Definition at line 3897 of file cblas_plugin.c.
References CBLAS_FUNCTION_CSYR2K, decision_data, LIFTRACC_FUNCTION_CSYR2K, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CSYR2K, and set_decision_data().
void liftracc_plugin_csyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void * alpha, const void * a, const int lda, const void * beta, void * c, const int ldc)
Definition at line 3868 of file cblas_plugin.c.
References CBLAS_FUNCTION_CSYRK, decision_data, LIFTRACC_FUNCTION_CSYRK, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CSYRK, and set_decision_data().
void liftracc_plugin_ctbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void * a, const int lda, void * x, const int incx)
Definition at line 2099 of file cblas_plugin.c.
References CBLAS_FUNCTION_CTBMV, decision_data, LIFTRACC_FUNCTION_CTBMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CTBMV, and set_decision_data().
void liftracc_plugin_ctbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void * a, const int lda, void * x, const int incx)
Definition at line 2186 of file cblas_plugin.c.
References CBLAS_FUNCTION_CTBSV, decision_data, LIFTRACC_FUNCTION_CTBSV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CTBSV, and set_decision_data().
void liftracc_plugin_ctpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * ap, void * x, const int incx)
Definition at line 2128 of file cblas_plugin.c.
References CBLAS_FUNCTION_CTPMV, decision_data, LIFTRACC_FUNCTION_CTPMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CTPMV, and set_decision_data().
void liftracc_plugin_ctpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * ap, void * x, const int incx)
Definition at line 2215 of file cblas_plugin.c.
References CBLAS_FUNCTION_CTPSV, decision_data, LIFTRACC_FUNCTION_CTPSV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CTPSV, and set_decision_data().
void liftracc_plugin_ctrmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void * alpha, const void * a, const int lda, void * b, const int ldb)
Definition at line 3926 of file cblas_plugin.c.
References CBLAS_FUNCTION_CTRMM, decision_data, LIFTRACC_FUNCTION_CTRMM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CTRMM, and set_decision_data().
void liftracc_plugin_ctrmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * a, const int lda, void * x, const int incx)
Definition at line 2070 of file cblas_plugin.c.
References CBLAS_FUNCTION_CTRMV, decision_data, LIFTRACC_FUNCTION_CTRMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CTRMV, and set_decision_data().
void liftracc_plugin_ctrsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void * alpha, const void * a, const int lda, void * b, const int ldb)
Definition at line 3955 of file cblas_plugin.c.
References CBLAS_FUNCTION_CTRSM, decision_data, LIFTRACC_FUNCTION_CTRSM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CTRSM, and set_decision_data().
void liftracc_plugin_ctrsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * a, const int lda, void * x, const int incx)
Definition at line 2157 of file cblas_plugin.c.
References CBLAS_FUNCTION_CTRSV, decision_data, LIFTRACC_FUNCTION_CTRSV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_CTRSV, and set_decision_data().
double liftracc_plugin_dasum (const int n, const double * x, const int incx)
Definition at line 488 of file cblas_plugin.c.
References CBLAS_FUNCTION_DASUM, decision_data, LIFTRACC_FUNCTION_DASUM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DASUM, and set_decision_data().
void liftracc_plugin_daxpy (const int n, const double alpha, const double * x, const int incx, double * y, const int incy)
Definition at line 939 of file cblas_plugin.c.
References CBLAS_FUNCTION_DAXPY, decision_data, LIFTRACC_FUNCTION_DAXPY, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DAXPY, and set_decision_data().
void liftracc_plugin_dcopy (const int n, const double * x, const int incx, double * y, const int incy)
Definition at line 910 of file cblas_plugin.c.
References CBLAS_FUNCTION_DCOPY, decision_data, LIFTRACC_FUNCTION_DCOPY, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DCOPY, and set_decision_data().
double liftracc_plugin_ddot (const int n, const double * x, const int incx, const double * y, const int incy)
Definition at line 236 of file cblas_plugin.c.
References CBLAS_FUNCTION_DDOT, decision_data, LIFTRACC_FUNCTION_DDOT, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DDOT, and set_decision_data().
void liftracc_plugin_dgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const double alpha, const double * a, const int lda, const double * x, const int incx, const double beta, double * y, const int incy)
Definition at line 1809 of file cblas_plugin.c.
References CBLAS_FUNCTION_DGBMV, decision_data, LIFTRACC_FUNCTION_DGBMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DGBMV, and set_decision_data().
void liftracc_plugin_dgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const double alpha, const double * a, const int lda, const double * b, const int ldb, const double beta, double * c, const int ldc)
Definition at line 3636 of file cblas_plugin.c.
References CBLAS_FUNCTION_DGEMM, decision_data, LIFTRACC_FUNCTION_DGEMM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DGEMM, and set_decision_data().
void liftracc_plugin_dgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const double alpha, const double * a, const int lda, const double * x, const int incx, const double beta, double * y, const int incy)
Definition at line 1780 of file cblas_plugin.c.
References CBLAS_FUNCTION_DGEMV, decision_data, LIFTRACC_FUNCTION_DGEMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DGEMV, and set_decision_data().
void liftracc_plugin_dger (const liftracc_order_t order, const int m, const int n, const double alpha, const double * x, const int incx, const double * y, const int incy, double * a, const int lda)
Definition at line 2795 of file cblas_plugin.c.
References CBLAS_FUNCTION_DGER, decision_data, LIFTRACC_FUNCTION_DGER, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DGER, and set_decision_data().
double liftracc_plugin_dnrm2 (const int n, const double * x, const int incx)
Definition at line 454 of file cblas_plugin.c.
References CBLAS_FUNCTION_DNRM2, decision_data, LIFTRACC_FUNCTION_DNRM2, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DNRM2, and set_decision_data().
void liftracc_plugin_drot (const int n, double * x, const int incx, double * y, const int incy, const double c, const double s)
Definition at line 1316 of file cblas_plugin.c.
References CBLAS_FUNCTION_DROT, decision_data, LIFTRACC_FUNCTION_DROT, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DROT, and set_decision_data().
void liftracc_plugin_drotg (double * a, double * b, double * c, double * s)
Definition at line 1258 of file cblas_plugin.c.
References CBLAS_FUNCTION_DROTG, decision_data, LIFTRACC_FUNCTION_DROTG, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DROTG, and set_decision_data().
void liftracc_plugin_drotm (const int n, double * x, const int incx, double * y, const int incy, const double * p)
Definition at line 1345 of file cblas_plugin.c.
References CBLAS_FUNCTION_DROTM, decision_data, LIFTRACC_FUNCTION_DROTM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DROTM, and set_decision_data().
void liftracc_plugin_drotmg (double * d1, double * d2, double * b1, const double b2, double * p)
Definition at line 1287 of file cblas_plugin.c.
References CBLAS_FUNCTION_DROTMG, decision_data, LIFTRACC_FUNCTION_DROTMG, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DROTMG, and set_decision_data().
void liftracc_plugin_dsbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const double alpha, const double * a, const int lda, const double * x, const int incx, const double beta, double * y, const int incy)
Definition at line 2737 of file cblas_plugin.c.
References CBLAS_FUNCTION_DSBMV, decision_data, LIFTRACC_FUNCTION_DSBMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DSBMV, and set_decision_data().
void liftracc_plugin_dscal (const int n, const double alpha, double * x, const int incx)
Definition at line 1403 of file cblas_plugin.c.
References CBLAS_FUNCTION_DSCAL, decision_data, LIFTRACC_FUNCTION_DSCAL, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DSCAL, and set_decision_data().
double liftracc_plugin_dsdot (const int n, const float * x, const int incx, const float * y, const int incy)
Definition at line 168 of file cblas_plugin.c.
References CBLAS_FUNCTION_DSDOT, decision_data, LIFTRACC_FUNCTION_DSDOT, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DSDOT, and set_decision_data().
void liftracc_plugin_dspmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double * ap, const double * x, const int incx, const double beta, double * y, const int incy)
Definition at line 2766 of file cblas_plugin.c.
References CBLAS_FUNCTION_DSPMV, decision_data, LIFTRACC_FUNCTION_DSPMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DSPMV, and set_decision_data().
void liftracc_plugin_dspr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double * x, const int incx, double * ap)
Definition at line 2853 of file cblas_plugin.c.
References CBLAS_FUNCTION_DSPR, decision_data, LIFTRACC_FUNCTION_DSPR, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DSPR, and set_decision_data().
void liftracc_plugin_dspr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double * x, const int incx, const double * y, const int incy, double * a)
Definition at line 2911 of file cblas_plugin.c.
References CBLAS_FUNCTION_DSPR2, decision_data, LIFTRACC_FUNCTION_DSPR2, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DSPR2, and set_decision_data().
void liftracc_plugin_dswap (const int n, double * x, const int incx, double * y, const int incy)
Definition at line 881 of file cblas_plugin.c.
References CBLAS_FUNCTION_DSWAP, decision_data, LIFTRACC_FUNCTION_DSWAP, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DSWAP, and set_decision_data().
void liftracc_plugin_dsymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const double alpha, const double * a, const int lda, const double * b, const int ldb, const double beta, double * c, const int ldc)
Definition at line 3665 of file cblas_plugin.c.
References CBLAS_FUNCTION_DSYMM, decision_data, LIFTRACC_FUNCTION_DSYMM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DSYMM, and set_decision_data().
void liftracc_plugin_dsymv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double * a, const int lda, const double * x, const int incx, const double beta, double * y, const int incy)
Definition at line 2708 of file cblas_plugin.c.
References CBLAS_FUNCTION_DSYMV, decision_data, LIFTRACC_FUNCTION_DSYMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DSYMV, and set_decision_data().
void liftracc_plugin_dsyr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double * x, const int incx, double * a, const int lda)
Definition at line 2824 of file cblas_plugin.c.
References CBLAS_FUNCTION_DSYR, decision_data, LIFTRACC_FUNCTION_DSYR, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DSYR, and set_decision_data().
void liftracc_plugin_dsyr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double * x, const int incx, const double * y, const int incy, double * a, const int lda)
Definition at line 2882 of file cblas_plugin.c.
References CBLAS_FUNCTION_DSYR2, decision_data, LIFTRACC_FUNCTION_DSYR2, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DSYR2, and set_decision_data().
void liftracc_plugin_dsyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const double alpha, const double * a, const int lda, const double * b, const int ldb, const double beta, double * c, const int ldc)
Definition at line 3723 of file cblas_plugin.c.
References CBLAS_FUNCTION_DSYR2K, decision_data, LIFTRACC_FUNCTION_DSYR2K, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DSYR2K, and set_decision_data().
void liftracc_plugin_dsyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const double alpha, const double * a, const int lda, const double beta, double * c, const int ldc)
Definition at line 3694 of file cblas_plugin.c.
References CBLAS_FUNCTION_DSYRK, decision_data, LIFTRACC_FUNCTION_DSYRK, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DSYRK, and set_decision_data().
void liftracc_plugin_dtbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const double * a, const int lda, double * x, const int incx)
Definition at line 1867 of file cblas_plugin.c.
References CBLAS_FUNCTION_DTBMV, decision_data, LIFTRACC_FUNCTION_DTBMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DTBMV, and set_decision_data().
void liftracc_plugin_dtbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const double * a, const int lda, double * x, const int incx)
Definition at line 1954 of file cblas_plugin.c.
References CBLAS_FUNCTION_DTBSV, decision_data, LIFTRACC_FUNCTION_DTBSV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DTBSV, and set_decision_data().
void liftracc_plugin_dtpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double * ap, double * x, const int incx)
Definition at line 1896 of file cblas_plugin.c.
References CBLAS_FUNCTION_DTPMV, decision_data, LIFTRACC_FUNCTION_DTPMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DTPMV, and set_decision_data().
void liftracc_plugin_dtpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double * ap, double * x, const int incx)
Definition at line 1983 of file cblas_plugin.c.
References CBLAS_FUNCTION_DTPSV, decision_data, LIFTRACC_FUNCTION_DTPSV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DTPSV, and set_decision_data().
void liftracc_plugin_dtrmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const double alpha, const double * a, const int lda, double * b, const int ldb)
Definition at line 3752 of file cblas_plugin.c.
References CBLAS_FUNCTION_DTRMM, decision_data, LIFTRACC_FUNCTION_DTRMM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DTRMM, and set_decision_data().
void liftracc_plugin_dtrmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double * a, const int lda, double * x, const int incx)
Definition at line 1838 of file cblas_plugin.c.
References CBLAS_FUNCTION_DTRMV, decision_data, LIFTRACC_FUNCTION_DTRMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DTRMV, and set_decision_data().
void liftracc_plugin_dtrsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const double alpha, const double * a, const int lda, double * b, const int ldb)
Definition at line 3781 of file cblas_plugin.c.
References CBLAS_FUNCTION_DTRSM, decision_data, LIFTRACC_FUNCTION_DTRSM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DTRSM, and set_decision_data().
void liftracc_plugin_dtrsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double * a, const int lda, double * x, const int incx)
Definition at line 1925 of file cblas_plugin.c.
References CBLAS_FUNCTION_DTRSV, decision_data, LIFTRACC_FUNCTION_DTRSV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DTRSV, and set_decision_data().
double liftracc_plugin_dzasum (const int n, const void * x, const int incx)
Definition at line 624 of file cblas_plugin.c.
References CBLAS_FUNCTION_DZASUM, decision_data, LIFTRACC_FUNCTION_DZASUM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DZASUM, and set_decision_data().
double liftracc_plugin_dznrm2 (const int n, const void * x, const int incx)
Definition at line 590 of file cblas_plugin.c.
References CBLAS_FUNCTION_DZNRM2, decision_data, LIFTRACC_FUNCTION_DZNRM2, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DZNRM2, and set_decision_data().
decision_data_t liftracc_plugin_getdecision (liftracc_selector_funcid_t id, int index)
Definition at line 113 of file cblas_plugin.c.
References decision_data, and plugin_info_t::prio.
liftracc_index_t liftracc_plugin_icamax (const int n, const void * x, const int incx)
Definition at line 726 of file cblas_plugin.c.
References CBLAS_FUNCTION_ICAMAX, decision_data, LIFTRACC_FUNCTION_ICAMAX, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_ICAMAX, and set_decision_data().
liftracc_index_t liftracc_plugin_idamax (const int n, const double * x, const int incx)
Definition at line 692 of file cblas_plugin.c.
References CBLAS_FUNCTION_IDAMAX, decision_data, LIFTRACC_FUNCTION_IDAMAX, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_IDAMAX, and set_decision_data().
liftracc_index_t liftracc_plugin_isamax (const int n, const float * x, const int incx)
Definition at line 658 of file cblas_plugin.c.
References CBLAS_FUNCTION_ISAMAX, decision_data, LIFTRACC_FUNCTION_ISAMAX, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_ISAMAX, and set_decision_data().
liftracc_index_t liftracc_plugin_izamax (const int n, const void * x, const int incx)
Definition at line 760 of file cblas_plugin.c.
References CBLAS_FUNCTION_IZAMAX, decision_data, LIFTRACC_FUNCTION_IZAMAX, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_IZAMAX, and set_decision_data().
float liftracc_plugin_sasum (const int n, const float * x, const int incx)
Definition at line 420 of file cblas_plugin.c.
References CBLAS_FUNCTION_SASUM, decision_data, LIFTRACC_FUNCTION_SASUM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SASUM, and set_decision_data().
void liftracc_plugin_saxpy (const int n, const float alpha, const float * x, const int incx, float * y, const int incy)
Definition at line 852 of file cblas_plugin.c.
References CBLAS_FUNCTION_SAXPY, decision_data, LIFTRACC_FUNCTION_SAXPY, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SAXPY, and set_decision_data().
float liftracc_plugin_scasum (const int n, const void * x, const int incx)
Definition at line 556 of file cblas_plugin.c.
References CBLAS_FUNCTION_SCASUM, decision_data, LIFTRACC_FUNCTION_SCASUM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SCASUM, and set_decision_data().
float liftracc_plugin_scnrm2 (const int n, const void * x, const int incx)
Definition at line 522 of file cblas_plugin.c.
References CBLAS_FUNCTION_SCNRM2, decision_data, LIFTRACC_FUNCTION_SCNRM2, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SCNRM2, and set_decision_data().
void liftracc_plugin_scopy (const int n, const float * x, const int incx, float * y, const int incy)
Definition at line 823 of file cblas_plugin.c.
References CBLAS_FUNCTION_SCOPY, decision_data, LIFTRACC_FUNCTION_SCOPY, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SCOPY, and set_decision_data().
float liftracc_plugin_sdot (const int n, const float * x, const int incx, const float * y, const int incy)
Definition at line 202 of file cblas_plugin.c.
References CBLAS_FUNCTION_SDOT, decision_data, LIFTRACC_FUNCTION_SDOT, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SDOT, and set_decision_data().
float liftracc_plugin_sdsdot (const int n, const float alpha, const float * x, const int incx, const float * y, const int incy)
Definition at line 134 of file cblas_plugin.c.
References CBLAS_FUNCTION_SDSDOT, decision_data, LIFTRACC_FUNCTION_SDSDOT, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SDSDOT, and set_decision_data().
void liftracc_plugin_sgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const float alpha, const float * a, const int lda, const float * x, const int incx, const float beta, float * y, const int incy)
Definition at line 1577 of file cblas_plugin.c.
References CBLAS_FUNCTION_SGBMV, decision_data, LIFTRACC_FUNCTION_SGBMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SGBMV, and set_decision_data().
void liftracc_plugin_sgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const float alpha, const float * a, const int lda, const float * b, const int ldb, const float beta, float * c, const int ldc)
Definition at line 3462 of file cblas_plugin.c.
References CBLAS_FUNCTION_SGEMM, decision_data, LIFTRACC_FUNCTION_SGEMM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SGEMM, and set_decision_data().
void liftracc_plugin_sgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const float alpha, const float * a, const int lda, const float * x, const int incx, const float beta, float * y, const int incy)
Definition at line 1548 of file cblas_plugin.c.
References CBLAS_FUNCTION_SGEMV, decision_data, LIFTRACC_FUNCTION_SGEMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SGEMV, and set_decision_data().
void liftracc_plugin_sger (const liftracc_order_t order, const int m, const int n, const float alpha, const float * x, const int incx, const float * y, const int incy, float * a, const int lda)
Definition at line 2563 of file cblas_plugin.c.
References CBLAS_FUNCTION_SGER, decision_data, LIFTRACC_FUNCTION_SGER, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SGER, and set_decision_data().
float liftracc_plugin_snrm2 (const int n, const float * x, const int incx)
Definition at line 386 of file cblas_plugin.c.
References CBLAS_FUNCTION_SNRM2, decision_data, LIFTRACC_FUNCTION_SNRM2, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SNRM2, and set_decision_data().
void liftracc_plugin_srot (const int n, float * x, const int incx, float * y, const int incy, const float c, const float s)
Definition at line 1200 of file cblas_plugin.c.
References CBLAS_FUNCTION_SROT, decision_data, LIFTRACC_FUNCTION_SROT, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SROT, and set_decision_data().
void liftracc_plugin_srotg (float * a, float * b, float * c, float * s)
Definition at line 1142 of file cblas_plugin.c.
References CBLAS_FUNCTION_SROTG, decision_data, LIFTRACC_FUNCTION_SROTG, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SROTG, and set_decision_data().
void liftracc_plugin_srotm (const int n, float * x, const int incx, float * y, const int incy, const float * p)
Definition at line 1229 of file cblas_plugin.c.
References CBLAS_FUNCTION_SROTM, decision_data, LIFTRACC_FUNCTION_SROTM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SROTM, and set_decision_data().
void liftracc_plugin_srotmg (float * d1, float * d2, float * b1, const float b2, float * p)
Definition at line 1171 of file cblas_plugin.c.
References CBLAS_FUNCTION_SROTMG, decision_data, LIFTRACC_FUNCTION_SROTMG, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SROTMG, and set_decision_data().
void liftracc_plugin_ssbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const float alpha, const float * a, const int lda, const float * x, const int incx, const float beta, float * y, const int incy)
Definition at line 2505 of file cblas_plugin.c.
References CBLAS_FUNCTION_SSBMV, decision_data, LIFTRACC_FUNCTION_SSBMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SSBMV, and set_decision_data().
void liftracc_plugin_sscal (const int n, const float alpha, float * x, const int incx)
Definition at line 1374 of file cblas_plugin.c.
References CBLAS_FUNCTION_SSCAL, decision_data, LIFTRACC_FUNCTION_SSCAL, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SSCAL, and set_decision_data().
void liftracc_plugin_sspmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float * ap, const float * x, const int incx, const float beta, float * y, const int incy)
Definition at line 2534 of file cblas_plugin.c.
References CBLAS_FUNCTION_SSPMV, decision_data, LIFTRACC_FUNCTION_SSPMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SSPMV, and set_decision_data().
void liftracc_plugin_sspr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float * x, const int incx, float * ap)
Definition at line 2621 of file cblas_plugin.c.
References CBLAS_FUNCTION_SSPR, decision_data, LIFTRACC_FUNCTION_SSPR, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SSPR, and set_decision_data().
void liftracc_plugin_sspr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float * x, const int incx, const float * y, const int incy, float * a)
Definition at line 2679 of file cblas_plugin.c.
References CBLAS_FUNCTION_SSPR2, decision_data, LIFTRACC_FUNCTION_SSPR2, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SSPR2, and set_decision_data().
void liftracc_plugin_sswap (const int n, float * x, const int incx, float * y, const int incy)
Definition at line 794 of file cblas_plugin.c.
References CBLAS_FUNCTION_SSWAP, decision_data, LIFTRACC_FUNCTION_SSWAP, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SSWAP, and set_decision_data().
void liftracc_plugin_ssymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const float alpha, const float * a, const int lda, const float * b, const int ldb, const float beta, float * c, const int ldc)
Definition at line 3491 of file cblas_plugin.c.
References CBLAS_FUNCTION_SSYMM, decision_data, LIFTRACC_FUNCTION_SSYMM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SSYMM, and set_decision_data().
void liftracc_plugin_ssymv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float * a, const int lda, const float * x, const int incx, const float beta, float * y, const int incy)
Definition at line 2476 of file cblas_plugin.c.
References CBLAS_FUNCTION_SSYMV, decision_data, LIFTRACC_FUNCTION_SSYMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SSYMV, and set_decision_data().
void liftracc_plugin_ssyr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float * x, const int incx, float * a, const int lda)
Definition at line 2592 of file cblas_plugin.c.
References CBLAS_FUNCTION_SSYR, decision_data, LIFTRACC_FUNCTION_SSYR, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SSYR, and set_decision_data().
void liftracc_plugin_ssyr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float * x, const int incx, const float * y, const int incy, float * a, const int lda)
Definition at line 2650 of file cblas_plugin.c.
References CBLAS_FUNCTION_SSYR2, decision_data, LIFTRACC_FUNCTION_SSYR2, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SSYR2, and set_decision_data().
void liftracc_plugin_ssyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const float alpha, const float * a, const int lda, const float * b, const int ldb, const float beta, float * c, const int ldc)
Definition at line 3549 of file cblas_plugin.c.
References CBLAS_FUNCTION_SSYR2K, decision_data, LIFTRACC_FUNCTION_SSYR2K, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SSYR2K, and set_decision_data().
void liftracc_plugin_ssyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const float alpha, const float * a, const int lda, const float beta, float * c, const int ldc)
Definition at line 3520 of file cblas_plugin.c.
References CBLAS_FUNCTION_SSYRK, decision_data, LIFTRACC_FUNCTION_SSYRK, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_SSYRK, and set_decision_data().
void liftracc_plugin_stbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const float * a, const int lda, float * x, const int incx)
Definition at line 1635 of file cblas_plugin.c.
References CBLAS_FUNCTION_STBMV, decision_data, LIFTRACC_FUNCTION_STBMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_STBMV, and set_decision_data().
void liftracc_plugin_stbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const float * a, const int lda, float * x, const int incx)
Definition at line 1722 of file cblas_plugin.c.
References CBLAS_FUNCTION_STBSV, decision_data, LIFTRACC_FUNCTION_STBSV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_STBSV, and set_decision_data().
void liftracc_plugin_stpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float * ap, float * x, const int incx)
Definition at line 1664 of file cblas_plugin.c.
References CBLAS_FUNCTION_STPMV, decision_data, LIFTRACC_FUNCTION_STPMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_STPMV, and set_decision_data().
void liftracc_plugin_stpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float * ap, float * x, const int incx)
Definition at line 1751 of file cblas_plugin.c.
References CBLAS_FUNCTION_STPSV, decision_data, LIFTRACC_FUNCTION_STPSV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_STPSV, and set_decision_data().
void liftracc_plugin_strmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const float alpha, const float * a, const int lda, float * b, const int ldb)
Definition at line 3578 of file cblas_plugin.c.
References CBLAS_FUNCTION_STRMM, decision_data, LIFTRACC_FUNCTION_STRMM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_STRMM, and set_decision_data().
void liftracc_plugin_strmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float * a, const int lda, float * x, const int incx)
Definition at line 1606 of file cblas_plugin.c.
References CBLAS_FUNCTION_STRMV, decision_data, LIFTRACC_FUNCTION_STRMV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_STRMV, and set_decision_data().
void liftracc_plugin_strsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const float alpha, const float * a, const int lda, float * b, const int ldb)
Definition at line 3607 of file cblas_plugin.c.
References CBLAS_FUNCTION_STRSM, decision_data, LIFTRACC_FUNCTION_STRSM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_STRSM, and set_decision_data().
void liftracc_plugin_strsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float * a, const int lda, float * x, const int incx)
Definition at line 1693 of file cblas_plugin.c.
References CBLAS_FUNCTION_STRSV, decision_data, LIFTRACC_FUNCTION_STRSV, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_STRSV, and set_decision_data().
void liftracc_plugin_xerbla (int p, const char * rout, const char * form)
Definition at line 4332 of file cblas_plugin.c.
References CBLAS_FUNCTION_XERBLA, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_XERBLA, liftracc_plugin_fptr, plugin_info_t::name, SELECT_XERBLA, and set_decision_data().
void liftracc_plugin_zaxpy (const int n, const void * alpha, const void * x, const int incx, void * y, const int incy)
Definition at line 1113 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZAXPY, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZAXPY, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZAXPY, and set_decision_data().
void liftracc_plugin_zcopy (const int n, const void * x, const int incx, void * y, const int incy)
Definition at line 1084 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZCOPY, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZCOPY, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZCOPY, and set_decision_data().
void liftracc_plugin_zdotc_sub (const int n, const void * x, const int incx, const void * y, const int incy, void * dotc)
Definition at line 357 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZDOTC_SUB, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZDOTC_SUB, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZDOTC_SUB, and set_decision_data().
void liftracc_plugin_zdotu_sub (const int n, const void * x, const int incx, const void * y, const int incy, void * dotu)
Definition at line 328 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZDOTU_SUB, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZDOTU_SUB, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZDOTU_SUB, and set_decision_data().
void liftracc_plugin_zdscal (const int n, const double alpha, void * x, const int incx)
Definition at line 1519 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZDSCAL, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZDSCAL, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZDSCAL, and set_decision_data().
void liftracc_plugin_zgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 2273 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZGBMV, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZGBMV, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZGBMV, and set_decision_data().
void liftracc_plugin_zgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
Definition at line 3984 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZGEMM, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZGEMM, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZGEMM, and set_decision_data().
void liftracc_plugin_zgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 2244 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZGEMV, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZGEMV, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZGEMV, and set_decision_data().
void liftracc_plugin_zgerc (const liftracc_order_t order, const int m, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * a, const int lda)
Definition at line 3317 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZGERC, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZGERC, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZGERC, and set_decision_data().
void liftracc_plugin_zgeru (const liftracc_order_t order, const int m, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * a, const int lda)
Definition at line 3288 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZGERU, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZGERU, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZGERU, and set_decision_data().
void liftracc_plugin_zhbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 3230 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZHBMV, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZHBMV, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZHBMV, and set_decision_data().
void liftracc_plugin_zhemm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
Definition at line 4245 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZHEMM, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZHEMM, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZHEMM, and set_decision_data().
void liftracc_plugin_zhemv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 3201 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZHEMV, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZHEMV, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZHEMV, and set_decision_data().
void liftracc_plugin_zher (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const void * x, const int incx, void * a, const int lda)
Definition at line 3346 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZHER, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZHER, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZHER, and set_decision_data().
void liftracc_plugin_zher2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * a, const int lda)
Definition at line 3404 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZHER2, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZHER2, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZHER2, and set_decision_data().
void liftracc_plugin_zher2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const double beta, void * c, const int ldc)
Definition at line 4303 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZHER2K, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZHER2K, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZHER2K, and set_decision_data().
void liftracc_plugin_zherk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const double alpha, const void * a, const int lda, const double beta, void * c, const int ldc)
Definition at line 4274 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZHERK, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZHERK, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZHERK, and set_decision_data().
void liftracc_plugin_zhpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * ap, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 3259 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZHPMV, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZHPMV, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZHPMV, and set_decision_data().
void liftracc_plugin_zhpr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const void * x, const int incx, void * a)
Definition at line 3375 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZHPR, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZHPR, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZHPR, and set_decision_data().
void liftracc_plugin_zhpr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * ap)
Definition at line 3433 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZHPR2, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZHPR2, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZHPR2, and set_decision_data().
void liftracc_plugin_zscal (const int n, const void * alpha, void * x, const int incx)
Definition at line 1461 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZSCAL, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZSCAL, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZSCAL, and set_decision_data().
void liftracc_plugin_zswap (const int n, void * x, const int incx, void * y, const int incy)
Definition at line 1055 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZSWAP, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZSWAP, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZSWAP, and set_decision_data().
void liftracc_plugin_zsymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
Definition at line 4013 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZSYMM, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZSYMM, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZSYMM, and set_decision_data().
void liftracc_plugin_zsyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
Definition at line 4071 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZSYR2K, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZSYR2K, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZSYR2K, and set_decision_data().
void liftracc_plugin_zsyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void * alpha, const void * a, const int lda, const void * beta, void * c, const int ldc)
Definition at line 4042 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZSYRK, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZSYRK, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZSYRK, and set_decision_data().
void liftracc_plugin_ztbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void * a, const int lda, void * x, const int incx)
Definition at line 2331 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZTBMV, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZTBMV, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZTBMV, and set_decision_data().
void liftracc_plugin_ztbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void * a, const int lda, void * x, const int incx)
Definition at line 2418 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZTBSV, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZTBSV, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZTBSV, and set_decision_data().
void liftracc_plugin_ztpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * ap, void * x, const int incx)
Definition at line 2360 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZTPMV, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZTPMV, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZTPMV, and set_decision_data().
void liftracc_plugin_ztpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * ap, void * x, const int incx)
Definition at line 2447 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZTPSV, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZTPSV, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZTPSV, and set_decision_data().
void liftracc_plugin_ztrmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void * alpha, const void * a, const int lda, void * b, const int ldb)
Definition at line 4100 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZTRMM, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZTRMM, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZTRMM, and set_decision_data().
void liftracc_plugin_ztrmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * a, const int lda, void * x, const int incx)
Definition at line 2302 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZTRMV, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZTRMV, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZTRMV, and set_decision_data().
void liftracc_plugin_ztrsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void * alpha, const void * a, const int lda, void * b, const int ldb)
Definition at line 4129 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZTRSM, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZTRSM, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZTRSM, and set_decision_data().
void liftracc_plugin_ztrsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * a, const int lda, void * x, const int incx)
Definition at line 2389 of file cblas_plugin.c.
References CBLAS_FUNCTION_ZTRSV, decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTION_ZTRSV, liftracc_plugin_fptr, plugin_info_t::name, SELECT_ZTRSV, and set_decision_data().
Variable Documentation
decision_data_t decision_data[FUNCTION_COUNT *ARRAY_SIZE] = { }
Definition at line 30 of file cblas_plugin.c.
char* error = 0
Definition at line 42 of file cblas_plugin.c.
profiling_data_t function_profiling_data[LIFTRACC_FUNCTIONS_COUNT] = { }
Definition at line 27 of file cblas_plugin.c.
void* handle = 0
Definition at line 41 of file cblas_plugin.c.
void* liftracc_plugin_fptr[CBLAS_FUNCTIONS_COUNT] = { }
Definition at line 32 of file cblas_plugin.c.
plugin_info_t liftracc_plugin_info
Initial value:
 {
    .uuid = "f4a17438-80ed-4f9f-90f1-1728df8ea630",
    .name = "liftracc_cblas_plugin",
    .desc = "wrapper to standard blas library",
    .prio = 1
}
Definition at line 34 of file cblas_plugin.c.