libliftracc: src/plugins/clearspeed_plugin.c File Reference
src/plugins/clearspeed_plugin.c File Reference
Plugin to support the Clearspeed library.
Enumerations
enum liftracc_clear_functions_t { CLEAR_DGEMM_ID, CLEAR_FUNCTIONS_COUNT }
Functions
void __attribute__ ((constructor))
void __attribute__ ((destructor))
decision_data_t liftracc_plugin_getdecision (liftracc_selector_funcid_t id, int index)
void liftracc_plugin_dgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const double alpha, const double *a, const int lda, const double *b, const int ldb, const double beta, double *c, const int ldc)
Variables
profiling_data_t function_profiling_data [LIFTRACC_FUNCTIONS_COUNT] = {}
decision_data_t decision_data [FUNCTION_COUNT *ARRAY_SIZE] = {}
const char * liftracc_clear_function_names []
void * liftracc_plugin_fptr [CLEAR_FUNCTIONS_COUNT] = { }
plugin_info_t liftracc_plugin_info
void * handle = 0
char * error = 0
Detailed Description
Plugin to support the Clearspeed library.
Definition in file clearspeed_plugin.c.
Enumeration Type Documentation
enum liftracc_clear_functions_t
Enumerator:
CLEAR_DGEMM_ID
CLEAR_FUNCTIONS_COUNT
Definition at line 26 of file clearspeed_plugin.c.
Function Documentation
void __attribute__ ((constructor))
Definition at line 48 of file clearspeed_plugin.c.
References CLEAR_FUNCTIONS_COUNT, decision_data, handle, liftracc_clear_function_names, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_INIT, liftracc_plugin_fptr, liftracc_selector_loadinfo(), and plugin_info_t::name.
void __attribute__ ((destructor))
Definition at line 89 of file clearspeed_plugin.c.
References decision_data, handle, LIFTRACC_FINI, liftracc_function_names, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTIONS_COUNT, liftracc_selector_saveinfo(), plugin_info_t::name, and print_profiling_data().
void liftracc_plugin_dgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const double alpha, const double * a, const int lda, const double * b, const int ldb, const double beta, double * c, const int ldc)
Definition at line 130 of file clearspeed_plugin.c.
References CLEAR_DGEMM_ID, decision_data, liftracc_col_major, liftracc_conj_trans, LIFTRACC_FUNCTION_DGEMM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_no_trans, liftracc_plugin_fptr, liftracc_trans, plugin_info_t::name, SELECT_DGEMM, and set_decision_data().
decision_data_t liftracc_plugin_getdecision (liftracc_selector_funcid_t id, int index)
Definition at line 117 of file clearspeed_plugin.c.
References decision_data, and plugin_info_t::prio.
Variable Documentation
decision_data_t decision_data[FUNCTION_COUNT *ARRAY_SIZE] = {}
Definition at line 24 of file clearspeed_plugin.c.
char* error = 0
Definition at line 46 of file clearspeed_plugin.c.
profiling_data_t function_profiling_data[LIFTRACC_FUNCTIONS_COUNT] = {}
Definition at line 21 of file clearspeed_plugin.c.
void* handle = 0
Definition at line 45 of file clearspeed_plugin.c.
const char* liftracc_clear_function_names[]
Initial value:
 {
    "DGEMM",
    "size_entry"
}
Definition at line 31 of file clearspeed_plugin.c.
Referenced by __attribute__().
void* liftracc_plugin_fptr[CLEAR_FUNCTIONS_COUNT] = { }
Definition at line 36 of file clearspeed_plugin.c.
plugin_info_t liftracc_plugin_info
Initial value:
 {
    .uuid = "7bedd79d-62b6-4210-b221-98ebf540057a",
    .name = "liftracc_clearspeed_plugin",
    .desc = "wrapper to clearspeed blas library",
    .prio = 30
}
Definition at line 38 of file clearspeed_plugin.c.