libliftracc: src/plugins/cublas_plugin.c File Reference
src/plugins/cublas_plugin.c File Reference
Plugin to support the CUBLAS library.
Functions
void __attribute__ ((constructor))
void __attribute__ ((destructor))
decision_data_t liftracc_plugin_getdecision (liftracc_selector_funcid_t id, int index)
void liftracc_plugin_daxpy (const int n, const double alpha, const double *x, const int incx, double *y, const int incy)
double liftracc_plugin_ddot (const int n, const double *x, const int incx, const double *y, const int incy)
void liftracc_plugin_dgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const double alpha, const double *a, const int lda, const double *b, const int ldb, const double beta, double *c, const int ldc)
void liftracc_plugin_dscal (const int n, const double alpha, double *x, const int incx)
liftracc_index_t liftracc_plugin_idamax (const int n, const double *x, const int incx)
Variables
profiling_data_t function_profiling_data [LIFTRACC_FUNCTIONS_COUNT] = {}
decision_data_t decision_data [FUNCTION_COUNT *ARRAY_SIZE] = {}
plugin_info_t liftracc_plugin_info
void * handle = 0
char * error = 0
Detailed Description
Plugin to support the CUBLAS library.
Definition in file cublas_plugin.c.
Function Documentation
void __attribute__ ((constructor))
Definition at line 38 of file cublas_plugin.c.
References decision_data, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_INIT, liftracc_selector_loadinfo(), and plugin_info_t::name.
void __attribute__ ((destructor))
Definition at line 67 of file cublas_plugin.c.
References decision_data, LIFTRACC_FINI, liftracc_function_names, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTIONS_COUNT, liftracc_selector_saveinfo(), plugin_info_t::name, and print_profiling_data().
void liftracc_plugin_daxpy (const int n, const double alpha, const double * x, const int incx, double * y, const int incy)
Definition at line 111 of file cublas_plugin.c.
References decision_data, LIFTRACC_FUNCTION_DAXPY, liftracc_function_timing_start(), liftracc_function_timing_stop(), plugin_info_t::name, SELECT_DAXPY, and set_decision_data().
double liftracc_plugin_ddot (const int n, const double * x, const int incx, const double * y, const int incy)
Definition at line 150 of file cublas_plugin.c.
References decision_data, LIFTRACC_FUNCTION_DDOT, liftracc_function_timing_start(), liftracc_function_timing_stop(), plugin_info_t::name, SELECT_DDOT, and set_decision_data().
void liftracc_plugin_dgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const double alpha, const double * a, const int lda, const double * b, const int ldb, const double beta, double * c, const int ldc)
Definition at line 189 of file cublas_plugin.c.
References decision_data, liftracc_col_major, liftracc_conj_trans, LIFTRACC_FUNCTION_DGEMM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_no_trans, liftracc_profiling_data, liftracc_trans, plugin_info_t::name, PARAM_CONV, SELECT_DGEMM, and set_decision_data().
void liftracc_plugin_dscal (const int n, const double alpha, double * x, const int incx)
Definition at line 277 of file cublas_plugin.c.
References decision_data, LIFTRACC_FUNCTION_DSCAL, liftracc_function_timing_start(), liftracc_function_timing_stop(), plugin_info_t::name, SELECT_DSCAL, and set_decision_data().
decision_data_t liftracc_plugin_getdecision (liftracc_selector_funcid_t id, int index)
Definition at line 98 of file cublas_plugin.c.
References decision_data, and plugin_info_t::prio.
liftracc_index_t liftracc_plugin_idamax (const int n, const double * x, const int incx)
Definition at line 310 of file cublas_plugin.c.
References decision_data, LIFTRACC_FUNCTION_IDAMAX, liftracc_function_timing_start(), liftracc_function_timing_stop(), plugin_info_t::name, SELECT_IDAMAX, and set_decision_data().
Variable Documentation
decision_data_t decision_data[FUNCTION_COUNT *ARRAY_SIZE] = {}
Definition at line 26 of file cublas_plugin.c.
char* error = 0
Definition at line 36 of file cublas_plugin.c.
profiling_data_t function_profiling_data[LIFTRACC_FUNCTIONS_COUNT] = {}
Definition at line 23 of file cublas_plugin.c.
void* handle = 0
Definition at line 35 of file cublas_plugin.c.
plugin_info_t liftracc_plugin_info
Initial value:
 {
    .uuid = "4241c224-99c9-4c44-979f-32c6ac5fc9a4",
    .name = "liftracc_cublas_plugin",
    .desc = "wrapper to cublas library",
    .prio = 20
}
Definition at line 28 of file cublas_plugin.c.