libliftracc: src/plugins/goto2_plugin.c File Reference
src/plugins/goto2_plugin.c File Reference
Plugin to support the Goto2 library.
Enumerations
enum liftracc_atlas_functions_t {
ATLAS_DAXPY_ID, ATLAS_DDOT_ID, ATLAS_DGEMM_ID, ATLAS_DSCAL_ID,
ATLAS_IDAMAX_ID, ATLAS_FUNCTIONS_COUNT, GOTO_DAXPY_ID, GOTO_DDOT_ID,
GOTO_DGEMM_ID, GOTO_DSCAL_ID, GOTO_IDAMAX_ID, GOTO_FUNCTIONS_COUNT
}
Functions
void __attribute__ ((constructor))
void __attribute__ ((destructor))
decision_data_t liftracc_plugin_getdecision (liftracc_selector_funcid_t id, int index)
void liftracc_plugin_daxpy (const int n, const double alpha, const double *x, const int incx, double *y, const int incy)
double liftracc_plugin_ddot (const int n, const double *x, const int incx, const double *y, const int incy)
void liftracc_plugin_dgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const double alpha, const double *a, const int lda, const double *b, const int ldb, const double beta, double *c, const int ldc)
void liftracc_plugin_dscal (const int n, const double alpha, double *x, const int incx)
liftracc_index_t liftracc_plugin_idamax (const int n, const double *x, const int incx)
Variables
profiling_data_t function_profiling_data [LIFTRACC_FUNCTIONS_COUNT] = {}
decision_data_t decision_data [FUNCTION_COUNT *ARRAY_SIZE] = {}
const char * liftracc_goto_function_names []
void * liftracc_plugin_fptr [GOTO_FUNCTIONS_COUNT] = { }
plugin_info_t liftracc_plugin_info
void * handle = 0
char * error = 0
Detailed Description
Plugin to support the Goto2 library.
Definition in file goto2_plugin.c.
Enumeration Type Documentation
enum liftracc_atlas_functions_t
Enumerator:
ATLAS_DAXPY_ID
ATLAS_DDOT_ID
ATLAS_DGEMM_ID
ATLAS_DSCAL_ID
ATLAS_IDAMAX_ID
ATLAS_FUNCTIONS_COUNT
GOTO_DAXPY_ID
GOTO_DDOT_ID
GOTO_DGEMM_ID
GOTO_DSCAL_ID
GOTO_IDAMAX_ID
GOTO_FUNCTIONS_COUNT
Definition at line 28 of file goto2_plugin.c.
Function Documentation
void __attribute__ ((constructor))
Definition at line 58 of file goto2_plugin.c.
References decision_data, GOTO_FUNCTIONS_COUNT, handle, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_goto_function_names, LIFTRACC_INIT, liftracc_plugin_fptr, liftracc_selector_loadinfo(), and plugin_info_t::name.
void __attribute__ ((destructor))
Definition at line 99 of file goto2_plugin.c.
References decision_data, handle, LIFTRACC_FINI, liftracc_function_names, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTIONS_COUNT, liftracc_selector_saveinfo(), plugin_info_t::name, and print_profiling_data().
void liftracc_plugin_daxpy (const int n, const double alpha, const double * x, const int incx, double * y, const int incy)
Definition at line 141 of file goto2_plugin.c.
References decision_data, GOTO_DAXPY_ID, LIFTRACC_FUNCTION_DAXPY, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DAXPY, and set_decision_data().
double liftracc_plugin_ddot (const int n, const double * x, const int incx, const double * y, const int incy)
Definition at line 167 of file goto2_plugin.c.
References decision_data, GOTO_DDOT_ID, LIFTRACC_FUNCTION_DDOT, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DDOT, and set_decision_data().
void liftracc_plugin_dgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const double alpha, const double * a, const int lda, const double * b, const int ldb, const double beta, double * c, const int ldc)
Definition at line 195 of file goto2_plugin.c.
References decision_data, GOTO_DGEMM_ID, LIFTRACC_FUNCTION_DGEMM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DGEMM, and set_decision_data().
void liftracc_plugin_dscal (const int n, const double alpha, double * x, const int incx)
Definition at line 225 of file goto2_plugin.c.
References decision_data, GOTO_DSCAL_ID, LIFTRACC_FUNCTION_DSCAL, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_DSCAL, and set_decision_data().
decision_data_t liftracc_plugin_getdecision (liftracc_selector_funcid_t id, int index)
Definition at line 128 of file goto2_plugin.c.
References decision_data, and plugin_info_t::prio.
liftracc_index_t liftracc_plugin_idamax (const int n, const double * x, const int incx)
Definition at line 250 of file goto2_plugin.c.
References decision_data, GOTO_IDAMAX_ID, LIFTRACC_FUNCTION_IDAMAX, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_plugin_fptr, plugin_info_t::name, SELECT_IDAMAX, and set_decision_data().
Variable Documentation
decision_data_t decision_data[FUNCTION_COUNT *ARRAY_SIZE] = {}
Definition at line 26 of file goto2_plugin.c.
char* error = 0
Definition at line 56 of file goto2_plugin.c.
profiling_data_t function_profiling_data[LIFTRACC_FUNCTIONS_COUNT] = {}
Definition at line 23 of file goto2_plugin.c.
void* handle = 0
Definition at line 55 of file goto2_plugin.c.
const char* liftracc_goto_function_names[]
Initial value:
 {
    "cblas_daxpy",
    "cblas_ddot",
    "cblas_dgemm",
    "cblas_dscal",
    "cblas_idamax",
    "size_entry"
}
Definition at line 37 of file goto2_plugin.c.
Referenced by __attribute__().
void* liftracc_plugin_fptr[GOTO_FUNCTIONS_COUNT] = { }
Definition at line 46 of file goto2_plugin.c.
plugin_info_t liftracc_plugin_info
Initial value:
 {
    .uuid = "829a1670-46b0-450e-9f85-3d6a65a9efcb",
    .name = "liftracc_libgoto2_plugin",
    .desc = "wrapper to libgoto2 blas library",
    .prio = 40,
}
Definition at line 48 of file goto2_plugin.c.