libliftracc: Selector Component
Selector Component
Data Structures
struct liftracc_selector_problem_info_t
Struct to describe the problem.
Typedefs
typedef ticks decision_data_t
Enumerations
enum liftracc_selector_error_t {
NO_ERROR, NO_LIBS_FOUND_ERROR, LIBS_OPEN_ERROR, LIBS_CLOSE_ERROR,
FUNCTION_NOT_FOUND_ERROR, FILE_NOT_FOUND_ERROR, DATA_READ_ERROR, DATA_WRITE_ERROR
}
Enumeration of error states.
enum liftracc_selector_funcid_t {
SELECT_SDSDOT, SELECT_DSDOT, SELECT_SDOT, SELECT_DDOT,
SELECT_CDOTU_SUB, SELECT_CDOTC_SUB, SELECT_ZDOTU_SUB, SELECT_ZDOTC_SUB,
SELECT_SNRM2, SELECT_SASUM, SELECT_DNRM2, SELECT_DASUM,
SELECT_SCNRM2, SELECT_SCASUM, SELECT_DZNRM2, SELECT_DZASUM,
SELECT_ISAMAX, SELECT_IDAMAX, SELECT_ICAMAX, SELECT_IZAMAX,
SELECT_SSWAP, SELECT_SCOPY, SELECT_SAXPY, SELECT_DSWAP,
SELECT_DCOPY, SELECT_DAXPY, SELECT_CSWAP, SELECT_CCOPY,
SELECT_CAXPY, SELECT_ZSWAP, SELECT_ZCOPY, SELECT_ZAXPY,
SELECT_SROTG, SELECT_SROTMG, SELECT_SROT, SELECT_SROTM,
SELECT_DROTG, SELECT_DROTMG, SELECT_DROT, SELECT_DROTM,
SELECT_SSCAL, SELECT_DSCAL, SELECT_CSCAL, SELECT_ZSCAL,
SELECT_CSSCAL, SELECT_ZDSCAL, SELECT_SGEMV, SELECT_SGBMV,
SELECT_STRMV, SELECT_STBMV, SELECT_STPMV, SELECT_STRSV,
SELECT_STBSV, SELECT_STPSV, SELECT_DGEMV, SELECT_DGBMV,
SELECT_DTRMV, SELECT_DTBMV, SELECT_DTPMV, SELECT_DTRSV,
SELECT_DTBSV, SELECT_DTPSV, SELECT_CGEMV, SELECT_CGBMV,
SELECT_CTRMV, SELECT_CTBMV, SELECT_CTPMV, SELECT_CTRSV,
SELECT_CTBSV, SELECT_CTPSV, SELECT_ZGEMV, SELECT_ZGBMV,
SELECT_ZTRMV, SELECT_ZTBMV, SELECT_ZTPMV, SELECT_ZTRSV,
SELECT_ZTBSV, SELECT_ZTPSV, SELECT_SSYMV, SELECT_SSBMV,
SELECT_SSPMV, SELECT_SGER, SELECT_SSYR, SELECT_SSPR,
SELECT_SSYR2, SELECT_SSPR2, SELECT_DSYMV, SELECT_DSBMV,
SELECT_DSPMV, SELECT_DGER, SELECT_DSYR, SELECT_DSPR,
SELECT_DSYR2, SELECT_DSPR2, SELECT_CHEMV, SELECT_CHBMV,
SELECT_CHPMV, SELECT_CGERU, SELECT_CGERC, SELECT_CHER,
SELECT_CHPR, SELECT_CHER2, SELECT_CHPR2, SELECT_ZHEMV,
SELECT_ZHBMV, SELECT_ZHPMV, SELECT_ZGERU, SELECT_ZGERC,
SELECT_ZHER, SELECT_ZHPR, SELECT_ZHER2, SELECT_ZHPR2,
SELECT_SGEMM, SELECT_SSYMM, SELECT_SSYRK, SELECT_SSYR2K,
SELECT_STRMM, SELECT_STRSM, SELECT_DGEMM, SELECT_DSYMM,
SELECT_DSYRK, SELECT_DSYR2K, SELECT_DTRMM, SELECT_DTRSM,
SELECT_CGEMM, SELECT_CSYMM, SELECT_CSYRK, SELECT_CSYR2K,
SELECT_CTRMM, SELECT_CTRSM, SELECT_ZGEMM, SELECT_ZSYMM,
SELECT_ZSYRK, SELECT_ZSYR2K, SELECT_ZTRMM, SELECT_ZTRSM,
SELECT_CHEMM, SELECT_CHERK, SELECT_CHER2K, SELECT_ZHEMM,
SELECT_ZHERK, SELECT_ZHER2K, SELECT_XERBLA, CALLTEST_DYNAMIC,
FUNCTION_COUNT
}
Enumeration of selector function ids.
Functions
static __inline__ unsigned int get_inx (unsigned int probsize, unsigned int max)
Calculate the index in array.
liftracc_selector_error_t liftracc_selector_load_plugins ()
liftracc_selector_error_t liftracc_selector_init ()
Selector component init function.
liftracc_selector_error_t liftracc_selector_fini ()
Selector component finalize function.
void * liftracc_selector_select (const liftracc_selector_funcid_t func_id, const liftracc_selector_problem_info_t *problem_info)
Selects function pointer to use from LUT.
void * liftracc_selector_select (const char *symbol_name)
Select function pointer to use in LUT.
liftracc_selector_error_t liftracc_selector_loadinfo (const char *file_name, decision_data_t *array)
Load decision info's from file.
liftracc_selector_error_t liftracc_selector_saveinfo (const char *file_name, decision_data_t *array)
Save decision info's to file.
Variables
char * error = 0
int liftracc_found_libs = 0
char liftracc_library_path [PATH_MAX] = { }
void ** liftracc_plugin_handles = 0
decision_data_t liftracc_decision_table [FUNCTION_COUNT][ARRAY_SIZE] = { }
The decision table.
void * liftracc_fptr_lut [FUNCTION_COUNT][ARRAY_SIZE] = { }
The look up table.
void * liftracc_preferred_fptr [FUNCTION_COUNT] = {}
Preferred function pointers.
char liftracc_library_path []
const char * liftracc_selector_funcnames []
Array of function name strings.
const char * liftracc_selector_funcnames []
Array of function name strings.
Typedef Documentation
typedef unsigned char decision_data_t
in auto mode ticks are used to find the fastest function
if in prio mode prios go from 1-255
Definition at line 28 of file liftracc_selector.h.
Enumeration Type Documentation
enum liftracc_selector_error_t
Enumeration of error states.
This enum covers all possible error states the selector can get in.
Enumerator:
NO_ERROR
NO_LIBS_FOUND_ERROR
LIBS_OPEN_ERROR
LIBS_CLOSE_ERROR
FUNCTION_NOT_FOUND_ERROR
FILE_NOT_FOUND_ERROR
DATA_READ_ERROR
DATA_WRITE_ERROR
Definition at line 40 of file liftracc_selector.h.
enum liftracc_selector_funcid_t
Enumeration of selector function ids.
There is an id to every blas function supported. One of these ids is passed to the selector in order to decide which function should be selected. (candidate for autogen!)
Enumerator:
SELECT_SDSDOT
SELECT_DSDOT
SELECT_SDOT
SELECT_DDOT
SELECT_CDOTU_SUB
SELECT_CDOTC_SUB
SELECT_ZDOTU_SUB
SELECT_ZDOTC_SUB
SELECT_SNRM2
SELECT_SASUM
SELECT_DNRM2
SELECT_DASUM
SELECT_SCNRM2
SELECT_SCASUM
SELECT_DZNRM2
SELECT_DZASUM
SELECT_ISAMAX
SELECT_IDAMAX
SELECT_ICAMAX
SELECT_IZAMAX
SELECT_SSWAP
SELECT_SCOPY
SELECT_SAXPY
SELECT_DSWAP
SELECT_DCOPY
SELECT_DAXPY
SELECT_CSWAP
SELECT_CCOPY
SELECT_CAXPY
SELECT_ZSWAP
SELECT_ZCOPY
SELECT_ZAXPY
SELECT_SROTG
SELECT_SROTMG
SELECT_SROT
SELECT_SROTM
SELECT_DROTG
SELECT_DROTMG
SELECT_DROT
SELECT_DROTM
SELECT_SSCAL
SELECT_DSCAL
SELECT_CSCAL
SELECT_ZSCAL
SELECT_CSSCAL
SELECT_ZDSCAL
SELECT_SGEMV
SELECT_SGBMV
SELECT_STRMV
SELECT_STBMV
SELECT_STPMV
SELECT_STRSV
SELECT_STBSV
SELECT_STPSV
SELECT_DGEMV
SELECT_DGBMV
SELECT_DTRMV
SELECT_DTBMV
SELECT_DTPMV
SELECT_DTRSV
SELECT_DTBSV
SELECT_DTPSV
SELECT_CGEMV
SELECT_CGBMV
SELECT_CTRMV
SELECT_CTBMV
SELECT_CTPMV
SELECT_CTRSV
SELECT_CTBSV
SELECT_CTPSV
SELECT_ZGEMV
SELECT_ZGBMV
SELECT_ZTRMV
SELECT_ZTBMV
SELECT_ZTPMV
SELECT_ZTRSV
SELECT_ZTBSV
SELECT_ZTPSV
SELECT_SSYMV
SELECT_SSBMV
SELECT_SSPMV
SELECT_SGER
SELECT_SSYR
SELECT_SSPR
SELECT_SSYR2
SELECT_SSPR2
SELECT_DSYMV
SELECT_DSBMV
SELECT_DSPMV
SELECT_DGER
SELECT_DSYR
SELECT_DSPR
SELECT_DSYR2
SELECT_DSPR2
SELECT_CHEMV
SELECT_CHBMV
SELECT_CHPMV
SELECT_CGERU
SELECT_CGERC
SELECT_CHER
SELECT_CHPR
SELECT_CHER2
SELECT_CHPR2
SELECT_ZHEMV
SELECT_ZHBMV
SELECT_ZHPMV
SELECT_ZGERU
SELECT_ZGERC
SELECT_ZHER
SELECT_ZHPR
SELECT_ZHER2
SELECT_ZHPR2
SELECT_SGEMM
SELECT_SSYMM
SELECT_SSYRK
SELECT_SSYR2K
SELECT_STRMM
SELECT_STRSM
SELECT_DGEMM
SELECT_DSYMM
SELECT_DSYRK
SELECT_DSYR2K
SELECT_DTRMM
SELECT_DTRSM
SELECT_CGEMM
SELECT_CSYMM
SELECT_CSYRK
SELECT_CSYR2K
SELECT_CTRMM
SELECT_CTRSM
SELECT_ZGEMM
SELECT_ZSYMM
SELECT_ZSYRK
SELECT_ZSYR2K
SELECT_ZTRMM
SELECT_ZTRSM
SELECT_CHEMM
SELECT_CHERK
SELECT_CHER2K
SELECT_ZHEMM
SELECT_ZHERK
SELECT_ZHER2K
SELECT_XERBLA
CALLTEST_DYNAMIC
FUNCTION_COUNT
Definition at line 59 of file liftracc_selector.h.
Function Documentation
static __inline__ unsigned int get_inx (unsigned int probsize, unsigned int max) [static]
Calculate the index in array.
Inline assembler function to calculate the index in LUT. As numbers to the power of two are used, this can be done with the bsr instruction.
Parameters:
probsize Get the index to this number
max To not jump behind the bounds of the array, the maximum index return is max.
Returns:
The index to use in LUT array
Definition at line 63 of file liftracc_plugin.h.
Referenced by liftracc_selector_init(), and set_decision_data().
liftracc_selector_error_t liftracc_selector_fini ()
Selector component finalize function.
Clean up is done here.
Returns:
Error state or NO_ERROR
Definition at line 94 of file liftracc_selector_old.c.
References error, found_libs, library_handles, LIBS_CLOSE_ERROR, NO_ERROR, and prio_list.
Referenced by liftracc_fini(), and liftracc_selector_init().
liftracc_selector_error_t liftracc_selector_init ()
Selector component init function.
All init stuff is done here. This includes loading the plugins and generating the look up table.
Returns:
Error state or NO_ERROR
Definition at line 85 of file liftracc_selector.c.
References DATA_READ_ERROR, DATA_WRITE_ERROR, plugin_info_t::desc, error, FILE_NOT_FOUND_ERROR, FUNCTION_COUNT, FUNCTION_NOT_FOUND_ERROR, get_inx(), handle, liftracc_selector_problem_info_t::info1, LIBS_CLOSE_ERROR, LIBS_OPEN_ERROR, liftracc_decision_table, liftracc_found_libs, liftracc_fptr_lut, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_library_path, liftracc_plugin_handles, liftracc_preferred_fptr, liftracc_profiling_data, liftracc_selector_fini(), liftracc_selector_funcnames, liftracc_selector_load_plugins(), liftracc_selector_loadinfo(), liftracc_selector_saveinfo(), liftracc_selector_select(), LUT_INIT, plugin_info_t::name, NO_ERROR, NO_LIBS_FOUND_ERROR, plugin_info_t::prio, and plugin_info_t::uuid.
Referenced by liftracc_init(), and liftracc_selector_init().
liftracc_selector_error_t liftracc_selector_load_plugins ()
Referenced by liftracc_selector_init().
liftracc_selector_error_t liftracc_selector_loadinfo (const char * file_name, decision_data_t * array)
Load decision info's from file.
This method loads the array containing infos used by the selector to decide with function is the fastest an should therefor be used as entry in the function pointer LUT.
Parameters:
file_name Name of file to load data from
array Pointer to array to store data into
Returns:
liftracc selector error code
Referenced by __attribute__(), and liftracc_selector_init().
liftracc_selector_error_t liftracc_selector_saveinfo (const char * file_name, decision_data_t * array)
Save decision info's to file.
This method saves the array containing infos used by the selector to decide with function is the fastest an should therefor be used as entry in the function pointer LUT.
Parameters:
file_name Name of file to save data to
array Pointer to array that contains the data
Returns:
liftracc selector error code
Referenced by __attribute__(), and liftracc_selector_init().
void* liftracc_selector_select (const liftracc_selector_funcid_t func_id, const liftracc_selector_problem_info_t * problem_info)
Selects function pointer to use from LUT.
This function selects the function pointer that is stored in the LUT. The returned function pointer depends on the given parameter.
Parameters:
func_id Indentifies the function that should be returned.
problem_info Decision data that is used to select the best function fron the sublibraries.
Returns:
The selected function pointer
Todo:
More and different versions of the selector mechanism should be implemented.
Referenced by __typeof__(), liftracc_calltest_dynamic(), liftracc_daxpy(), liftracc_ddot(), liftracc_dgemm(), liftracc_dscal(), liftracc_dsdot(), liftracc_idamax(), liftracc_sdot(), liftracc_sdsdot(), and liftracc_selector_init().
void* liftracc_selector_select (const char * symbol_name)
Select function pointer to use in LUT.
This function selects a function pointer. It is one of the function pointers available in one of the sublibraries. The selection is based on a per library priority.
Parameters:
symbol_name Symbol name of function that should be selected.
Returns:
The selected function pointer
Definition at line 119 of file liftracc_selector_old.c.
References error, found_libs, library_handles, and prio_list.
Variable Documentation
char* error = 0
Pointer to error message.
Definition at line 41 of file liftracc_selector.c.
decision_data_t liftracc_decision_table[FUNCTION_COUNT][ARRAY_SIZE] = { }
The decision table.
Two dimentional array containing the information in order to find the best function out of the set of plugins. In auto mode the collected data is the time in ticks, the functions have run in average.
Definition at line 54 of file liftracc_selector.c.
Referenced by liftracc_selector_init().
int liftracc_found_libs = 0
Number of found libraries.
Definition at line 42 of file liftracc_selector.c.
Referenced by liftracc_selector_init().
void* liftracc_fptr_lut[FUNCTION_COUNT][ARRAY_SIZE] = { }
The look up table.
The function pointer look up table. In order to get super fast access to the needed functions, this array contains a function pointer to ever blas function supported. The stored pointer is that one to the fastest function. (Found in init phase)
Definition at line 66 of file liftracc_selector.c.
Referenced by liftracc_selector_init().
char liftracc_library_path[]
Path to lib liftracc.
Definition at line 43 of file liftracc_selector.c.
Referenced by liftracc_selector_init().
char liftracc_library_path[PATH_MAX] = { }
Path to lib liftracc.
Definition at line 43 of file liftracc_selector.c.
Referenced by liftracc_selector_init().
void** liftracc_plugin_handles = 0
Pointer to all plugin handlers
Definition at line 44 of file liftracc_selector.c.
Referenced by liftracc_selector_init().
void* liftracc_preferred_fptr[FUNCTION_COUNT] = {}
Preferred function pointers.
Array that contains the pointers to the functions in the plugin that should be used in prefered manner. The Plugin is selectable through the environment variable LIFTRACC_USE_PLUGIN. The string passed to this variable must be the plugins' uuid.
Definition at line 77 of file liftracc_selector.c.
Referenced by liftracc_selector_init().
const char* liftracc_selector_funcnames[]
Array of function name strings.
In order to load each function with dlsym the function name is needed. The index into this array is the function id defined in Enumeration liftracc_selector_funcid_t.
Definition at line 21 of file liftracc_selector_autogen.c.
Referenced by liftracc_selector_init().
const char* liftracc_selector_funcnames[]
Array of function name strings.
In order to load each function with dlsym the function name is needed. The index into this array is the function id defined in Enumeration liftracc_selector_funcid_t.
Definition at line 21 of file liftracc_selector_autogen.c.
Referenced by liftracc_selector_init().