libliftracc: Library initialization/finalization
Library initialization/finalization
Functions
void liftracc_init (void)
The library constructor. This function is called automatically when the library is loaded by the dynamic loader.
void liftracc_fini (void)
The library destructor. This function is called at the time the library is unloaded.
int liftracc_is_initialized (void)
Check initialization state. Return the initialization state of the library.
Variables
int liftracc_initialized = 0
Global init flag. This variable is set to >0 if the library is initialized correctly.
Function Documentation
void liftracc_fini (void)
The library destructor. This function is called at the time the library is unloaded.
Function definition:
 void liftracc_fini(void) __attribute__ ((destructor));
Definition at line 80 of file liftracc.c.
References LIFTRACC_FINI, liftracc_function_names, liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_FUNCTIONS_COUNT, liftracc_selector_fini(), NO_ERROR, and print_profiling_data().
void liftracc_init (void)
The library constructor. This function is called automatically when the library is loaded by the dynamic loader.
Function definition:
 void liftracc_init(void) __attribute__ ((constructor));
Definition at line 43 of file liftracc.c.
References liftracc_function_timing_start(), liftracc_function_timing_stop(), LIFTRACC_INIT, liftracc_initialized, liftracc_selector_init(), and NO_ERROR.
int liftracc_is_initialized (void)
Check initialization state. Return the initialization state of the library.
Returns:
init state
Definition at line 107 of file liftracc.c.
References liftracc_initialized.
Variable Documentation
int liftracc_initialized = 0
Global init flag. This variable is set to >0 if the library is initialized correctly.
Definition at line 31 of file liftracc.c.
Referenced by liftracc_init(), and liftracc_is_initialized().