libliftracc: Profiling
Profiling
Data Structures
struct time_data_t
Time data definition for tickless measurement.
struct profiling_data_t
Profiling data structure.
Typedefs
typedef ticks time_data_t
Time data definition for ticks measurement.
Enumerations
enum prof_id_t {
MEASURING_ERROR, MEASURING_ERROR2, CALL_DYNAMIC, CALL_DYNAMIC2,
CALL_NORMAL, CALL_NORMAL2, LUT_INIT, SELECT_CALL,
PARAM_CONV, ID_COUNT
}
Enumeration to distinguish profiling measure points.
Functions
void liftracc_function_timing_start (profiling_data_t *pd)
Set the start time of a measurement.
void liftracc_function_timing_stop (profiling_data_t *pd)
Calculate duration of measurement.
time_data_t time_data_add (const time_data_t *a, const time_data_t *b)
Add two time_data_t values and return result.
time_data_t time_data_sub (const time_data_t *a, const time_data_t *b)
Subtract two time_data_t values and return result.
time_data_t time_data_mul (const time_data_t *a, const time_data_t *b)
Multiply two time_data_t values and return result.
time_data_t time_data_div (const time_data_t *a, const time_data_t *b)
Divide two time_data_t values and return result.
void time_data_set (time_data_t *a, const time_data_t *b)
Set time_data_t value a to the values stored in b.
void time_data_set_av (time_data_t *a, const time_data_t *b, const unsigned long long count)
Set average time and store it in time_data_t a.
int time_data_islesser (const time_data_t *a, const time_data_t *b)
a<b return true.
int time_data_isgreater (const time_data_t *a, const time_data_t *b)
a>b return true.
void print_profiling_data (const char *title, profiling_data_t *pd, const char *names[], int count)
Print an array of profiling data to stdout.
Variables
const char * prof_id_names []
Useful names for profiling data.
profiling_data_t liftracc_profiling_data [ID_COUNT] = {}
time_data_t tmp_time
const char * liftracc_function_names []
liftracc function names
const char * prof_id_names []
Useful names for profiling data.
profiling_data_t liftracc_profiling_data []
const char * prof_id_names []
Useful names for profiling data.
profiling_data_t liftracc_profiling_data [ID_COUNT] = {}
time_data_t tmp_time
Typedef Documentation
typedef ticks time_data_t
Time data definition for ticks measurement.
Definition at line 38 of file liftracc_profiling.h.
Enumeration Type Documentation
enum prof_id_t
Enumeration to distinguish profiling measure points.
Enumeration is used to log more than one profiling record at the same time.
Enumerator:
MEASURING_ERROR
MEASURING_ERROR2
CALL_DYNAMIC
CALL_DYNAMIC2
CALL_NORMAL
CALL_NORMAL2
LUT_INIT
SELECT_CALL
PARAM_CONV
ID_COUNT
Definition at line 74 of file liftracc_profiling.h.
Function Documentation
void liftracc_function_timing_start (profiling_data_t * pd)
Set the start time of a measurement.
This function saves the point in time at that moment when the function is called. The time value is stored in a datastructure of type profiling_data_t.
Definition at line 49 of file liftracc_profiling.c.
References profiling_data_t::count, getticks(), profiling_data_t::measuring, profiling_data_t::start_time, time_data_t::tks, and time_data_t::ts.
Referenced by __attribute__(), __typeof__(), liftracc_calltest_dynamic(), liftracc_daxpy(), liftracc_ddot(), liftracc_dgemm(), liftracc_dscal(), liftracc_dsdot(), liftracc_fini(), liftracc_idamax(), liftracc_init(), liftracc_plugin_caxpy(), liftracc_plugin_ccopy(), liftracc_plugin_cdotc_sub(), liftracc_plugin_cdotu_sub(), liftracc_plugin_cgbmv(), liftracc_plugin_cgemm(), liftracc_plugin_cgemv(), liftracc_plugin_cgerc(), liftracc_plugin_cgeru(), liftracc_plugin_chbmv(), liftracc_plugin_chemm(), liftracc_plugin_chemv(), liftracc_plugin_cher(), liftracc_plugin_cher2(), liftracc_plugin_cher2k(), liftracc_plugin_cherk(), liftracc_plugin_chpmv(), liftracc_plugin_chpr(), liftracc_plugin_chpr2(), liftracc_plugin_cscal(), liftracc_plugin_csscal(), liftracc_plugin_cswap(), liftracc_plugin_csymm(), liftracc_plugin_csyr2k(), liftracc_plugin_csyrk(), liftracc_plugin_ctbmv(), liftracc_plugin_ctbsv(), liftracc_plugin_ctpmv(), liftracc_plugin_ctpsv(), liftracc_plugin_ctrmm(), liftracc_plugin_ctrmv(), liftracc_plugin_ctrsm(), liftracc_plugin_ctrsv(), liftracc_plugin_dasum(), liftracc_plugin_daxpy(), liftracc_plugin_dcopy(), liftracc_plugin_ddot(), liftracc_plugin_dgbmv(), liftracc_plugin_dgemm(), liftracc_plugin_dgemv(), liftracc_plugin_dger(), liftracc_plugin_dnrm2(), liftracc_plugin_drot(), liftracc_plugin_drotg(), liftracc_plugin_drotm(), liftracc_plugin_drotmg(), liftracc_plugin_dsbmv(), liftracc_plugin_dscal(), liftracc_plugin_dsdot(), liftracc_plugin_dspmv(), liftracc_plugin_dspr(), liftracc_plugin_dspr2(), liftracc_plugin_dswap(), liftracc_plugin_dsymm(), liftracc_plugin_dsymv(), liftracc_plugin_dsyr(), liftracc_plugin_dsyr2(), liftracc_plugin_dsyr2k(), liftracc_plugin_dsyrk(), liftracc_plugin_dtbmv(), liftracc_plugin_dtbsv(), liftracc_plugin_dtpmv(), liftracc_plugin_dtpsv(), liftracc_plugin_dtrmm(), liftracc_plugin_dtrmv(), liftracc_plugin_dtrsm(), liftracc_plugin_dtrsv(), liftracc_plugin_dzasum(), liftracc_plugin_dznrm2(), liftracc_plugin_icamax(), liftracc_plugin_idamax(), liftracc_plugin_isamax(), liftracc_plugin_izamax(), liftracc_plugin_sasum(), liftracc_plugin_saxpy(), liftracc_plugin_scasum(), liftracc_plugin_scnrm2(), liftracc_plugin_scopy(), liftracc_plugin_sdot(), liftracc_plugin_sdsdot(), liftracc_plugin_sgbmv(), liftracc_plugin_sgemm(), liftracc_plugin_sgemv(), liftracc_plugin_sger(), liftracc_plugin_snrm2(), liftracc_plugin_srot(), liftracc_plugin_srotg(), liftracc_plugin_srotm(), liftracc_plugin_srotmg(), liftracc_plugin_ssbmv(), liftracc_plugin_sscal(), liftracc_plugin_sspmv(), liftracc_plugin_sspr(), liftracc_plugin_sspr2(), liftracc_plugin_sswap(), liftracc_plugin_ssymm(), liftracc_plugin_ssymv(), liftracc_plugin_ssyr(), liftracc_plugin_ssyr2(), liftracc_plugin_ssyr2k(), liftracc_plugin_ssyrk(), liftracc_plugin_stbmv(), liftracc_plugin_stbsv(), liftracc_plugin_stpmv(), liftracc_plugin_stpsv(), liftracc_plugin_strmm(), liftracc_plugin_strmv(), liftracc_plugin_strsm(), liftracc_plugin_strsv(), liftracc_plugin_xerbla(), liftracc_plugin_zaxpy(), liftracc_plugin_zcopy(), liftracc_plugin_zdotc_sub(), liftracc_plugin_zdotu_sub(), liftracc_plugin_zdscal(), liftracc_plugin_zgbmv(), liftracc_plugin_zgemm(), liftracc_plugin_zgemv(), liftracc_plugin_zgerc(), liftracc_plugin_zgeru(), liftracc_plugin_zhbmv(), liftracc_plugin_zhemm(), liftracc_plugin_zhemv(), liftracc_plugin_zher(), liftracc_plugin_zher2(), liftracc_plugin_zher2k(), liftracc_plugin_zherk(), liftracc_plugin_zhpmv(), liftracc_plugin_zhpr(), liftracc_plugin_zhpr2(), liftracc_plugin_zscal(), liftracc_plugin_zswap(), liftracc_plugin_zsymm(), liftracc_plugin_zsyr2k(), liftracc_plugin_zsyrk(), liftracc_plugin_ztbmv(), liftracc_plugin_ztbsv(), liftracc_plugin_ztpmv(), liftracc_plugin_ztpsv(), liftracc_plugin_ztrmm(), liftracc_plugin_ztrmv(), liftracc_plugin_ztrsm(), liftracc_plugin_ztrsv(), liftracc_sdot(), liftracc_sdsdot(), and liftracc_selector_init().
void liftracc_function_timing_stop (profiling_data_t * pd)
Calculate duration of measurement.
This function calculates the duration of a measurement. Duration is from a point in time previously set by liftracc_function_timing_start.
Definition at line 61 of file liftracc_profiling.c.
References profiling_data_t::av_time, profiling_data_t::count, getticks(), profiling_data_t::last_time, profiling_data_t::max_time, profiling_data_t::measuring, profiling_data_t::min_time, profiling_data_t::start_time, time_data_isgreater(), time_data_islesser(), time_data_set(), time_data_set_av(), time_data_sub(), time_data_t::tks, and time_data_t::ts.
Referenced by __attribute__(), __typeof__(), liftracc_calltest_dynamic(), liftracc_calltest_normal(), liftracc_daxpy(), liftracc_ddot(), liftracc_dgemm(), liftracc_dscal(), liftracc_dsdot(), liftracc_fini(), liftracc_idamax(), liftracc_init(), liftracc_plugin_calltest_dynamic(), liftracc_plugin_caxpy(), liftracc_plugin_ccopy(), liftracc_plugin_cdotc_sub(), liftracc_plugin_cdotu_sub(), liftracc_plugin_cgbmv(), liftracc_plugin_cgemm(), liftracc_plugin_cgemv(), liftracc_plugin_cgerc(), liftracc_plugin_cgeru(), liftracc_plugin_chbmv(), liftracc_plugin_chemm(), liftracc_plugin_chemv(), liftracc_plugin_cher(), liftracc_plugin_cher2(), liftracc_plugin_cher2k(), liftracc_plugin_cherk(), liftracc_plugin_chpmv(), liftracc_plugin_chpr(), liftracc_plugin_chpr2(), liftracc_plugin_cscal(), liftracc_plugin_csscal(), liftracc_plugin_cswap(), liftracc_plugin_csymm(), liftracc_plugin_csyr2k(), liftracc_plugin_csyrk(), liftracc_plugin_ctbmv(), liftracc_plugin_ctbsv(), liftracc_plugin_ctpmv(), liftracc_plugin_ctpsv(), liftracc_plugin_ctrmm(), liftracc_plugin_ctrmv(), liftracc_plugin_ctrsm(), liftracc_plugin_ctrsv(), liftracc_plugin_dasum(), liftracc_plugin_daxpy(), liftracc_plugin_dcopy(), liftracc_plugin_ddot(), liftracc_plugin_dgbmv(), liftracc_plugin_dgemm(), liftracc_plugin_dgemv(), liftracc_plugin_dger(), liftracc_plugin_dnrm2(), liftracc_plugin_drot(), liftracc_plugin_drotg(), liftracc_plugin_drotm(), liftracc_plugin_drotmg(), liftracc_plugin_dsbmv(), liftracc_plugin_dscal(), liftracc_plugin_dsdot(), liftracc_plugin_dspmv(), liftracc_plugin_dspr(), liftracc_plugin_dspr2(), liftracc_plugin_dswap(), liftracc_plugin_dsymm(), liftracc_plugin_dsymv(), liftracc_plugin_dsyr(), liftracc_plugin_dsyr2(), liftracc_plugin_dsyr2k(), liftracc_plugin_dsyrk(), liftracc_plugin_dtbmv(), liftracc_plugin_dtbsv(), liftracc_plugin_dtpmv(), liftracc_plugin_dtpsv(), liftracc_plugin_dtrmm(), liftracc_plugin_dtrmv(), liftracc_plugin_dtrsm(), liftracc_plugin_dtrsv(), liftracc_plugin_dzasum(), liftracc_plugin_dznrm2(), liftracc_plugin_icamax(), liftracc_plugin_idamax(), liftracc_plugin_isamax(), liftracc_plugin_izamax(), liftracc_plugin_sasum(), liftracc_plugin_saxpy(), liftracc_plugin_scasum(), liftracc_plugin_scnrm2(), liftracc_plugin_scopy(), liftracc_plugin_sdot(), liftracc_plugin_sdsdot(), liftracc_plugin_sgbmv(), liftracc_plugin_sgemm(), liftracc_plugin_sgemv(), liftracc_plugin_sger(), liftracc_plugin_snrm2(), liftracc_plugin_srot(), liftracc_plugin_srotg(), liftracc_plugin_srotm(), liftracc_plugin_srotmg(), liftracc_plugin_ssbmv(), liftracc_plugin_sscal(), liftracc_plugin_sspmv(), liftracc_plugin_sspr(), liftracc_plugin_sspr2(), liftracc_plugin_sswap(), liftracc_plugin_ssymm(), liftracc_plugin_ssymv(), liftracc_plugin_ssyr(), liftracc_plugin_ssyr2(), liftracc_plugin_ssyr2k(), liftracc_plugin_ssyrk(), liftracc_plugin_stbmv(), liftracc_plugin_stbsv(), liftracc_plugin_stpmv(), liftracc_plugin_stpsv(), liftracc_plugin_strmm(), liftracc_plugin_strmv(), liftracc_plugin_strsm(), liftracc_plugin_strsv(), liftracc_plugin_xerbla(), liftracc_plugin_zaxpy(), liftracc_plugin_zcopy(), liftracc_plugin_zdotc_sub(), liftracc_plugin_zdotu_sub(), liftracc_plugin_zdscal(), liftracc_plugin_zgbmv(), liftracc_plugin_zgemm(), liftracc_plugin_zgemv(), liftracc_plugin_zgerc(), liftracc_plugin_zgeru(), liftracc_plugin_zhbmv(), liftracc_plugin_zhemm(), liftracc_plugin_zhemv(), liftracc_plugin_zher(), liftracc_plugin_zher2(), liftracc_plugin_zher2k(), liftracc_plugin_zherk(), liftracc_plugin_zhpmv(), liftracc_plugin_zhpr(), liftracc_plugin_zhpr2(), liftracc_plugin_zscal(), liftracc_plugin_zswap(), liftracc_plugin_zsymm(), liftracc_plugin_zsyr2k(), liftracc_plugin_zsyrk(), liftracc_plugin_ztbmv(), liftracc_plugin_ztbsv(), liftracc_plugin_ztpmv(), liftracc_plugin_ztpsv(), liftracc_plugin_ztrmm(), liftracc_plugin_ztrmv(), liftracc_plugin_ztrsm(), liftracc_plugin_ztrsv(), liftracc_sdot(), liftracc_sdsdot(), and liftracc_selector_init().
void print_profiling_data (const char * title, profiling_data_t * pd, const char * names[], int count)
Print an array of profiling data to stdout.
Print the given profiling data in formated way to stdout.
Parameters:
title Title to display above the printed data.
pd Array that stores the profiling data
names Meaningful names for the profiling data
count number of entries to print
Definition at line 164 of file liftracc_profiling.c.
References profiling_data_t::av_time, profiling_data_t::max_time, profiling_data_t::min_time, time_data_t::tks, and time_data_t::ts.
Referenced by __attribute__(), and liftracc_fini().
time_data_t time_data_add (const time_data_t * a, const time_data_t * b)
Add two time_data_t values and return result.
Definition at line 85 of file liftracc_profiling.c.
References time_data_t::tks, and time_data_t::ts.
time_data_t time_data_div (const time_data_t * a, const time_data_t * b)
Divide two time_data_t values and return result.
Definition at line 122 of file liftracc_profiling.c.
References time_data_t::tks, and time_data_t::ts.
int time_data_isgreater (const time_data_t * a, const time_data_t * b)
a>b return true.
Definition at line 155 of file liftracc_profiling.c.
References time_data_t::ts.
Referenced by liftracc_function_timing_stop().
int time_data_islesser (const time_data_t * a, const time_data_t * b)
a<b return true.
Definition at line 147 of file liftracc_profiling.c.
References time_data_t::ts.
Referenced by liftracc_function_timing_stop().
time_data_t time_data_mul (const time_data_t * a, const time_data_t * b)
Multiply two time_data_t values and return result.
Definition at line 111 of file liftracc_profiling.c.
References time_data_t::tks, and time_data_t::ts.
void time_data_set (time_data_t * a, const time_data_t * b)
Set time_data_t value a to the values stored in b.
Definition at line 133 of file liftracc_profiling.c.
References time_data_t::tks, and time_data_t::ts.
Referenced by liftracc_function_timing_stop().
void time_data_set_av (time_data_t * a, const time_data_t * b, unsigned long long count)
Set average time and store it in time_data_t a.
Definition at line 140 of file liftracc_profiling.c.
References time_data_t::tks, and time_data_t::ts.
Referenced by liftracc_function_timing_stop().
time_data_t time_data_sub (const time_data_t * a, const time_data_t * b)
Subtract two time_data_t values and return result.
Definition at line 96 of file liftracc_profiling.c.
References time_data_t::tks, and time_data_t::ts.
Referenced by liftracc_function_timing_stop().
Variable Documentation
const char* liftracc_function_names[]
liftracc function names
Definition at line 12 of file liftracc_profiling_autogen.c.
Referenced by __attribute__(), and liftracc_fini().
profiling_data_t liftracc_profiling_data[ID_COUNT] = {}
Definition at line 45 of file liftracc_profiling.c.
Referenced by __typeof__(), liftracc_calltest_dynamic(), liftracc_calltest_normal(), liftracc_daxpy(), liftracc_ddot(), liftracc_dgemm(), liftracc_dscal(), liftracc_dsdot(), liftracc_idamax(), liftracc_plugin_calltest_dynamic(), liftracc_plugin_dgemm(), liftracc_sdot(), liftracc_sdsdot(), and liftracc_selector_init().
profiling_data_t liftracc_profiling_data[ID_COUNT] = {}
Definition at line 40 of file liftracc_profiling_tks.c.
profiling_data_t liftracc_profiling_data[]
Definition at line 45 of file liftracc_profiling.c.
Referenced by __typeof__(), liftracc_calltest_dynamic(), liftracc_calltest_normal(), liftracc_daxpy(), liftracc_ddot(), liftracc_dgemm(), liftracc_dscal(), liftracc_dsdot(), liftracc_idamax(), liftracc_plugin_calltest_dynamic(), liftracc_plugin_dgemm(), liftracc_sdot(), liftracc_sdsdot(), and liftracc_selector_init().
const char* prof_id_names[]
Initial value:
 {
    "measuring_error",
    "measuring_error2",
    "call_dynamic",
    "call_dynamic2",
    "call_normal",
    "call_normal2",
    "lut_init",
    "select_call",
    "param_conv",
    "size_entry"
}
Useful names for profiling data.
Provide names for the measure points selectable through prof_id_t.
Definition at line 32 of file liftracc_profiling.c.
const char* prof_id_names[]
Useful names for profiling data.
Provide names for the measure points selectable through prof_id_t.
Definition at line 32 of file liftracc_profiling.c.
const char* prof_id_names[]
Initial value:
 {
    "measuring_error",
    "measuring_error2",
    "call_dynamic",
    "call_dynamic2",
    "call_normal",
    "call_normal2",
    "lut_init",
    "select_call",
    "param_conv",
    "size_entry"
}
Useful names for profiling data.
Provide names for the measure points selectable through prof_id_t.
Definition at line 27 of file liftracc_profiling_tks.c.
time_data_t tmp_time
Definition at line 42 of file liftracc_profiling_tks.c.
time_data_t tmp_time
Definition at line 47 of file liftracc_profiling.c.