libliftracc: src/liftracc_level1.h File Reference
src/liftracc_level1.h File Reference
[generated file]
Functions
float liftracc_sdsdot (const int n, const float alpha, const float *x, const int incx, const float *y, const int incy)
liftracc sdsdot function
float liftracc_sdsdot_ (const int *n, const float *alpha, const float *x, const int *incx, const float *y, const int *incy)
liftracc sdsdot function with pointer interface
double liftracc_dsdot (const int n, const float *x, const int incx, const float *y, const int incy)
liftracc dsdot function
double liftracc_dsdot_ (const int *n, const float *x, const int *incx, const float *y, const int *incy)
liftracc dsdot function with pointer interface
float liftracc_sdot (const int n, const float *x, const int incx, const float *y, const int incy)
liftracc sdot function
float liftracc_sdot_ (const int *n, const float *x, const int *incx, const float *y, const int *incy)
liftracc sdot function with pointer interface
double liftracc_ddot (const int n, const double *x, const int incx, const double *y, const int incy)
liftracc ddot function
double liftracc_ddot_ (const int *n, const double *x, const int *incx, const double *y, const int *incy)
liftracc ddot function with pointer interface
void liftracc_cdotu_sub (const int n, const void *x, const int incx, const void *y, const int incy, void *dotu)
liftracc cdotu_sub function
void liftracc_cdotu_sub_ (const int *n, const void *x, const int *incx, const void *y, const int *incy, void *dotu)
liftracc cdotu_sub function with pointer interface
void liftracc_cdotc_sub (const int n, const void *x, const int incx, const void *y, const int incy, void *dotc)
liftracc cdotc_sub function
void liftracc_cdotc_sub_ (const int *n, const void *x, const int *incx, const void *y, const int *incy, void *dotc)
liftracc cdotc_sub function with pointer interface
void liftracc_zdotu_sub (const int n, const void *x, const int incx, const void *y, const int incy, void *dotu)
liftracc zdotu_sub function
void liftracc_zdotu_sub_ (const int *n, const void *x, const int *incx, const void *y, const int *incy, void *dotu)
liftracc zdotu_sub function with pointer interface
void liftracc_zdotc_sub (const int n, const void *x, const int incx, const void *y, const int incy, void *dotc)
liftracc zdotc_sub function
void liftracc_zdotc_sub_ (const int *n, const void *x, const int *incx, const void *y, const int *incy, void *dotc)
liftracc zdotc_sub function with pointer interface
float liftracc_snrm2 (const int n, const float *x, const int incx)
liftracc snrm2 function
float liftracc_snrm2_ (const int *n, const float *x, const int *incx)
liftracc snrm2 function with pointer interface
float liftracc_sasum (const int n, const float *x, const int incx)
liftracc sasum function
float liftracc_sasum_ (const int *n, const float *x, const int *incx)
liftracc sasum function with pointer interface
double liftracc_dnrm2 (const int n, const double *x, const int incx)
liftracc dnrm2 function
double liftracc_dnrm2_ (const int *n, const double *x, const int *incx)
liftracc dnrm2 function with pointer interface
double liftracc_dasum (const int n, const double *x, const int incx)
liftracc dasum function
double liftracc_dasum_ (const int *n, const double *x, const int *incx)
liftracc dasum function with pointer interface
float liftracc_scnrm2 (const int n, const void *x, const int incx)
liftracc scnrm2 function
float liftracc_scnrm2_ (const int *n, const void *x, const int *incx)
liftracc scnrm2 function with pointer interface
float liftracc_scasum (const int n, const void *x, const int incx)
liftracc scasum function
float liftracc_scasum_ (const int *n, const void *x, const int *incx)
liftracc scasum function with pointer interface
double liftracc_dznrm2 (const int n, const void *x, const int incx)
liftracc dznrm2 function
double liftracc_dznrm2_ (const int *n, const void *x, const int *incx)
liftracc dznrm2 function with pointer interface
double liftracc_dzasum (const int n, const void *x, const int incx)
liftracc dzasum function
double liftracc_dzasum_ (const int *n, const void *x, const int *incx)
liftracc dzasum function with pointer interface
liftracc_index_t liftracc_isamax (const int n, const float *x, const int incx)
liftracc isamax function
liftracc_index_t liftracc_isamax_ (const int *n, const float *x, const int *incx)
liftracc isamax function with pointer interface
liftracc_index_t liftracc_idamax (const int n, const double *x, const int incx)
liftracc idamax function
liftracc_index_t liftracc_idamax_ (const int *n, const double *x, const int *incx)
liftracc idamax function with pointer interface
liftracc_index_t liftracc_icamax (const int n, const void *x, const int incx)
liftracc icamax function
liftracc_index_t liftracc_icamax_ (const int *n, const void *x, const int *incx)
liftracc icamax function with pointer interface
liftracc_index_t liftracc_izamax (const int n, const void *x, const int incx)
liftracc izamax function
liftracc_index_t liftracc_izamax_ (const int *n, const void *x, const int *incx)
liftracc izamax function with pointer interface
void liftracc_sswap (const int n, float *x, const int incx, float *y, const int incy)
liftracc sswap function
void liftracc_sswap_ (const int *n, float *x, const int *incx, float *y, const int *incy)
liftracc sswap function with pointer interface
void liftracc_scopy (const int n, const float *x, const int incx, float *y, const int incy)
liftracc scopy function
void liftracc_scopy_ (const int *n, const float *x, const int *incx, float *y, const int *incy)
liftracc scopy function with pointer interface
void liftracc_saxpy (const int n, const float alpha, const float *x, const int incx, float *y, const int incy)
liftracc saxpy function
void liftracc_saxpy_ (const int *n, const float *alpha, const float *x, const int *incx, float *y, const int *incy)
liftracc saxpy function with pointer interface
void liftracc_dswap (const int n, double *x, const int incx, double *y, const int incy)
liftracc dswap function
void liftracc_dswap_ (const int *n, double *x, const int *incx, double *y, const int *incy)
liftracc dswap function with pointer interface
void liftracc_dcopy (const int n, const double *x, const int incx, double *y, const int incy)
liftracc dcopy function
void liftracc_dcopy_ (const int *n, const double *x, const int *incx, double *y, const int *incy)
liftracc dcopy function with pointer interface
void liftracc_daxpy (const int n, const double alpha, const double *x, const int incx, double *y, const int incy)
liftracc daxpy function
void liftracc_daxpy_ (const int *n, const double *alpha, const double *x, const int *incx, double *y, const int *incy)
liftracc daxpy function with pointer interface
void liftracc_cswap (const int n, void *x, const int incx, void *y, const int incy)
liftracc cswap function
void liftracc_cswap_ (const int *n, void *x, const int *incx, void *y, const int *incy)
liftracc cswap function with pointer interface
void liftracc_ccopy (const int n, const void *x, const int incx, void *y, const int incy)
liftracc ccopy function
void liftracc_ccopy_ (const int *n, const void *x, const int *incx, void *y, const int *incy)
liftracc ccopy function with pointer interface
void liftracc_caxpy (const int n, const void *alpha, const void *x, const int incx, void *y, const int incy)
liftracc caxpy function
void liftracc_caxpy_ (const int *n, const void *alpha, const void *x, const int *incx, void *y, const int *incy)
liftracc caxpy function with pointer interface
void liftracc_zswap (const int n, void *x, const int incx, void *y, const int incy)
liftracc zswap function
void liftracc_zswap_ (const int *n, void *x, const int *incx, void *y, const int *incy)
liftracc zswap function with pointer interface
void liftracc_zcopy (const int n, const void *x, const int incx, void *y, const int incy)
liftracc zcopy function
void liftracc_zcopy_ (const int *n, const void *x, const int *incx, void *y, const int *incy)
liftracc zcopy function with pointer interface
void liftracc_zaxpy (const int n, const void *alpha, const void *x, const int incx, void *y, const int incy)
liftracc zaxpy function
void liftracc_zaxpy_ (const int *n, const void *alpha, const void *x, const int *incx, void *y, const int *incy)
liftracc zaxpy function with pointer interface
void liftracc_srotg (float *a, float *b, float *c, float *s)
liftracc srotg function
void liftracc_srotg_ (float *a, float *b, float *c, float *s)
liftracc srotg function with pointer interface
void liftracc_srotmg (float *d1, float *d2, float *b1, const float b2, float *p)
liftracc srotmg function
void liftracc_srotmg_ (float *d1, float *d2, float *b1, const float *b2, float *p)
liftracc srotmg function with pointer interface
void liftracc_srot (const int n, float *x, const int incx, float *y, const int incy, const float c, const float s)
liftracc srot function
void liftracc_srot_ (const int *n, float *x, const int *incx, float *y, const int *incy, const float *c, const float *s)
liftracc srot function with pointer interface
void liftracc_srotm (const int n, float *x, const int incx, float *y, const int incy, const float *p)
liftracc srotm function
void liftracc_srotm_ (const int *n, float *x, const int *incx, float *y, const int *incy, const float *p)
liftracc srotm function with pointer interface
void liftracc_drotg (double *a, double *b, double *c, double *s)
liftracc drotg function
void liftracc_drotg_ (double *a, double *b, double *c, double *s)
liftracc drotg function with pointer interface
void liftracc_drotmg (double *d1, double *d2, double *b1, const double b2, double *p)
liftracc drotmg function
void liftracc_drotmg_ (double *d1, double *d2, double *b1, const double *b2, double *p)
liftracc drotmg function with pointer interface
void liftracc_drot (const int n, double *x, const int incx, double *y, const int incy, const double c, const double s)
liftracc drot function
void liftracc_drot_ (const int *n, double *x, const int *incx, double *y, const int *incy, const double *c, const double *s)
liftracc drot function with pointer interface
void liftracc_drotm (const int n, double *x, const int incx, double *y, const int incy, const double *p)
liftracc drotm function
void liftracc_drotm_ (const int *n, double *x, const int *incx, double *y, const int *incy, const double *p)
liftracc drotm function with pointer interface
void liftracc_sscal (const int n, const float alpha, float *x, const int incx)
liftracc sscal function
void liftracc_sscal_ (const int *n, const float *alpha, float *x, const int *incx)
liftracc sscal function with pointer interface
void liftracc_dscal (const int n, const double alpha, double *x, const int incx)
liftracc dscal function
void liftracc_dscal_ (const int *n, const double *alpha, double *x, const int *incx)
liftracc dscal function with pointer interface
void liftracc_cscal (const int n, const void *alpha, void *x, const int incx)
liftracc cscal function
void liftracc_cscal_ (const int *n, const void *alpha, void *x, const int *incx)
liftracc cscal function with pointer interface
void liftracc_zscal (const int n, const void *alpha, void *x, const int incx)
liftracc zscal function
void liftracc_zscal_ (const int *n, const void *alpha, void *x, const int *incx)
liftracc zscal function with pointer interface
void liftracc_csscal (const int n, const float alpha, void *x, const int incx)
liftracc csscal function
void liftracc_csscal_ (const int *n, const float *alpha, void *x, const int *incx)
liftracc csscal function with pointer interface
void liftracc_zdscal (const int n, const double alpha, void *x, const int incx)
liftracc zdscal function
void liftracc_zdscal_ (const int *n, const double *alpha, void *x, const int *incx)
liftracc zdscal function with pointer interface
Detailed Description
[generated file]
This file is generated automatically, do not edit manually!
Definition in file liftracc_level1.h.
Function Documentation
void liftracc_caxpy (const int n, const void * alpha, const void * x, const int incx, void * y, const int incy)
liftracc caxpy function
Referenced by liftracc_caxpy_().
void liftracc_caxpy_ (const int * n, const void * alpha, const void * x, const int * incx, void * y, const int * incy)
liftracc caxpy function with pointer interface
Definition at line 1523 of file liftracc_autogen.c.
References liftracc_caxpy().
void liftracc_ccopy (const int n, const void * x, const int incx, void * y, const int incy)
liftracc ccopy function
Referenced by liftracc_ccopy_().
void liftracc_ccopy_ (const int * n, const void * x, const int * incx, void * y, const int * incy)
liftracc ccopy function with pointer interface
Definition at line 1471 of file liftracc_autogen.c.
References liftracc_ccopy().
void liftracc_cdotc_sub (const int n, const void * x, const int incx, const void * y, const int incy, void * dotc)
liftracc cdotc_sub function
Referenced by liftracc_cdotc_sub_().
void liftracc_cdotc_sub_ (const int * n, const void * x, const int * incx, const void * y, const int * incy, void * dotc)
liftracc cdotc_sub function with pointer interface
Definition at line 327 of file liftracc_autogen.c.
References liftracc_cdotc_sub().
void liftracc_cdotu_sub (const int n, const void * x, const int incx, const void * y, const int incy, void * dotu)
liftracc cdotu_sub function
Referenced by liftracc_cdotu_sub_().
void liftracc_cdotu_sub_ (const int * n, const void * x, const int * incx, const void * y, const int * incy, void * dotu)
liftracc cdotu_sub function with pointer interface
Definition at line 275 of file liftracc_autogen.c.
References liftracc_cdotu_sub().
void liftracc_cscal (const int n, const void * alpha, void * x, const int incx)
liftracc cscal function
Referenced by liftracc_cscal_().
void liftracc_cscal_ (const int * n, const void * alpha, void * x, const int * incx)
liftracc cscal function with pointer interface
Definition at line 2251 of file liftracc_autogen.c.
References liftracc_cscal().
void liftracc_csscal (const int n, const float alpha, void * x, const int incx)
liftracc csscal function
Referenced by liftracc_csscal_().
void liftracc_csscal_ (const int * n, const float * alpha, void * x, const int * incx)
liftracc csscal function with pointer interface
Definition at line 2355 of file liftracc_autogen.c.
References liftracc_csscal().
void liftracc_cswap (const int n, void * x, const int incx, void * y, const int incy)
liftracc cswap function
Referenced by liftracc_cswap_().
void liftracc_cswap_ (const int * n, void * x, const int * incx, void * y, const int * incy)
liftracc cswap function with pointer interface
Definition at line 1419 of file liftracc_autogen.c.
References liftracc_cswap().
double liftracc_dasum (const int n, const double * x, const int incx)
liftracc dasum function
Referenced by liftracc_dasum_().
double liftracc_dasum_ (const int * n, const double * x, const int * incx)
liftracc dasum function with pointer interface
Definition at line 639 of file liftracc_autogen.c.
References liftracc_dasum().
void liftracc_daxpy (const int n, const double alpha, const double * x, const int incx, double * y, const int incy)
liftracc daxpy function
Definition at line 237 of file liftracc_testing.c.
References liftracc_selector_problem_info_t::info1, LIFTRACC_FUNCTION_DAXPY, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_profiling_data, liftracc_selector_select(), SELECT_CALL, and SELECT_DAXPY.
Referenced by liftracc_daxpy_().
void liftracc_daxpy_ (const int * n, const double * alpha, const double * x, const int * incx, double * y, const int * incy)
liftracc daxpy function with pointer interface
Definition at line 1367 of file liftracc_autogen.c.
References liftracc_daxpy().
void liftracc_dcopy (const int n, const double * x, const int incx, double * y, const int incy)
liftracc dcopy function
Referenced by liftracc_dcopy_().
void liftracc_dcopy_ (const int * n, const double * x, const int * incx, double * y, const int * incy)
liftracc dcopy function with pointer interface
Definition at line 1315 of file liftracc_autogen.c.
References liftracc_dcopy().
double liftracc_ddot (const int n, const double * x, const int incx, const double * y, const int incy)
liftracc ddot function
Definition at line 278 of file liftracc_testing.c.
References liftracc_selector_problem_info_t::info1, LIFTRACC_FUNCTION_DDOT, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_profiling_data, liftracc_selector_select(), SELECT_CALL, and SELECT_DDOT.
Referenced by liftracc_ddot_().
double liftracc_ddot_ (const int * n, const double * x, const int * incx, const double * y, const int * incy)
liftracc ddot function with pointer interface
Definition at line 223 of file liftracc_autogen.c.
References liftracc_ddot().
double liftracc_dnrm2 (const int n, const double * x, const int incx)
liftracc dnrm2 function
Referenced by liftracc_dnrm2_().
double liftracc_dnrm2_ (const int * n, const double * x, const int * incx)
liftracc dnrm2 function with pointer interface
Definition at line 587 of file liftracc_autogen.c.
References liftracc_dnrm2().
void liftracc_drot (const int n, double * x, const int incx, double * y, const int incy, const double c, const double s)
liftracc drot function
Referenced by liftracc_drot_().
void liftracc_drot_ (const int * n, double * x, const int * incx, double * y, const int * incy, const double * c, const double * s)
liftracc drot function with pointer interface
Definition at line 2043 of file liftracc_autogen.c.
References liftracc_drot().
void liftracc_drotg (double * a, double * b, double * c, double * s)
liftracc drotg function
Referenced by liftracc_drotg_().
void liftracc_drotg_ (double * a, double * b, double * c, double * s)
liftracc drotg function with pointer interface
Definition at line 1939 of file liftracc_autogen.c.
References liftracc_drotg().
void liftracc_drotm (const int n, double * x, const int incx, double * y, const int incy, const double * p)
liftracc drotm function
Referenced by liftracc_drotm_().
void liftracc_drotm_ (const int * n, double * x, const int * incx, double * y, const int * incy, const double * p)
liftracc drotm function with pointer interface
Definition at line 2095 of file liftracc_autogen.c.
References liftracc_drotm().
void liftracc_drotmg (double * d1, double * d2, double * b1, const double b2, double * p)
liftracc drotmg function
Referenced by liftracc_drotmg_().
void liftracc_drotmg_ (double * d1, double * d2, double * b1, const double * b2, double * p)
liftracc drotmg function with pointer interface
Definition at line 1991 of file liftracc_autogen.c.
References liftracc_drotmg().
void liftracc_dscal (const int n, const double alpha, double * x, const int incx)
liftracc dscal function
Definition at line 198 of file liftracc_testing.c.
References liftracc_selector_problem_info_t::info1, LIFTRACC_FUNCTION_DSCAL, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_profiling_data, liftracc_selector_select(), SELECT_CALL, and SELECT_DSCAL.
Referenced by liftracc_dscal_().
void liftracc_dscal_ (const int * n, const double * alpha, double * x, const int * incx)
liftracc dscal function with pointer interface
Definition at line 2199 of file liftracc_autogen.c.
References liftracc_dscal().
double liftracc_dsdot (const int n, const float * x, const int incx, const float * y, const int incy)
liftracc dsdot function
Definition at line 69 of file liftracc_testing.c.
References liftracc_selector_problem_info_t::info1, LIFTRACC_FUNCTION_DSDOT, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_profiling_data, liftracc_selector_select(), SELECT_CALL, and SELECT_DSDOT.
Referenced by liftracc_dsdot_().
double liftracc_dsdot_ (const int * n, const float * x, const int * incx, const float * y, const int * incy)
liftracc dsdot function with pointer interface
Definition at line 119 of file liftracc_autogen.c.
References liftracc_dsdot().
void liftracc_dswap (const int n, double * x, const int incx, double * y, const int incy)
liftracc dswap function
Referenced by liftracc_dswap_().
void liftracc_dswap_ (const int * n, double * x, const int * incx, double * y, const int * incy)
liftracc dswap function with pointer interface
Definition at line 1263 of file liftracc_autogen.c.
References liftracc_dswap().
double liftracc_dzasum (const int n, const void * x, const int incx)
liftracc dzasum function
Referenced by liftracc_dzasum_().
double liftracc_dzasum_ (const int * n, const void * x, const int * incx)
liftracc dzasum function with pointer interface
Definition at line 847 of file liftracc_autogen.c.
References liftracc_dzasum().
double liftracc_dznrm2 (const int n, const void * x, const int incx)
liftracc dznrm2 function
Referenced by liftracc_dznrm2_().
double liftracc_dznrm2_ (const int * n, const void * x, const int * incx)
liftracc dznrm2 function with pointer interface
Definition at line 795 of file liftracc_autogen.c.
References liftracc_dznrm2().
liftracc_index_t liftracc_icamax (const int n, const void * x, const int incx)
liftracc icamax function
Referenced by liftracc_icamax_().
liftracc_index_t liftracc_icamax_ (const int * n, const void * x, const int * incx)
liftracc icamax function with pointer interface
Definition at line 1003 of file liftracc_autogen.c.
References liftracc_icamax().
liftracc_index_t liftracc_idamax (const int n, const double * x, const int incx)
liftracc idamax function
Definition at line 156 of file liftracc_testing.c.
References liftracc_selector_problem_info_t::info1, LIFTRACC_FUNCTION_IDAMAX, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_profiling_data, liftracc_selector_select(), SELECT_CALL, and SELECT_IDAMAX.
Referenced by liftracc_idamax_().
liftracc_index_t liftracc_idamax_ (const int * n, const double * x, const int * incx)
liftracc idamax function with pointer interface
Definition at line 951 of file liftracc_autogen.c.
References liftracc_idamax().
liftracc_index_t liftracc_isamax (const int n, const float * x, const int incx)
liftracc isamax function
Referenced by liftracc_isamax_().
liftracc_index_t liftracc_isamax_ (const int * n, const float * x, const int * incx)
liftracc isamax function with pointer interface
Definition at line 899 of file liftracc_autogen.c.
References liftracc_isamax().
liftracc_index_t liftracc_izamax (const int n, const void * x, const int incx)
liftracc izamax function
Referenced by liftracc_izamax_().
liftracc_index_t liftracc_izamax_ (const int * n, const void * x, const int * incx)
liftracc izamax function with pointer interface
Definition at line 1055 of file liftracc_autogen.c.
References liftracc_izamax().
float liftracc_sasum (const int n, const float * x, const int incx)
liftracc sasum function
Referenced by liftracc_sasum_().
float liftracc_sasum_ (const int * n, const float * x, const int * incx)
liftracc sasum function with pointer interface
Definition at line 535 of file liftracc_autogen.c.
References liftracc_sasum().
void liftracc_saxpy (const int n, const float alpha, const float * x, const int incx, float * y, const int incy)
liftracc saxpy function
Referenced by liftracc_saxpy_().
void liftracc_saxpy_ (const int * n, const float * alpha, const float * x, const int * incx, float * y, const int * incy)
liftracc saxpy function with pointer interface
Definition at line 1211 of file liftracc_autogen.c.
References liftracc_saxpy().
float liftracc_scasum (const int n, const void * x, const int incx)
liftracc scasum function
Referenced by liftracc_scasum_().
float liftracc_scasum_ (const int * n, const void * x, const int * incx)
liftracc scasum function with pointer interface
Definition at line 743 of file liftracc_autogen.c.
References liftracc_scasum().
float liftracc_scnrm2 (const int n, const void * x, const int incx)
liftracc scnrm2 function
Referenced by liftracc_scnrm2_().
float liftracc_scnrm2_ (const int * n, const void * x, const int * incx)
liftracc scnrm2 function with pointer interface
Definition at line 691 of file liftracc_autogen.c.
References liftracc_scnrm2().
void liftracc_scopy (const int n, const float * x, const int incx, float * y, const int incy)
liftracc scopy function
Referenced by liftracc_scopy_().
void liftracc_scopy_ (const int * n, const float * x, const int * incx, float * y, const int * incy)
liftracc scopy function with pointer interface
Definition at line 1159 of file liftracc_autogen.c.
References liftracc_scopy().
float liftracc_sdot (const int n, const float * x, const int incx, const float * y, const int incy)
liftracc sdot function
Definition at line 112 of file liftracc_testing.c.
References liftracc_selector_problem_info_t::info1, LIFTRACC_FUNCTION_SDOT, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_profiling_data, liftracc_selector_select(), SELECT_CALL, and SELECT_SDOT.
Referenced by liftracc_sdot_().
float liftracc_sdot_ (const int * n, const float * x, const int * incx, const float * y, const int * incy)
liftracc sdot function with pointer interface
Definition at line 171 of file liftracc_autogen.c.
References liftracc_sdot().
float liftracc_sdsdot (const int n, const float alpha, const float * x, const int incx, const float * y, const int incy)
liftracc sdsdot function
Definition at line 30 of file liftracc_autogen.c.
References liftracc_selector_problem_info_t::info1, LIFTRACC_FUNCTION_SDSDOT, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_profiling_data, liftracc_selector_select(), SELECT_CALL, and SELECT_SDSDOT.
Referenced by liftracc_sdsdot_().
float liftracc_sdsdot_ (const int * n, const float * alpha, const float * x, const int * incx, const float * y, const int * incy)
liftracc sdsdot function with pointer interface
Definition at line 67 of file liftracc_autogen.c.
References liftracc_sdsdot().
float liftracc_snrm2 (const int n, const float * x, const int incx)
liftracc snrm2 function
Referenced by liftracc_snrm2_().
float liftracc_snrm2_ (const int * n, const float * x, const int * incx)
liftracc snrm2 function with pointer interface
Definition at line 483 of file liftracc_autogen.c.
References liftracc_snrm2().
void liftracc_srot (const int n, float * x, const int incx, float * y, const int incy, const float c, const float s)
liftracc srot function
Referenced by liftracc_srot_().
void liftracc_srot_ (const int * n, float * x, const int * incx, float * y, const int * incy, const float * c, const float * s)
liftracc srot function with pointer interface
Definition at line 1835 of file liftracc_autogen.c.
References liftracc_srot().
void liftracc_srotg (float * a, float * b, float * c, float * s)
liftracc srotg function
Referenced by liftracc_srotg_().
void liftracc_srotg_ (float * a, float * b, float * c, float * s)
liftracc srotg function with pointer interface
Definition at line 1731 of file liftracc_autogen.c.
References liftracc_srotg().
void liftracc_srotm (const int n, float * x, const int incx, float * y, const int incy, const float * p)
liftracc srotm function
Referenced by liftracc_srotm_().
void liftracc_srotm_ (const int * n, float * x, const int * incx, float * y, const int * incy, const float * p)
liftracc srotm function with pointer interface
Definition at line 1887 of file liftracc_autogen.c.
References liftracc_srotm().
void liftracc_srotmg (float * d1, float * d2, float * b1, const float b2, float * p)
liftracc srotmg function
Referenced by liftracc_srotmg_().
void liftracc_srotmg_ (float * d1, float * d2, float * b1, const float * b2, float * p)
liftracc srotmg function with pointer interface
Definition at line 1783 of file liftracc_autogen.c.
References liftracc_srotmg().
void liftracc_sscal (const int n, const float alpha, float * x, const int incx)
liftracc sscal function
Referenced by liftracc_sscal_().
void liftracc_sscal_ (const int * n, const float * alpha, float * x, const int * incx)
liftracc sscal function with pointer interface
Definition at line 2147 of file liftracc_autogen.c.
References liftracc_sscal().
void liftracc_sswap (const int n, float * x, const int incx, float * y, const int incy)
liftracc sswap function
Referenced by liftracc_sswap_().
void liftracc_sswap_ (const int * n, float * x, const int * incx, float * y, const int * incy)
liftracc sswap function with pointer interface
Definition at line 1107 of file liftracc_autogen.c.
References liftracc_sswap().
void liftracc_zaxpy (const int n, const void * alpha, const void * x, const int incx, void * y, const int incy)
liftracc zaxpy function
Referenced by liftracc_zaxpy_().
void liftracc_zaxpy_ (const int * n, const void * alpha, const void * x, const int * incx, void * y, const int * incy)
liftracc zaxpy function with pointer interface
Definition at line 1679 of file liftracc_autogen.c.
References liftracc_zaxpy().
void liftracc_zcopy (const int n, const void * x, const int incx, void * y, const int incy)
liftracc zcopy function
Referenced by liftracc_zcopy_().
void liftracc_zcopy_ (const int * n, const void * x, const int * incx, void * y, const int * incy)
liftracc zcopy function with pointer interface
Definition at line 1627 of file liftracc_autogen.c.
References liftracc_zcopy().
void liftracc_zdotc_sub (const int n, const void * x, const int incx, const void * y, const int incy, void * dotc)
liftracc zdotc_sub function
Referenced by liftracc_zdotc_sub_().
void liftracc_zdotc_sub_ (const int * n, const void * x, const int * incx, const void * y, const int * incy, void * dotc)
liftracc zdotc_sub function with pointer interface
Definition at line 431 of file liftracc_autogen.c.
References liftracc_zdotc_sub().
void liftracc_zdotu_sub (const int n, const void * x, const int incx, const void * y, const int incy, void * dotu)
liftracc zdotu_sub function
Referenced by liftracc_zdotu_sub_().
void liftracc_zdotu_sub_ (const int * n, const void * x, const int * incx, const void * y, const int * incy, void * dotu)
liftracc zdotu_sub function with pointer interface
Definition at line 379 of file liftracc_autogen.c.
References liftracc_zdotu_sub().
void liftracc_zdscal (const int n, const double alpha, void * x, const int incx)
liftracc zdscal function
Referenced by liftracc_zdscal_().
void liftracc_zdscal_ (const int * n, const double * alpha, void * x, const int * incx)
liftracc zdscal function with pointer interface
Definition at line 2407 of file liftracc_autogen.c.
References liftracc_zdscal().
void liftracc_zscal (const int n, const void * alpha, void * x, const int incx)
liftracc zscal function
Referenced by liftracc_zscal_().
void liftracc_zscal_ (const int * n, const void * alpha, void * x, const int * incx)
liftracc zscal function with pointer interface
Definition at line 2303 of file liftracc_autogen.c.
References liftracc_zscal().
void liftracc_zswap (const int n, void * x, const int incx, void * y, const int incy)
liftracc zswap function
Referenced by liftracc_zswap_().
void liftracc_zswap_ (const int * n, void * x, const int * incx, void * y, const int * incy)
liftracc zswap function with pointer interface
Definition at line 1575 of file liftracc_autogen.c.
References liftracc_zswap().