libliftracc: src/liftracc_testing.c File Reference
src/liftracc_testing.c File Reference
C file to test new functionality.
Functions
float liftracc_sdsdot (const int n, const float alpha, const float *x, const int incx, const float *y, const int incy)
liftracc sdsdot function
float liftracc_sdsdot_ (const int *n, const float *alpha, const float *x, const int *incx, const float *y, const int *incy)
liftracc sdsdot function with pointer interface
double liftracc_dsdot (const int n, const float *x, const int incx, const float *y, const int incy)
liftracc dsdot function
double liftracc_dsdot_ (const int *n, const float *x, const int *incx, const float *y, const int *incy)
liftracc dsdot function with pointer interface
float liftracc_sdot (const int n, const float *x, const int incx, const float *y, const int incy)
liftracc sdot function
float liftracc_sdot_ (const int *n, const float *x, const int *incx, const float *y, const int *incy)
liftracc sdot function with pointer interface
liftracc_index_t liftracc_idamax (const int n, const double *x, const int incx)
liftracc idamax function
liftracc_index_t liftracc_idamax_ (const int *n, const double *x, const int *incx)
liftracc idamax function with pointer interface
void liftracc_dscal (const int n, const double alpha, double *x, const int incx)
liftracc dscal function
void liftracc_dscal_ (const int *n, const double *alpha, double *x, const int *incx)
liftracc dscal function with pointer interface
void liftracc_daxpy (const int n, const double alpha, const double *x, const int incx, double *y, const int incy)
liftracc daxpy function
void liftracc_daxpy_ (const int *n, const double *alpha, const double *x, const int *incx, double *y, const int *incy)
liftracc daxpy function with pointer interface
double liftracc_ddot (const int n, const double *x, const int incx, const double *y, const int incy)
liftracc ddot function
double liftracc_ddot_ (const int *n, const double *x, const int *incx, const double *y, const int *incy)
liftracc ddot function with pointer interface
void liftracc_dgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const double alpha, const double *a, const int lda, const double *b, const int ldb, const double beta, double *c, const int ldc)
liftracc dgemm function
void liftracc_dgemm_ (const char *transa, const char *transb, const int *m, const int *n, const int *k, const double *alpha, const double *a, const int *lda, const double *b, const int *ldb, const double *beta, double *c, const int *ldc)
liftracc dgemm function with pointer interface
Variables
profiling_data_t liftracc_function_profiling_data []
liftracc_selector_problem_info_t pinfo = { }
Detailed Description
C file to test new functionality.
Author:
Manuel Niekamp <niekma@upb.de>
Version:
0.1
This file implements the main functionality of the library. It is intended to use this file for testing purpose. If the here implemented code works and is tested it can be easily transfered to the xsl file to auto generate the complete library.
Definition in file liftracc_testing.c.
Function Documentation
void liftracc_daxpy (const int n, const double alpha, const double * x, const int incx, double * y, const int incy)
liftracc daxpy function
Definition at line 237 of file liftracc_testing.c.
References liftracc_selector_problem_info_t::info1, LIFTRACC_FUNCTION_DAXPY, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_profiling_data, liftracc_selector_select(), SELECT_CALL, and SELECT_DAXPY.
Referenced by liftracc_daxpy_().
void liftracc_daxpy_ (const int * n, const double * alpha, const double * x, const int * incx, double * y, const int * incy)
liftracc daxpy function with pointer interface
Definition at line 272 of file liftracc_testing.c.
References liftracc_daxpy().
double liftracc_ddot (const int n, const double * x, const int incx, const double * y, const int incy)
liftracc ddot function
Definition at line 278 of file liftracc_testing.c.
References liftracc_selector_problem_info_t::info1, LIFTRACC_FUNCTION_DDOT, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_profiling_data, liftracc_selector_select(), SELECT_CALL, and SELECT_DDOT.
Referenced by liftracc_ddot_().
double liftracc_ddot_ (const int * n, const double * x, const int * incx, const double * y, const int * incy)
liftracc ddot function with pointer interface
Definition at line 315 of file liftracc_testing.c.
References liftracc_ddot().
void liftracc_dgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const double alpha, const double * a, const int lda, const double * b, const int ldb, const double beta, double * c, const int ldc)
liftracc dgemm function
Definition at line 321 of file liftracc_testing.c.
References liftracc_selector_problem_info_t::info1, LIFTRACC_FUNCTION_DGEMM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_profiling_data, liftracc_selector_select(), SELECT_CALL, and SELECT_DGEMM.
Referenced by liftracc_dgemm_().
void liftracc_dgemm_ (const char * transa, const char * transb, const int * m, const int * n, const int * k, const double * alpha, const double * a, const int * lda, const double * b, const int * ldb, const double * beta, double * c, const int * ldc)
liftracc dgemm function with pointer interface
Definition at line 368 of file liftracc_testing.c.
References liftracc_col_major, liftracc_conj_trans, liftracc_dgemm(), liftracc_no_trans, and liftracc_trans.
void liftracc_dscal (const int n, const double alpha, double * x, const int incx)
liftracc dscal function
Definition at line 198 of file liftracc_testing.c.
References liftracc_selector_problem_info_t::info1, LIFTRACC_FUNCTION_DSCAL, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_profiling_data, liftracc_selector_select(), SELECT_CALL, and SELECT_DSCAL.
Referenced by liftracc_dscal_().
void liftracc_dscal_ (const int * n, const double * alpha, double * x, const int * incx)
liftracc dscal function with pointer interface
Definition at line 232 of file liftracc_testing.c.
References liftracc_dscal().
double liftracc_dsdot (const int n, const float * x, const int incx, const float * y, const int incy)
liftracc dsdot function
Definition at line 69 of file liftracc_testing.c.
References liftracc_selector_problem_info_t::info1, LIFTRACC_FUNCTION_DSDOT, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_profiling_data, liftracc_selector_select(), SELECT_CALL, and SELECT_DSDOT.
Referenced by liftracc_dsdot_().
double liftracc_dsdot_ (const int * n, const float * x, const int * incx, const float * y, const int * incy)
liftracc dsdot function with pointer interface
Definition at line 106 of file liftracc_testing.c.
References liftracc_dsdot().
liftracc_index_t liftracc_idamax (const int n, const double * x, const int incx)
liftracc idamax function
Definition at line 156 of file liftracc_testing.c.
References liftracc_selector_problem_info_t::info1, LIFTRACC_FUNCTION_IDAMAX, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_profiling_data, liftracc_selector_select(), SELECT_CALL, and SELECT_IDAMAX.
Referenced by liftracc_idamax_().
liftracc_index_t liftracc_idamax_ (const int * n, const double * x, const int * incx)
liftracc idamax function with pointer interface
Definition at line 193 of file liftracc_testing.c.
References liftracc_idamax().
float liftracc_sdot (const int n, const float * x, const int incx, const float * y, const int incy)
liftracc sdot function
Definition at line 112 of file liftracc_testing.c.
References liftracc_selector_problem_info_t::info1, LIFTRACC_FUNCTION_SDOT, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_profiling_data, liftracc_selector_select(), SELECT_CALL, and SELECT_SDOT.
Referenced by liftracc_sdot_().
float liftracc_sdot_ (const int * n, const float * x, const int * incx, const float * y, const int * incy)
liftracc sdot function with pointer interface
Definition at line 150 of file liftracc_testing.c.
References liftracc_sdot().
float liftracc_sdsdot (const int n, const float alpha, const float * x, const int incx, const float * y, const int incy)
liftracc sdsdot function
Definition at line 25 of file liftracc_testing.c.
References liftracc_selector_problem_info_t::info1, LIFTRACC_FUNCTION_SDSDOT, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_profiling_data, liftracc_selector_select(), SELECT_CALL, and SELECT_SDSDOT.
float liftracc_sdsdot_ (const int * n, const float * alpha, const float * x, const int * incx, const float * y, const int * incy)
liftracc sdsdot function with pointer interface
Definition at line 63 of file liftracc_testing.c.
References liftracc_sdsdot().
Variable Documentation
profiling_data_t liftracc_function_profiling_data[]
Definition at line 18 of file liftracc.c.
liftracc_selector_problem_info_t pinfo = { }
Definition at line 23 of file liftracc_testing.c.