libliftracc: src/liftracc.c File Reference
src/liftracc.c File Reference
Main C file of the liftracc lib.
Functions
void liftracc_init (void)
The library constructor. This function is called automatically when the library is loaded by the dynamic loader.
void liftracc_fini (void)
The library destructor. This function is called at the time the library is unloaded.
int liftracc_is_initialized (void)
Check initialization state. Return the initialization state of the library.
int liftracc_calltest_dynamic (int a, int b, int c)
dynamic call measure function Only used to measure the time a dynamic call through the library costs. This function is useless in any other manner.
Variables
profiling_data_t liftracc_function_profiling_data [LIFTRACC_FUNCTIONS_COUNT] = {}
int liftracc_initialized = 0
Global init flag. This variable is set to >0 if the library is initialized correctly.
Detailed Description
Main C file of the liftracc lib.
Author:
Manuel Niekamp <niekma@upb.de>
Version:
0.1
This file contains the constructor and destructor function. Some general functions are defined too.
Definition in file liftracc.c.
Function Documentation
int liftracc_calltest_dynamic (int a, int b, int c)
dynamic call measure function Only used to measure the time a dynamic call through the library costs. This function is useless in any other manner.
Definition at line 119 of file liftracc.c.
References CALLTEST_DYNAMIC, liftracc_selector_problem_info_t::info1, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_profiling_data, liftracc_selector_select(), pinfo, and SELECT_CALL.
Variable Documentation
profiling_data_t liftracc_function_profiling_data[LIFTRACC_FUNCTIONS_COUNT] = {}
Definition at line 18 of file liftracc.c.