libliftracc: src/liftracc_level3_testing.h File Reference
src/liftracc_level3_testing.h File Reference
File for testing purpose.
Functions
void liftracc_sgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const float alpha, const float *a, const int lda, const float *b, const int ldb, const float beta, float *c, const int ldc)
liftracc sgemm function
void liftracc_sgemm_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const liftracc_transpose_t *transb, const int *m, const int *n, const int *k, const float *alpha, const float *a, const int *lda, const float *b, const int *ldb, const float *beta, float *c, const int *ldc)
liftracc sgemm function with pointer interface
void liftracc_ssymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const float alpha, const float *a, const int lda, const float *b, const int ldb, const float beta, float *c, const int ldc)
liftracc ssymm function
void liftracc_ssymm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const int *m, const int *n, const float *alpha, const float *a, const int *lda, const float *b, const int *ldb, const float *beta, float *c, const int *ldc)
liftracc ssymm function with pointer interface
void liftracc_ssyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const float alpha, const float *a, const int lda, const float beta, float *c, const int ldc)
liftracc ssyrk function
void liftracc_ssyrk_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const float *alpha, const float *a, const int *lda, const float *beta, float *c, const int *ldc)
liftracc ssyrk function with pointer interface
void liftracc_ssyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const float alpha, const float *a, const int lda, const float *b, const int ldb, const float beta, float *c, const int ldc)
liftracc ssyr2k function
void liftracc_ssyr2k_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const float *alpha, const float *a, const int *lda, const float *b, const int *ldb, const float *beta, float *c, const int *ldc)
liftracc ssyr2k function with pointer interface
void liftracc_strmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const float alpha, const float *a, const int lda, float *b, const int ldb)
liftracc strmm function
void liftracc_strmm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *m, const int *n, const float *alpha, const float *a, const int *lda, float *b, const int *ldb)
liftracc strmm function with pointer interface
void liftracc_strsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const float alpha, const float *a, const int lda, float *b, const int ldb)
liftracc strsm function
void liftracc_strsm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *m, const int *n, const float *alpha, const float *a, const int *lda, float *b, const int *ldb)
liftracc strsm function with pointer interface
void liftracc_dgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const double alpha, const double *a, const int lda, const double *b, const int ldb, const double beta, double *c, const int ldc)
liftracc dgemm function
void liftracc_dgemm_ (const char *transa, const char *transb, const int *m, const int *n, const int *k, const double *alpha, const double *a, const int *lda, const double *b, const int *ldb, const double *beta, double *c, const int *ldc)
liftracc dgemm function with pointer interface
void liftracc_dsymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const double alpha, const double *a, const int lda, const double *b, const int ldb, const double beta, double *c, const int ldc)
liftracc dsymm function
void liftracc_dsymm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const int *m, const int *n, const double *alpha, const double *a, const int *lda, const double *b, const int *ldb, const double *beta, double *c, const int *ldc)
liftracc dsymm function with pointer interface
void liftracc_dsyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const double alpha, const double *a, const int lda, const double beta, double *c, const int ldc)
liftracc dsyrk function
void liftracc_dsyrk_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const double *alpha, const double *a, const int *lda, const double *beta, double *c, const int *ldc)
liftracc dsyrk function with pointer interface
void liftracc_dsyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const double alpha, const double *a, const int lda, const double *b, const int ldb, const double beta, double *c, const int ldc)
liftracc dsyr2k function
void liftracc_dsyr2k_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const double *alpha, const double *a, const int *lda, const double *b, const int *ldb, const double *beta, double *c, const int *ldc)
liftracc dsyr2k function with pointer interface
void liftracc_dtrmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const double alpha, const double *a, const int lda, double *b, const int ldb)
liftracc dtrmm function
void liftracc_dtrmm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *m, const int *n, const double *alpha, const double *a, const int *lda, double *b, const int *ldb)
liftracc dtrmm function with pointer interface
void liftracc_dtrsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const double alpha, const double *a, const int lda, double *b, const int ldb)
liftracc dtrsm function
void liftracc_dtrsm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *m, const int *n, const double *alpha, const double *a, const int *lda, double *b, const int *ldb)
liftracc dtrsm function with pointer interface
void liftracc_cgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
liftracc cgemm function
void liftracc_cgemm_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const liftracc_transpose_t *transb, const int *m, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const void *beta, void *c, const int *ldc)
liftracc cgemm function with pointer interface
void liftracc_csymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
liftracc csymm function
void liftracc_csymm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const int *m, const int *n, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const void *beta, void *c, const int *ldc)
liftracc csymm function with pointer interface
void liftracc_csyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void *alpha, const void *a, const int lda, const void *beta, void *c, const int ldc)
liftracc csyrk function
void liftracc_csyrk_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *beta, void *c, const int *ldc)
liftracc csyrk function with pointer interface
void liftracc_csyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
liftracc csyr2k function
void liftracc_csyr2k_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const void *beta, void *c, const int *ldc)
liftracc csyr2k function with pointer interface
void liftracc_ctrmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void *alpha, const void *a, const int lda, void *b, const int ldb)
liftracc ctrmm function
void liftracc_ctrmm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *m, const int *n, const void *alpha, const void *a, const int *lda, void *b, const int *ldb)
liftracc ctrmm function with pointer interface
void liftracc_ctrsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void *alpha, const void *a, const int lda, void *b, const int ldb)
liftracc ctrsm function
void liftracc_ctrsm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *m, const int *n, const void *alpha, const void *a, const int *lda, void *b, const int *ldb)
liftracc ctrsm function with pointer interface
void liftracc_zgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
liftracc zgemm function
void liftracc_zgemm_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const liftracc_transpose_t *transb, const int *m, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const void *beta, void *c, const int *ldc)
liftracc zgemm function with pointer interface
void liftracc_zsymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
liftracc zsymm function
void liftracc_zsymm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const int *m, const int *n, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const void *beta, void *c, const int *ldc)
liftracc zsymm function with pointer interface
void liftracc_zsyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void *alpha, const void *a, const int lda, const void *beta, void *c, const int ldc)
liftracc zsyrk function
void liftracc_zsyrk_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *beta, void *c, const int *ldc)
liftracc zsyrk function with pointer interface
void liftracc_zsyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
liftracc zsyr2k function
void liftracc_zsyr2k_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const void *beta, void *c, const int *ldc)
liftracc zsyr2k function with pointer interface
void liftracc_ztrmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void *alpha, const void *a, const int lda, void *b, const int ldb)
liftracc ztrmm function
void liftracc_ztrmm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *m, const int *n, const void *alpha, const void *a, const int *lda, void *b, const int *ldb)
liftracc ztrmm function with pointer interface
void liftracc_ztrsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void *alpha, const void *a, const int lda, void *b, const int ldb)
liftracc ztrsm function
void liftracc_ztrsm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *m, const int *n, const void *alpha, const void *a, const int *lda, void *b, const int *ldb)
liftracc ztrsm function with pointer interface
void liftracc_chemm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
liftracc chemm function
void liftracc_chemm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const int *m, const int *n, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const void *beta, void *c, const int *ldc)
liftracc chemm function with pointer interface
void liftracc_cherk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const float alpha, const void *a, const int lda, const float beta, void *c, const int ldc)
liftracc cherk function
void liftracc_cherk_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const float *alpha, const void *a, const int *lda, const float *beta, void *c, const int *ldc)
liftracc cherk function with pointer interface
void liftracc_cher2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const float beta, void *c, const int ldc)
liftracc cher2k function
void liftracc_cher2k_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const float *beta, void *c, const int *ldc)
liftracc cher2k function with pointer interface
void liftracc_zhemm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
liftracc zhemm function
void liftracc_zhemm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const int *m, const int *n, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const void *beta, void *c, const int *ldc)
liftracc zhemm function with pointer interface
void liftracc_zherk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const double alpha, const void *a, const int lda, const double beta, void *c, const int ldc)
liftracc zherk function
void liftracc_zherk_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const double *alpha, const void *a, const int *lda, const double *beta, void *c, const int *ldc)
liftracc zherk function with pointer interface
void liftracc_zher2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const double beta, void *c, const int ldc)
liftracc zher2k function
void liftracc_zher2k_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const double *beta, void *c, const int *ldc)
liftracc zher2k function with pointer interface
void liftracc_xerbla (int p, const char *rout, const char *form,...)
liftracc xerbla function
void liftracc_xerbla_ (int *p, const char *rout, const char *form,...)
liftracc xerbla function with pointer interface
Detailed Description
File for testing purpose.
Edit this file to your needs!
Definition in file liftracc_level3_testing.h.
Function Documentation
void liftracc_cgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
liftracc cgemm function
void liftracc_cgemm_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const liftracc_transpose_t * transb, const int * m, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const void * beta, void * c, const int * ldc)
liftracc cgemm function with pointer interface
Definition at line 6515 of file liftracc_autogen.c.
References liftracc_cgemm().
void liftracc_chemm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
liftracc chemm function
void liftracc_chemm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const int * m, const int * n, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const void * beta, void * c, const int * ldc)
liftracc chemm function with pointer interface
Definition at line 7139 of file liftracc_autogen.c.
References liftracc_chemm().
void liftracc_cher2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const float beta, void * c, const int ldc)
liftracc cher2k function
void liftracc_cher2k_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const float * beta, void * c, const int * ldc)
liftracc cher2k function with pointer interface
Definition at line 7243 of file liftracc_autogen.c.
References liftracc_cher2k().
void liftracc_cherk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const float alpha, const void * a, const int lda, const float beta, void * c, const int ldc)
liftracc cherk function
void liftracc_cherk_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const float * alpha, const void * a, const int * lda, const float * beta, void * c, const int * ldc)
liftracc cherk function with pointer interface
Definition at line 7191 of file liftracc_autogen.c.
References liftracc_cherk().
void liftracc_csymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
liftracc csymm function
void liftracc_csymm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const int * m, const int * n, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const void * beta, void * c, const int * ldc)
liftracc csymm function with pointer interface
Definition at line 6567 of file liftracc_autogen.c.
References liftracc_csymm().
void liftracc_csyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
liftracc csyr2k function
void liftracc_csyr2k_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const void * beta, void * c, const int * ldc)
liftracc csyr2k function with pointer interface
Definition at line 6671 of file liftracc_autogen.c.
References liftracc_csyr2k().
void liftracc_csyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void * alpha, const void * a, const int lda, const void * beta, void * c, const int ldc)
liftracc csyrk function
void liftracc_csyrk_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * beta, void * c, const int * ldc)
liftracc csyrk function with pointer interface
Definition at line 6619 of file liftracc_autogen.c.
References liftracc_csyrk().
void liftracc_ctrmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void * alpha, const void * a, const int lda, void * b, const int ldb)
liftracc ctrmm function
void liftracc_ctrmm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * m, const int * n, const void * alpha, const void * a, const int * lda, void * b, const int * ldb)
liftracc ctrmm function with pointer interface
Definition at line 6723 of file liftracc_autogen.c.
References liftracc_ctrmm().
void liftracc_ctrsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void * alpha, const void * a, const int lda, void * b, const int ldb)
liftracc ctrsm function
void liftracc_ctrsm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * m, const int * n, const void * alpha, const void * a, const int * lda, void * b, const int * ldb)
liftracc ctrsm function with pointer interface
Definition at line 6775 of file liftracc_autogen.c.
References liftracc_ctrsm().
void liftracc_dgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const double alpha, const double * a, const int lda, const double * b, const int ldb, const double beta, double * c, const int ldc)
liftracc dgemm function
Definition at line 321 of file liftracc_testing.c.
References liftracc_selector_problem_info_t::info1, LIFTRACC_FUNCTION_DGEMM, liftracc_function_timing_start(), liftracc_function_timing_stop(), liftracc_profiling_data, liftracc_selector_select(), SELECT_CALL, and SELECT_DGEMM.
void liftracc_dgemm_ (const char * transa, const char * transb, const int * m, const int * n, const int * k, const double * alpha, const double * a, const int * lda, const double * b, const int * ldb, const double * beta, double * c, const int * ldc)
liftracc dgemm function with pointer interface
Definition at line 368 of file liftracc_testing.c.
References liftracc_col_major, liftracc_conj_trans, liftracc_dgemm(), liftracc_no_trans, and liftracc_trans.
void liftracc_dsymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const double alpha, const double * a, const int lda, const double * b, const int ldb, const double beta, double * c, const int ldc)
liftracc dsymm function
void liftracc_dsymm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const int * m, const int * n, const double * alpha, const double * a, const int * lda, const double * b, const int * ldb, const double * beta, double * c, const int * ldc)
liftracc dsymm function with pointer interface
Definition at line 6255 of file liftracc_autogen.c.
References liftracc_dsymm().
void liftracc_dsyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const double alpha, const double * a, const int lda, const double * b, const int ldb, const double beta, double * c, const int ldc)
liftracc dsyr2k function
void liftracc_dsyr2k_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const double * alpha, const double * a, const int * lda, const double * b, const int * ldb, const double * beta, double * c, const int * ldc)
liftracc dsyr2k function with pointer interface
Definition at line 6359 of file liftracc_autogen.c.
References liftracc_dsyr2k().
void liftracc_dsyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const double alpha, const double * a, const int lda, const double beta, double * c, const int ldc)
liftracc dsyrk function
void liftracc_dsyrk_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const double * alpha, const double * a, const int * lda, const double * beta, double * c, const int * ldc)
liftracc dsyrk function with pointer interface
Definition at line 6307 of file liftracc_autogen.c.
References liftracc_dsyrk().
void liftracc_dtrmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const double alpha, const double * a, const int lda, double * b, const int ldb)
liftracc dtrmm function
void liftracc_dtrmm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * m, const int * n, const double * alpha, const double * a, const int * lda, double * b, const int * ldb)
liftracc dtrmm function with pointer interface
Definition at line 6411 of file liftracc_autogen.c.
References liftracc_dtrmm().
void liftracc_dtrsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const double alpha, const double * a, const int lda, double * b, const int ldb)
liftracc dtrsm function
void liftracc_dtrsm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * m, const int * n, const double * alpha, const double * a, const int * lda, double * b, const int * ldb)
liftracc dtrsm function with pointer interface
Definition at line 6463 of file liftracc_autogen.c.
References liftracc_dtrsm().
void liftracc_sgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const float alpha, const float * a, const int lda, const float * b, const int ldb, const float beta, float * c, const int ldc)
liftracc sgemm function
void liftracc_sgemm_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const liftracc_transpose_t * transb, const int * m, const int * n, const int * k, const float * alpha, const float * a, const int * lda, const float * b, const int * ldb, const float * beta, float * c, const int * ldc)
liftracc sgemm function with pointer interface
Definition at line 5891 of file liftracc_autogen.c.
References liftracc_sgemm().
void liftracc_ssymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const float alpha, const float * a, const int lda, const float * b, const int ldb, const float beta, float * c, const int ldc)
liftracc ssymm function
void liftracc_ssymm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const int * m, const int * n, const float * alpha, const float * a, const int * lda, const float * b, const int * ldb, const float * beta, float * c, const int * ldc)
liftracc ssymm function with pointer interface
Definition at line 5943 of file liftracc_autogen.c.
References liftracc_ssymm().
void liftracc_ssyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const float alpha, const float * a, const int lda, const float * b, const int ldb, const float beta, float * c, const int ldc)
liftracc ssyr2k function
void liftracc_ssyr2k_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const float * alpha, const float * a, const int * lda, const float * b, const int * ldb, const float * beta, float * c, const int * ldc)
liftracc ssyr2k function with pointer interface
Definition at line 6047 of file liftracc_autogen.c.
References liftracc_ssyr2k().
void liftracc_ssyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const float alpha, const float * a, const int lda, const float beta, float * c, const int ldc)
liftracc ssyrk function
void liftracc_ssyrk_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const float * alpha, const float * a, const int * lda, const float * beta, float * c, const int * ldc)
liftracc ssyrk function with pointer interface
Definition at line 5995 of file liftracc_autogen.c.
References liftracc_ssyrk().
void liftracc_strmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const float alpha, const float * a, const int lda, float * b, const int ldb)
liftracc strmm function
void liftracc_strmm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * m, const int * n, const float * alpha, const float * a, const int * lda, float * b, const int * ldb)
liftracc strmm function with pointer interface
Definition at line 6099 of file liftracc_autogen.c.
References liftracc_strmm().
void liftracc_strsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const float alpha, const float * a, const int lda, float * b, const int ldb)
liftracc strsm function
void liftracc_strsm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * m, const int * n, const float * alpha, const float * a, const int * lda, float * b, const int * ldb)
liftracc strsm function with pointer interface
Definition at line 6151 of file liftracc_autogen.c.
References liftracc_strsm().
void liftracc_xerbla (int p, const char * rout, const char * form, ...)
liftracc xerbla function
void liftracc_xerbla_ (int * p, const char * rout, const char * form, ...)
liftracc xerbla function with pointer interface
Definition at line 7459 of file liftracc_autogen.c.
References liftracc_xerbla().
void liftracc_zgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
liftracc zgemm function
void liftracc_zgemm_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const liftracc_transpose_t * transb, const int * m, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const void * beta, void * c, const int * ldc)
liftracc zgemm function with pointer interface
Definition at line 6827 of file liftracc_autogen.c.
References liftracc_zgemm().
void liftracc_zhemm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
liftracc zhemm function
void liftracc_zhemm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const int * m, const int * n, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const void * beta, void * c, const int * ldc)
liftracc zhemm function with pointer interface
Definition at line 7295 of file liftracc_autogen.c.
References liftracc_zhemm().
void liftracc_zher2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const double beta, void * c, const int ldc)
liftracc zher2k function
void liftracc_zher2k_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const double * beta, void * c, const int * ldc)
liftracc zher2k function with pointer interface
Definition at line 7399 of file liftracc_autogen.c.
References liftracc_zher2k().
void liftracc_zherk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const double alpha, const void * a, const int lda, const double beta, void * c, const int ldc)
liftracc zherk function
void liftracc_zherk_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const double * alpha, const void * a, const int * lda, const double * beta, void * c, const int * ldc)
liftracc zherk function with pointer interface
Definition at line 7347 of file liftracc_autogen.c.
References liftracc_zherk().
void liftracc_zsymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
liftracc zsymm function
void liftracc_zsymm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const int * m, const int * n, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const void * beta, void * c, const int * ldc)
liftracc zsymm function with pointer interface
Definition at line 6879 of file liftracc_autogen.c.
References liftracc_zsymm().
void liftracc_zsyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
liftracc zsyr2k function
void liftracc_zsyr2k_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const void * beta, void * c, const int * ldc)
liftracc zsyr2k function with pointer interface
Definition at line 6983 of file liftracc_autogen.c.
References liftracc_zsyr2k().
void liftracc_zsyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void * alpha, const void * a, const int lda, const void * beta, void * c, const int ldc)
liftracc zsyrk function
void liftracc_zsyrk_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * beta, void * c, const int * ldc)
liftracc zsyrk function with pointer interface
Definition at line 6931 of file liftracc_autogen.c.
References liftracc_zsyrk().
void liftracc_ztrmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void * alpha, const void * a, const int lda, void * b, const int ldb)
liftracc ztrmm function
void liftracc_ztrmm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * m, const int * n, const void * alpha, const void * a, const int * lda, void * b, const int * ldb)
liftracc ztrmm function with pointer interface
Definition at line 7035 of file liftracc_autogen.c.
References liftracc_ztrmm().
void liftracc_ztrsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void * alpha, const void * a, const int lda, void * b, const int ldb)
liftracc ztrsm function
void liftracc_ztrsm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * m, const int * n, const void * alpha, const void * a, const int * lda, void * b, const int * ldb)
liftracc ztrsm function with pointer interface
Definition at line 7087 of file liftracc_autogen.c.
References liftracc_ztrsm().