libliftracc: src/liftracc_selector.c File Reference
src/liftracc_selector.c File Reference
C file of the selector module.
#include "liftracc_selector.h"
#include "liftracc_plugin.h"
#include "liftracc_logging.h"
#include <dlfcn.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <limits.h>
#include <glob.h>
Defines
#define __USE_GNU
Functions
liftracc_selector_error_t liftracc_selector_load_plugins ()
liftracc_selector_error_t liftracc_selector_init ()
Selector component init function. All init stuff is done here. This includes loading the plugins and generating the look up table.
liftracc_selector_error_t liftracc_selector_fini ()
Selector component finalize function. Clean up is done here.
void * liftracc_selector_select (const liftracc_selector_funcid_t func_id, const liftracc_selector_problem_info_t *problem_info)
liftracc_selector_error_t liftracc_selector_loadinfo (const char *file_name, decision_data_t *array)
Variables
char * error = 0
int liftracc_found_libs = 0
char liftracc_library_path [PATH_MAX] = { }
void ** liftracc_plugin_handles = 0
decision_data_t liftracc_decision_table [FUNCTION_COUNT][15] = { }
The decision table. Two dimentional array containing the information in order to find the best function out of the set of plugins. In auto mode the collected data is the time in ticks, the functions have run in average.
void * liftracc_fptr_lut [FUNCTION_COUNT][15] = { }
The look up table. The function pointer look up table. In order to get super fast access to the needed functions, this array contains a function pointer to ever blas function supported. The stored pointer is that one to the fastest function. (Found in init phase).
void * liftracc_preferred_fptr [FUNCTION_COUNT] = {}
Preferred function pointers. Array that contains the pointers to the functions in the plugin that should be used in prefered manner. The Plugin is selectable through the environment variable LIFTRACC_USE_PLUGIN. The string passed to this variable must be the plugins' uuid.
Detailed Description
C file of the selector module.
Author:
Manuel Niekamp <niekma@upb.de>
Version:
0.1
Date:
10/2009-03/2010
This file implements the interface to the selector component. The selector is used inside the wrapper library to select the best function out of a function pool. The functions selected match the calling one from the wrapper library.
Definition in file liftracc_selector.c.
Define Documentation
#define __USE_GNU
Definition at line 23 of file liftracc_selector.c.
Function Documentation
liftracc_selector_error_t liftracc_selector_fini ()
Selector component finalize function. Clean up is done here.
Returns:
Error state or NO_ERROR
Definition at line 136 of file liftracc_selector.c.
Referenced by __attribute__().
liftracc_selector_error_t liftracc_selector_init ()
Selector component init function. All init stuff is done here. This includes loading the plugins and generating the look up table.
Returns:
Error state or NO_ERROR
Definition at line 77 of file liftracc_selector.c.
Referenced by __attribute__(), liftracc_selector_init(), and liftracc_selector_load_plugins().
liftracc_selector_error_t liftracc_selector_load_plugins ()
Definition at line 173 of file liftracc_selector.c.
References plugin_info_t::desc, ERROR, liftracc_library_path, liftracc_plugin_handles, liftracc_preferred_fptr, liftracc_selector_funcnames, liftracc_selector_init(), MSG, plugin_info_t::name, plugin_info_t::prio, and plugin_info_t::uuid.
Referenced by liftracc_selector_init().
liftracc_selector_error_t liftracc_selector_loadinfo (const char * file_name, decision_data_t * array)
Definition at line 356 of file liftracc_selector.c.
Referenced by __attribute__().
void* liftracc_selector_select (const liftracc_selector_funcid_t func_id, const liftracc_selector_problem_info_t * problem_info)
Definition at line 159 of file liftracc_selector.c.
References ARRAY_SIZE, get_inx(), liftracc_selector_problem_info_t::info1, liftracc_fptr_lut, and liftracc_preferred_fptr.
Referenced by liftracc_caxpy(), liftracc_ccopy(), liftracc_cdotc_sub(), liftracc_cdotu_sub(), liftracc_cgbmv(), liftracc_cgemm(), liftracc_cgemv(), liftracc_cgerc(), liftracc_cgeru(), liftracc_chbmv(), liftracc_chemm(), liftracc_chemv(), liftracc_cher(), liftracc_cher2(), liftracc_cher2k(), liftracc_cherk(), liftracc_chpmv(), liftracc_chpr(), liftracc_chpr2(), liftracc_cscal(), liftracc_csscal(), liftracc_cswap(), liftracc_csymm(), liftracc_csyr2k(), liftracc_csyrk(), liftracc_ctbmv(), liftracc_ctbsv(), liftracc_ctpmv(), liftracc_ctpsv(), liftracc_ctrmm(), liftracc_ctrmv(), liftracc_ctrsm(), liftracc_ctrsv(), liftracc_dasum(), liftracc_daxpy(), liftracc_dcopy(), liftracc_ddot(), liftracc_dgbmv(), liftracc_dgemm(), liftracc_dgemv(), liftracc_dger(), liftracc_dnrm2(), liftracc_drot(), liftracc_drotg(), liftracc_drotm(), liftracc_drotmg(), liftracc_dsbmv(), liftracc_dscal(), liftracc_dsdot(), liftracc_dspmv(), liftracc_dspr(), liftracc_dspr2(), liftracc_dswap(), liftracc_dsymm(), liftracc_dsymv(), liftracc_dsyr(), liftracc_dsyr2(), liftracc_dsyr2k(), liftracc_dsyrk(), liftracc_dtbmv(), liftracc_dtbsv(), liftracc_dtpmv(), liftracc_dtpsv(), liftracc_dtrmm(), liftracc_dtrmv(), liftracc_dtrsm(), liftracc_dtrsv(), liftracc_dzasum(), liftracc_dznrm2(), liftracc_icamax(), liftracc_idamax(), liftracc_isamax(), liftracc_izamax(), liftracc_sasum(), liftracc_saxpy(), liftracc_scasum(), liftracc_scnrm2(), liftracc_scopy(), liftracc_sdot(), liftracc_sdsdot(), liftracc_sgbmv(), liftracc_sgemm(), liftracc_sgemv(), liftracc_sger(), liftracc_snrm2(), liftracc_srot(), liftracc_srotg(), liftracc_srotm(), liftracc_srotmg(), liftracc_ssbmv(), liftracc_sscal(), liftracc_sspmv(), liftracc_sspr(), liftracc_sspr2(), liftracc_sswap(), liftracc_ssymm(), liftracc_ssymv(), liftracc_ssyr(), liftracc_ssyr2(), liftracc_ssyr2k(), liftracc_ssyrk(), liftracc_stbmv(), liftracc_stbsv(), liftracc_stpmv(), liftracc_stpsv(), liftracc_strmm(), liftracc_strmv(), liftracc_strsm(), liftracc_strsv(), liftracc_xerbla(), liftracc_zaxpy(), liftracc_zcopy(), liftracc_zdotc_sub(), liftracc_zdotu_sub(), liftracc_zdscal(), liftracc_zgbmv(), liftracc_zgemm(), liftracc_zgemv(), liftracc_zgerc(), liftracc_zgeru(), liftracc_zhbmv(), liftracc_zhemm(), liftracc_zhemv(), liftracc_zher(), liftracc_zher2(), liftracc_zher2k(), liftracc_zherk(), liftracc_zhpmv(), liftracc_zhpr(), liftracc_zhpr2(), liftracc_zscal(), liftracc_zswap(), liftracc_zsymm(), liftracc_zsyr2k(), liftracc_zsyrk(), liftracc_ztbmv(), liftracc_ztbsv(), liftracc_ztpmv(), liftracc_ztpsv(), liftracc_ztrmm(), liftracc_ztrmv(), liftracc_ztrsm(), and liftracc_ztrsv().
Variable Documentation
char* error = 0
Pointer to error message.
Definition at line 36 of file liftracc_selector.c.
decision_data_t liftracc_decision_table[FUNCTION_COUNT][15] = { }
The decision table. Two dimentional array containing the information in order to find the best function out of the set of plugins. In auto mode the collected data is the time in ticks, the functions have run in average.
Definition at line 48 of file liftracc_selector.c.
Referenced by liftracc_selector_init().
int liftracc_found_libs = 0
Number of found libraries.
Definition at line 37 of file liftracc_selector.c.
Referenced by liftracc_selector_init().
void* liftracc_fptr_lut[FUNCTION_COUNT][15] = { }
The look up table. The function pointer look up table. In order to get super fast access to the needed functions, this array contains a function pointer to ever blas function supported. The stored pointer is that one to the fastest function. (Found in init phase).
Definition at line 59 of file liftracc_selector.c.
Referenced by liftracc_selector_init(), and liftracc_selector_select().
char liftracc_library_path[PATH_MAX] = { }
Path to lib liftracc.
Definition at line 38 of file liftracc_selector.c.
Referenced by liftracc_selector_load_plugins().
void** liftracc_plugin_handles = 0
Pointer to all plugin handlers
Definition at line 39 of file liftracc_selector.c.
Referenced by liftracc_selector_fini(), liftracc_selector_init(), and liftracc_selector_load_plugins().
void* liftracc_preferred_fptr[FUNCTION_COUNT] = {}
Preferred function pointers. Array that contains the pointers to the functions in the plugin that should be used in prefered manner. The Plugin is selectable through the environment variable LIFTRACC_USE_PLUGIN. The string passed to this variable must be the plugins' uuid.
Definition at line 69 of file liftracc_selector.c.
Referenced by liftracc_selector_load_plugins(), and liftracc_selector_select().