libliftracc: src/liftracc_level2.h File Reference
src/liftracc_level2.h File Reference
[generated file]
#include "liftracc_common.h"
Functions
void liftracc_sgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const float alpha, const float *a, const int lda, const float *x, const int incx, const float beta, float *y, const int incy)
void liftracc_sgemv_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const int *m, const int *n, const float *alpha, const float *a, const int *lda, const float *x, const int *incx, const float *beta, float *y, const int *incy)
void liftracc_sgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const float alpha, const float *a, const int lda, const float *x, const int incx, const float beta, float *y, const int incy)
void liftracc_sgbmv_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const int *m, const int *n, const int *kl, const int *ku, const float *alpha, const float *a, const int *lda, const float *x, const int *incx, const float *beta, float *y, const int *incy)
void liftracc_strmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float *a, const int lda, float *x, const int incx)
void liftracc_strmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const float *a, const int *lda, float *x, const int *incx)
void liftracc_stbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const float *a, const int lda, float *x, const int incx)
void liftracc_stbmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const int *k, const float *a, const int *lda, float *x, const int *incx)
void liftracc_stpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float *ap, float *x, const int incx)
void liftracc_stpmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const float *ap, float *x, const int *incx)
void liftracc_strsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float *a, const int lda, float *x, const int incx)
void liftracc_strsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const float *a, const int *lda, float *x, const int *incx)
void liftracc_stbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const float *a, const int lda, float *x, const int incx)
void liftracc_stbsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const int *k, const float *a, const int *lda, float *x, const int *incx)
void liftracc_stpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float *ap, float *x, const int incx)
void liftracc_stpsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const float *ap, float *x, const int *incx)
void liftracc_dgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const double alpha, const double *a, const int lda, const double *x, const int incx, const double beta, double *y, const int incy)
void liftracc_dgemv_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const int *m, const int *n, const double *alpha, const double *a, const int *lda, const double *x, const int *incx, const double *beta, double *y, const int *incy)
void liftracc_dgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const double alpha, const double *a, const int lda, const double *x, const int incx, const double beta, double *y, const int incy)
void liftracc_dgbmv_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const int *m, const int *n, const int *kl, const int *ku, const double *alpha, const double *a, const int *lda, const double *x, const int *incx, const double *beta, double *y, const int *incy)
void liftracc_dtrmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double *a, const int lda, double *x, const int incx)
void liftracc_dtrmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const double *a, const int *lda, double *x, const int *incx)
void liftracc_dtbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const double *a, const int lda, double *x, const int incx)
void liftracc_dtbmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const int *k, const double *a, const int *lda, double *x, const int *incx)
void liftracc_dtpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double *ap, double *x, const int incx)
void liftracc_dtpmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const double *ap, double *x, const int *incx)
void liftracc_dtrsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double *a, const int lda, double *x, const int incx)
void liftracc_dtrsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const double *a, const int *lda, double *x, const int *incx)
void liftracc_dtbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const double *a, const int lda, double *x, const int incx)
void liftracc_dtbsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const int *k, const double *a, const int *lda, double *x, const int *incx)
void liftracc_dtpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double *ap, double *x, const int incx)
void liftracc_dtpsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const double *ap, double *x, const int *incx)
void liftracc_cgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_cgemv_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const int *m, const int *n, const void *alpha, const void *a, const int *lda, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_cgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_cgbmv_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const int *m, const int *n, const int *kl, const int *ku, const void *alpha, const void *a, const int *lda, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_ctrmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *a, const int lda, void *x, const int incx)
void liftracc_ctrmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const void *a, const int *lda, void *x, const int *incx)
void liftracc_ctbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void *a, const int lda, void *x, const int incx)
void liftracc_ctbmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const int *k, const void *a, const int *lda, void *x, const int *incx)
void liftracc_ctpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *ap, void *x, const int incx)
void liftracc_ctpmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const void *ap, void *x, const int *incx)
void liftracc_ctrsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *a, const int lda, void *x, const int incx)
void liftracc_ctrsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const void *a, const int *lda, void *x, const int *incx)
void liftracc_ctbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void *a, const int lda, void *x, const int incx)
void liftracc_ctbsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const int *k, const void *a, const int *lda, void *x, const int *incx)
void liftracc_ctpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *ap, void *x, const int incx)
void liftracc_ctpsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const void *ap, void *x, const int *incx)
void liftracc_zgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_zgemv_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const int *m, const int *n, const void *alpha, const void *a, const int *lda, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_zgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_zgbmv_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const int *m, const int *n, const int *kl, const int *ku, const void *alpha, const void *a, const int *lda, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_ztrmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *a, const int lda, void *x, const int incx)
void liftracc_ztrmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const void *a, const int *lda, void *x, const int *incx)
void liftracc_ztbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void *a, const int lda, void *x, const int incx)
void liftracc_ztbmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const int *k, const void *a, const int *lda, void *x, const int *incx)
void liftracc_ztpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *ap, void *x, const int incx)
void liftracc_ztpmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const void *ap, void *x, const int *incx)
void liftracc_ztrsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *a, const int lda, void *x, const int incx)
void liftracc_ztrsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const void *a, const int *lda, void *x, const int *incx)
void liftracc_ztbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void *a, const int lda, void *x, const int incx)
void liftracc_ztbsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const int *k, const void *a, const int *lda, void *x, const int *incx)
void liftracc_ztpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *ap, void *x, const int incx)
void liftracc_ztpsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const void *ap, void *x, const int *incx)
void liftracc_ssymv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float *a, const int lda, const float *x, const int incx, const float beta, float *y, const int incy)
void liftracc_ssymv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const float *alpha, const float *a, const int *lda, const float *x, const int *incx, const float *beta, float *y, const int *incy)
void liftracc_ssbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const float alpha, const float *a, const int lda, const float *x, const int incx, const float beta, float *y, const int incy)
void liftracc_ssbmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const int *k, const float *alpha, const float *a, const int *lda, const float *x, const int *incx, const float *beta, float *y, const int *incy)
void liftracc_sspmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float *ap, const float *x, const int incx, const float beta, float *y, const int incy)
void liftracc_sspmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const float *alpha, const float *ap, const float *x, const int *incx, const float *beta, float *y, const int *incy)
void liftracc_sger (const liftracc_order_t order, const int m, const int n, const float alpha, const float *x, const int incx, const float *y, const int incy, float *a, const int lda)
void liftracc_sger_ (const liftracc_order_t *order, const int *m, const int *n, const float *alpha, const float *x, const int *incx, const float *y, const int *incy, float *a, const int *lda)
void liftracc_ssyr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float *x, const int incx, float *a, const int lda)
void liftracc_ssyr_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const float *alpha, const float *x, const int *incx, float *a, const int *lda)
void liftracc_sspr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float *x, const int incx, float *ap)
void liftracc_sspr_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const float *alpha, const float *x, const int *incx, float *ap)
void liftracc_ssyr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float *x, const int incx, const float *y, const int incy, float *a, const int lda)
void liftracc_ssyr2_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const float *alpha, const float *x, const int *incx, const float *y, const int *incy, float *a, const int *lda)
void liftracc_sspr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float *x, const int incx, const float *y, const int incy, float *a)
void liftracc_sspr2_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const float *alpha, const float *x, const int *incx, const float *y, const int *incy, float *a)
void liftracc_dsymv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double *a, const int lda, const double *x, const int incx, const double beta, double *y, const int incy)
void liftracc_dsymv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const double *alpha, const double *a, const int *lda, const double *x, const int *incx, const double *beta, double *y, const int *incy)
void liftracc_dsbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const double alpha, const double *a, const int lda, const double *x, const int incx, const double beta, double *y, const int incy)
void liftracc_dsbmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const int *k, const double *alpha, const double *a, const int *lda, const double *x, const int *incx, const double *beta, double *y, const int *incy)
void liftracc_dspmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double *ap, const double *x, const int incx, const double beta, double *y, const int incy)
void liftracc_dspmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const double *alpha, const double *ap, const double *x, const int *incx, const double *beta, double *y, const int *incy)
void liftracc_dger (const liftracc_order_t order, const int m, const int n, const double alpha, const double *x, const int incx, const double *y, const int incy, double *a, const int lda)
void liftracc_dger_ (const liftracc_order_t *order, const int *m, const int *n, const double *alpha, const double *x, const int *incx, const double *y, const int *incy, double *a, const int *lda)
void liftracc_dsyr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double *x, const int incx, double *a, const int lda)
void liftracc_dsyr_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const double *alpha, const double *x, const int *incx, double *a, const int *lda)
void liftracc_dspr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double *x, const int incx, double *ap)
void liftracc_dspr_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const double *alpha, const double *x, const int *incx, double *ap)
void liftracc_dsyr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double *x, const int incx, const double *y, const int incy, double *a, const int lda)
void liftracc_dsyr2_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const double *alpha, const double *x, const int *incx, const double *y, const int *incy, double *a, const int *lda)
void liftracc_dspr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double *x, const int incx, const double *y, const int incy, double *a)
void liftracc_dspr2_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const double *alpha, const double *x, const int *incx, const double *y, const int *incy, double *a)
void liftracc_chemv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_chemv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const void *alpha, const void *a, const int *lda, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_chbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_chbmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_chpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *ap, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_chpmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const void *alpha, const void *ap, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_cgeru (const liftracc_order_t order, const int m, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *a, const int lda)
void liftracc_cgeru_ (const liftracc_order_t *order, const int *m, const int *n, const void *alpha, const void *x, const int *incx, const void *y, const int *incy, void *a, const int *lda)
void liftracc_cgerc (const liftracc_order_t order, const int m, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *a, const int lda)
void liftracc_cgerc_ (const liftracc_order_t *order, const int *m, const int *n, const void *alpha, const void *x, const int *incx, const void *y, const int *incy, void *a, const int *lda)
void liftracc_cher (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const void *x, const int incx, void *a, const int lda)
void liftracc_cher_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const float *alpha, const void *x, const int *incx, void *a, const int *lda)
void liftracc_chpr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const void *x, const int incx, void *a)
void liftracc_chpr_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const float *alpha, const void *x, const int *incx, void *a)
void liftracc_cher2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *a, const int lda)
void liftracc_cher2_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const void *alpha, const void *x, const int *incx, const void *y, const int *incy, void *a, const int *lda)
void liftracc_chpr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *ap)
void liftracc_chpr2_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const void *alpha, const void *x, const int *incx, const void *y, const int *incy, void *ap)
void liftracc_zhemv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_zhemv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const void *alpha, const void *a, const int *lda, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_zhbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_zhbmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_zhpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *ap, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_zhpmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const void *alpha, const void *ap, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_zgeru (const liftracc_order_t order, const int m, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *a, const int lda)
void liftracc_zgeru_ (const liftracc_order_t *order, const int *m, const int *n, const void *alpha, const void *x, const int *incx, const void *y, const int *incy, void *a, const int *lda)
void liftracc_zgerc (const liftracc_order_t order, const int m, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *a, const int lda)
void liftracc_zgerc_ (const liftracc_order_t *order, const int *m, const int *n, const void *alpha, const void *x, const int *incx, const void *y, const int *incy, void *a, const int *lda)
void liftracc_zher (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const void *x, const int incx, void *a, const int lda)
void liftracc_zher_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const double *alpha, const void *x, const int *incx, void *a, const int *lda)
void liftracc_zhpr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const void *x, const int incx, void *a)
void liftracc_zhpr_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const double *alpha, const void *x, const int *incx, void *a)
void liftracc_zher2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *a, const int lda)
void liftracc_zher2_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const void *alpha, const void *x, const int *incx, const void *y, const int *incy, void *a, const int *lda)
void liftracc_zhpr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *ap)
void liftracc_zhpr2_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const void *alpha, const void *x, const int *incx, const void *y, const int *incy, void *ap)
Detailed Description
[generated file]
Definition in file liftracc_level2.h.
Function Documentation
void liftracc_cgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 3626 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CGBMV.
Referenced by liftracc_cgbmv_().
void liftracc_cgbmv_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const int * m, const int * n, const int * kl, const int * ku, const void * alpha, const void * a, const int * lda, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 3663 of file liftracc_autogen.c.
References liftracc_cgbmv().
void liftracc_cgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 3569 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CGEMV.
Referenced by liftracc_cgemv_().
void liftracc_cgemv_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const int * m, const int * n, const void * alpha, const void * a, const int * lda, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 3606 of file liftracc_autogen.c.
References liftracc_cgemv().
void liftracc_cgerc (const liftracc_order_t order, const int m, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * a, const int lda)
Definition at line 5621 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CGERC.
Referenced by liftracc_cgerc_().
void liftracc_cgerc_ (const liftracc_order_t * order, const int * m, const int * n, const void * alpha, const void * x, const int * incx, const void * y, const int * incy, void * a, const int * lda)
Definition at line 5658 of file liftracc_autogen.c.
References liftracc_cgerc().
void liftracc_cgeru (const liftracc_order_t order, const int m, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * a, const int lda)
Definition at line 5564 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CGERU.
Referenced by liftracc_cgeru_().
void liftracc_cgeru_ (const liftracc_order_t * order, const int * m, const int * n, const void * alpha, const void * x, const int * incx, const void * y, const int * incy, void * a, const int * lda)
Definition at line 5601 of file liftracc_autogen.c.
References liftracc_cgeru().
void liftracc_chbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 5450 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CHBMV.
Referenced by liftracc_chbmv_().
void liftracc_chbmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 5487 of file liftracc_autogen.c.
References liftracc_chbmv().
void liftracc_chemv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 5393 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CHEMV.
Referenced by liftracc_chemv_().
void liftracc_chemv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const void * alpha, const void * a, const int * lda, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 5430 of file liftracc_autogen.c.
References liftracc_chemv().
void liftracc_cher (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const void * x, const int incx, void * a, const int lda)
Definition at line 5678 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CHER.
Referenced by liftracc_cher_().
void liftracc_cher2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * a, const int lda)
Definition at line 5792 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CHER2.
Referenced by liftracc_cher2_().
void liftracc_cher2_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const void * alpha, const void * x, const int * incx, const void * y, const int * incy, void * a, const int * lda)
Definition at line 5829 of file liftracc_autogen.c.
References liftracc_cher2().
void liftracc_cher_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const float * alpha, const void * x, const int * incx, void * a, const int * lda)
Definition at line 5715 of file liftracc_autogen.c.
References liftracc_cher().
void liftracc_chpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * ap, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 5507 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CHPMV.
Referenced by liftracc_chpmv_().
void liftracc_chpmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const void * alpha, const void * ap, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 5544 of file liftracc_autogen.c.
References liftracc_chpmv().
void liftracc_chpr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const void * x, const int incx, void * a)
Definition at line 5735 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CHPR.
Referenced by liftracc_chpr_().
void liftracc_chpr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * ap)
Definition at line 5849 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CHPR2.
Referenced by liftracc_chpr2_().
void liftracc_chpr2_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const void * alpha, const void * x, const int * incx, const void * y, const int * incy, void * ap)
Definition at line 5886 of file liftracc_autogen.c.
References liftracc_chpr2().
void liftracc_chpr_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const float * alpha, const void * x, const int * incx, void * a)
Definition at line 5772 of file liftracc_autogen.c.
References liftracc_chpr().
void liftracc_ctbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void * a, const int lda, void * x, const int incx)
Definition at line 3740 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CTBMV.
Referenced by liftracc_ctbmv_().
void liftracc_ctbmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const int * k, const void * a, const int * lda, void * x, const int * incx)
Definition at line 3777 of file liftracc_autogen.c.
References liftracc_ctbmv().
void liftracc_ctbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void * a, const int lda, void * x, const int incx)
Definition at line 3911 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CTBSV.
Referenced by liftracc_ctbsv_().
void liftracc_ctbsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const int * k, const void * a, const int * lda, void * x, const int * incx)
Definition at line 3948 of file liftracc_autogen.c.
References liftracc_ctbsv().
void liftracc_ctpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * ap, void * x, const int incx)
Definition at line 3797 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CTPMV.
Referenced by liftracc_ctpmv_().
void liftracc_ctpmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const void * ap, void * x, const int * incx)
Definition at line 3834 of file liftracc_autogen.c.
References liftracc_ctpmv().
void liftracc_ctpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * ap, void * x, const int incx)
Definition at line 3968 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CTPSV.
Referenced by liftracc_ctpsv_().
void liftracc_ctpsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const void * ap, void * x, const int * incx)
Definition at line 4005 of file liftracc_autogen.c.
References liftracc_ctpsv().
void liftracc_ctrmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * a, const int lda, void * x, const int incx)
Definition at line 3683 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CTRMV.
Referenced by liftracc_ctrmv_().
void liftracc_ctrmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const void * a, const int * lda, void * x, const int * incx)
Definition at line 3720 of file liftracc_autogen.c.
References liftracc_ctrmv().
void liftracc_ctrsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * a, const int lda, void * x, const int incx)
Definition at line 3854 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CTRSV.
Referenced by liftracc_ctrsv_().
void liftracc_ctrsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const void * a, const int * lda, void * x, const int * incx)
Definition at line 3891 of file liftracc_autogen.c.
References liftracc_ctrsv().
void liftracc_dgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const double alpha, const double * a, const int lda, const double * x, const int incx, const double beta, double * y, const int incy)
Definition at line 3170 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DGBMV.
Referenced by liftracc_dgbmv_().
void liftracc_dgbmv_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const int * m, const int * n, const int * kl, const int * ku, const double * alpha, const double * a, const int * lda, const double * x, const int * incx, const double * beta, double * y, const int * incy)
Definition at line 3207 of file liftracc_autogen.c.
References liftracc_dgbmv().
void liftracc_dgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const double alpha, const double * a, const int lda, const double * x, const int incx, const double beta, double * y, const int incy)
Definition at line 3113 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DGEMV.
Referenced by liftracc_dgemv_().
void liftracc_dgemv_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const int * m, const int * n, const double * alpha, const double * a, const int * lda, const double * x, const int * incx, const double * beta, double * y, const int * incy)
Definition at line 3150 of file liftracc_autogen.c.
References liftracc_dgemv().
void liftracc_dger (const liftracc_order_t order, const int m, const int n, const double alpha, const double * x, const int incx, const double * y, const int incy, double * a, const int lda)
Definition at line 5108 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DGER.
Referenced by liftracc_dger_().
void liftracc_dger_ (const liftracc_order_t * order, const int * m, const int * n, const double * alpha, const double * x, const int * incx, const double * y, const int * incy, double * a, const int * lda)
Definition at line 5145 of file liftracc_autogen.c.
References liftracc_dger().
void liftracc_dsbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const double alpha, const double * a, const int lda, const double * x, const int incx, const double beta, double * y, const int incy)
Definition at line 4994 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DSBMV.
Referenced by liftracc_dsbmv_().
void liftracc_dsbmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const int * k, const double * alpha, const double * a, const int * lda, const double * x, const int * incx, const double * beta, double * y, const int * incy)
Definition at line 5031 of file liftracc_autogen.c.
References liftracc_dsbmv().
void liftracc_dspmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double * ap, const double * x, const int incx, const double beta, double * y, const int incy)
Definition at line 5051 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DSPMV.
Referenced by liftracc_dspmv_().
void liftracc_dspmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const double * alpha, const double * ap, const double * x, const int * incx, const double * beta, double * y, const int * incy)
Definition at line 5088 of file liftracc_autogen.c.
References liftracc_dspmv().
void liftracc_dspr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double * x, const int incx, double * ap)
Definition at line 5222 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DSPR.
Referenced by liftracc_dspr_().
void liftracc_dspr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double * x, const int incx, const double * y, const int incy, double * a)
Definition at line 5336 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DSPR2.
Referenced by liftracc_dspr2_().
void liftracc_dspr2_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const double * alpha, const double * x, const int * incx, const double * y, const int * incy, double * a)
Definition at line 5373 of file liftracc_autogen.c.
References liftracc_dspr2().
void liftracc_dspr_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const double * alpha, const double * x, const int * incx, double * ap)
Definition at line 5259 of file liftracc_autogen.c.
References liftracc_dspr().
void liftracc_dsymv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double * a, const int lda, const double * x, const int incx, const double beta, double * y, const int incy)
Definition at line 4937 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DSYMV.
Referenced by liftracc_dsymv_().
void liftracc_dsymv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const double * alpha, const double * a, const int * lda, const double * x, const int * incx, const double * beta, double * y, const int * incy)
Definition at line 4974 of file liftracc_autogen.c.
References liftracc_dsymv().
void liftracc_dsyr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double * x, const int incx, double * a, const int lda)
Definition at line 5165 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DSYR.
Referenced by liftracc_dsyr_().
void liftracc_dsyr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double * x, const int incx, const double * y, const int incy, double * a, const int lda)
Definition at line 5279 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DSYR2.
Referenced by liftracc_dsyr2_().
void liftracc_dsyr2_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const double * alpha, const double * x, const int * incx, const double * y, const int * incy, double * a, const int * lda)
Definition at line 5316 of file liftracc_autogen.c.
References liftracc_dsyr2().
void liftracc_dsyr_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const double * alpha, const double * x, const int * incx, double * a, const int * lda)
Definition at line 5202 of file liftracc_autogen.c.
References liftracc_dsyr().
void liftracc_dtbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const double * a, const int lda, double * x, const int incx)
Definition at line 3284 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DTBMV.
Referenced by liftracc_dtbmv_().
void liftracc_dtbmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const int * k, const double * a, const int * lda, double * x, const int * incx)
Definition at line 3321 of file liftracc_autogen.c.
References liftracc_dtbmv().
void liftracc_dtbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const double * a, const int lda, double * x, const int incx)
Definition at line 3455 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DTBSV.
Referenced by liftracc_dtbsv_().
void liftracc_dtbsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const int * k, const double * a, const int * lda, double * x, const int * incx)
Definition at line 3492 of file liftracc_autogen.c.
References liftracc_dtbsv().
void liftracc_dtpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double * ap, double * x, const int incx)
Definition at line 3341 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DTPMV.
Referenced by liftracc_dtpmv_().
void liftracc_dtpmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const double * ap, double * x, const int * incx)
Definition at line 3378 of file liftracc_autogen.c.
References liftracc_dtpmv().
void liftracc_dtpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double * ap, double * x, const int incx)
Definition at line 3512 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DTPSV.
Referenced by liftracc_dtpsv_().
void liftracc_dtpsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const double * ap, double * x, const int * incx)
Definition at line 3549 of file liftracc_autogen.c.
References liftracc_dtpsv().
void liftracc_dtrmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double * a, const int lda, double * x, const int incx)
Definition at line 3227 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DTRMV.
Referenced by liftracc_dtrmv_().
void liftracc_dtrmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const double * a, const int * lda, double * x, const int * incx)
Definition at line 3264 of file liftracc_autogen.c.
References liftracc_dtrmv().
void liftracc_dtrsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double * a, const int lda, double * x, const int incx)
Definition at line 3398 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DTRSV.
Referenced by liftracc_dtrsv_().
void liftracc_dtrsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const double * a, const int * lda, double * x, const int * incx)
Definition at line 3435 of file liftracc_autogen.c.
References liftracc_dtrsv().
void liftracc_sgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const float alpha, const float * a, const int lda, const float * x, const int incx, const float beta, float * y, const int incy)
Definition at line 2714 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SGBMV.
Referenced by liftracc_sgbmv_().
void liftracc_sgbmv_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const int * m, const int * n, const int * kl, const int * ku, const float * alpha, const float * a, const int * lda, const float * x, const int * incx, const float * beta, float * y, const int * incy)
Definition at line 2751 of file liftracc_autogen.c.
References liftracc_sgbmv().
void liftracc_sgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const float alpha, const float * a, const int lda, const float * x, const int incx, const float beta, float * y, const int incy)
Definition at line 2657 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SGEMV.
Referenced by liftracc_sgemv_().
void liftracc_sgemv_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const int * m, const int * n, const float * alpha, const float * a, const int * lda, const float * x, const int * incx, const float * beta, float * y, const int * incy)
Definition at line 2694 of file liftracc_autogen.c.
References liftracc_sgemv().
void liftracc_sger (const liftracc_order_t order, const int m, const int n, const float alpha, const float * x, const int incx, const float * y, const int incy, float * a, const int lda)
Definition at line 4652 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SGER.
Referenced by liftracc_sger_().
void liftracc_sger_ (const liftracc_order_t * order, const int * m, const int * n, const float * alpha, const float * x, const int * incx, const float * y, const int * incy, float * a, const int * lda)
Definition at line 4689 of file liftracc_autogen.c.
References liftracc_sger().
void liftracc_ssbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const float alpha, const float * a, const int lda, const float * x, const int incx, const float beta, float * y, const int incy)
Definition at line 4538 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SSBMV.
Referenced by liftracc_ssbmv_().
void liftracc_ssbmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const int * k, const float * alpha, const float * a, const int * lda, const float * x, const int * incx, const float * beta, float * y, const int * incy)
Definition at line 4575 of file liftracc_autogen.c.
References liftracc_ssbmv().
void liftracc_sspmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float * ap, const float * x, const int incx, const float beta, float * y, const int incy)
Definition at line 4595 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SSPMV.
Referenced by liftracc_sspmv_().
void liftracc_sspmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const float * alpha, const float * ap, const float * x, const int * incx, const float * beta, float * y, const int * incy)
Definition at line 4632 of file liftracc_autogen.c.
References liftracc_sspmv().
void liftracc_sspr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float * x, const int incx, float * ap)
Definition at line 4766 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SSPR.
Referenced by liftracc_sspr_().
void liftracc_sspr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float * x, const int incx, const float * y, const int incy, float * a)
Definition at line 4880 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SSPR2.
Referenced by liftracc_sspr2_().
void liftracc_sspr2_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const float * alpha, const float * x, const int * incx, const float * y, const int * incy, float * a)
Definition at line 4917 of file liftracc_autogen.c.
References liftracc_sspr2().
void liftracc_sspr_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const float * alpha, const float * x, const int * incx, float * ap)
Definition at line 4803 of file liftracc_autogen.c.
References liftracc_sspr().
void liftracc_ssymv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float * a, const int lda, const float * x, const int incx, const float beta, float * y, const int incy)
Definition at line 4481 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SSYMV.
Referenced by liftracc_ssymv_().
void liftracc_ssymv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const float * alpha, const float * a, const int * lda, const float * x, const int * incx, const float * beta, float * y, const int * incy)
Definition at line 4518 of file liftracc_autogen.c.
References liftracc_ssymv().
void liftracc_ssyr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float * x, const int incx, float * a, const int lda)
Definition at line 4709 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SSYR.
Referenced by liftracc_ssyr_().
void liftracc_ssyr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float * x, const int incx, const float * y, const int incy, float * a, const int lda)
Definition at line 4823 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SSYR2.
Referenced by liftracc_ssyr2_().
void liftracc_ssyr2_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const float * alpha, const float * x, const int * incx, const float * y, const int * incy, float * a, const int * lda)
Definition at line 4860 of file liftracc_autogen.c.
References liftracc_ssyr2().
void liftracc_ssyr_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const float * alpha, const float * x, const int * incx, float * a, const int * lda)
Definition at line 4746 of file liftracc_autogen.c.
References liftracc_ssyr().
void liftracc_stbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const float * a, const int lda, float * x, const int incx)
Definition at line 2828 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_STBMV.
Referenced by liftracc_stbmv_().
void liftracc_stbmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const int * k, const float * a, const int * lda, float * x, const int * incx)
Definition at line 2865 of file liftracc_autogen.c.
References liftracc_stbmv().
void liftracc_stbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const float * a, const int lda, float * x, const int incx)
Definition at line 2999 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_STBSV.
Referenced by liftracc_stbsv_().
void liftracc_stbsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const int * k, const float * a, const int * lda, float * x, const int * incx)
Definition at line 3036 of file liftracc_autogen.c.
References liftracc_stbsv().
void liftracc_stpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float * ap, float * x, const int incx)
Definition at line 2885 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_STPMV.
Referenced by liftracc_stpmv_().
void liftracc_stpmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const float * ap, float * x, const int * incx)
Definition at line 2922 of file liftracc_autogen.c.
References liftracc_stpmv().
void liftracc_stpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float * ap, float * x, const int incx)
Definition at line 3056 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_STPSV.
Referenced by liftracc_stpsv_().
void liftracc_stpsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const float * ap, float * x, const int * incx)
Definition at line 3093 of file liftracc_autogen.c.
References liftracc_stpsv().
void liftracc_strmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float * a, const int lda, float * x, const int incx)
Definition at line 2771 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_STRMV.
Referenced by liftracc_strmv_().
void liftracc_strmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const float * a, const int * lda, float * x, const int * incx)
Definition at line 2808 of file liftracc_autogen.c.
References liftracc_strmv().
void liftracc_strsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float * a, const int lda, float * x, const int incx)
Definition at line 2942 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_STRSV.
Referenced by liftracc_strsv_().
void liftracc_strsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const float * a, const int * lda, float * x, const int * incx)
Definition at line 2979 of file liftracc_autogen.c.
References liftracc_strsv().
void liftracc_zgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 4082 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZGBMV.
Referenced by liftracc_zgbmv_().
void liftracc_zgbmv_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const int * m, const int * n, const int * kl, const int * ku, const void * alpha, const void * a, const int * lda, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 4119 of file liftracc_autogen.c.
References liftracc_zgbmv().
void liftracc_zgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 4025 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZGEMV.
Referenced by liftracc_zgemv_().
void liftracc_zgemv_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const int * m, const int * n, const void * alpha, const void * a, const int * lda, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 4062 of file liftracc_autogen.c.
References liftracc_zgemv().
void liftracc_zgerc (const liftracc_order_t order, const int m, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * a, const int lda)
Definition at line 6134 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZGERC.
Referenced by liftracc_zgerc_().
void liftracc_zgerc_ (const liftracc_order_t * order, const int * m, const int * n, const void * alpha, const void * x, const int * incx, const void * y, const int * incy, void * a, const int * lda)
Definition at line 6171 of file liftracc_autogen.c.
References liftracc_zgerc().
void liftracc_zgeru (const liftracc_order_t order, const int m, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * a, const int lda)
Definition at line 6077 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZGERU.
Referenced by liftracc_zgeru_().
void liftracc_zgeru_ (const liftracc_order_t * order, const int * m, const int * n, const void * alpha, const void * x, const int * incx, const void * y, const int * incy, void * a, const int * lda)
Definition at line 6114 of file liftracc_autogen.c.
References liftracc_zgeru().
void liftracc_zhbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 5963 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZHBMV.
Referenced by liftracc_zhbmv_().
void liftracc_zhbmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 6000 of file liftracc_autogen.c.
References liftracc_zhbmv().
void liftracc_zhemv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 5906 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZHEMV.
Referenced by liftracc_zhemv_().
void liftracc_zhemv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const void * alpha, const void * a, const int * lda, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 5943 of file liftracc_autogen.c.
References liftracc_zhemv().
void liftracc_zher (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const void * x, const int incx, void * a, const int lda)
Definition at line 6191 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZHER.
Referenced by liftracc_zher_().
void liftracc_zher2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * a, const int lda)
Definition at line 6305 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZHER2.
Referenced by liftracc_zher2_().
void liftracc_zher2_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const void * alpha, const void * x, const int * incx, const void * y, const int * incy, void * a, const int * lda)
Definition at line 6342 of file liftracc_autogen.c.
References liftracc_zher2().
void liftracc_zher_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const double * alpha, const void * x, const int * incx, void * a, const int * lda)
Definition at line 6228 of file liftracc_autogen.c.
References liftracc_zher().
void liftracc_zhpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * ap, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 6020 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZHPMV.
Referenced by liftracc_zhpmv_().
void liftracc_zhpmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const void * alpha, const void * ap, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 6057 of file liftracc_autogen.c.
References liftracc_zhpmv().
void liftracc_zhpr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const void * x, const int incx, void * a)
Definition at line 6248 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZHPR.
Referenced by liftracc_zhpr_().
void liftracc_zhpr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * ap)
Definition at line 6362 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZHPR2.
Referenced by liftracc_zhpr2_().
void liftracc_zhpr2_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const void * alpha, const void * x, const int * incx, const void * y, const int * incy, void * ap)
Definition at line 6399 of file liftracc_autogen.c.
References liftracc_zhpr2().
void liftracc_zhpr_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const double * alpha, const void * x, const int * incx, void * a)
Definition at line 6285 of file liftracc_autogen.c.
References liftracc_zhpr().
void liftracc_ztbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void * a, const int lda, void * x, const int incx)
Definition at line 4196 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZTBMV.
Referenced by liftracc_ztbmv_().
void liftracc_ztbmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const int * k, const void * a, const int * lda, void * x, const int * incx)
Definition at line 4233 of file liftracc_autogen.c.
References liftracc_ztbmv().
void liftracc_ztbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void * a, const int lda, void * x, const int incx)
Definition at line 4367 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZTBSV.
Referenced by liftracc_ztbsv_().
void liftracc_ztbsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const int * k, const void * a, const int * lda, void * x, const int * incx)
Definition at line 4404 of file liftracc_autogen.c.
References liftracc_ztbsv().
void liftracc_ztpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * ap, void * x, const int incx)
Definition at line 4253 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZTPMV.
Referenced by liftracc_ztpmv_().
void liftracc_ztpmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const void * ap, void * x, const int * incx)
Definition at line 4290 of file liftracc_autogen.c.
References liftracc_ztpmv().
void liftracc_ztpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * ap, void * x, const int incx)
Definition at line 4424 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZTPSV.
Referenced by liftracc_ztpsv_().
void liftracc_ztpsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const void * ap, void * x, const int * incx)
Definition at line 4461 of file liftracc_autogen.c.
References liftracc_ztpsv().
void liftracc_ztrmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * a, const int lda, void * x, const int incx)
Definition at line 4139 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZTRMV.
Referenced by liftracc_ztrmv_().
void liftracc_ztrmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const void * a, const int * lda, void * x, const int * incx)
Definition at line 4176 of file liftracc_autogen.c.
References liftracc_ztrmv().
void liftracc_ztrsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * a, const int lda, void * x, const int incx)
Definition at line 4310 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZTRSV.
Referenced by liftracc_ztrsv_().
void liftracc_ztrsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const void * a, const int * lda, void * x, const int * incx)
Definition at line 4347 of file liftracc_autogen.c.
References liftracc_ztrsv().