libliftracc: src/liftracc_autogen.c File Reference
src/liftracc_autogen.c File Reference
[generated file]
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <limits.h>
#include "liftracc.h"
#include "liftracc_logging.h"
#include "liftracc_selector.h"
Functions
float liftracc_sdsdot (const int n, const float alpha, const float *x, const int incx, const float *y, const int incy)
float liftracc_sdsdot_ (const int *n, const float *alpha, const float *x, const int *incx, const float *y, const int *incy)
double liftracc_dsdot (const int n, const float *x, const int incx, const float *y, const int incy)
double liftracc_dsdot_ (const int *n, const float *x, const int *incx, const float *y, const int *incy)
float liftracc_sdot (const int n, const float *x, const int incx, const float *y, const int incy)
float liftracc_sdot_ (const int *n, const float *x, const int *incx, const float *y, const int *incy)
double liftracc_ddot (const int n, const double *x, const int incx, const double *y, const int incy)
double liftracc_ddot_ (const int *n, const double *x, const int *incx, const double *y, const int *incy)
void liftracc_cdotu_sub (const int n, const void *x, const int incx, const void *y, const int incy, void *dotu)
void liftracc_cdotu_sub_ (const int *n, const void *x, const int *incx, const void *y, const int *incy, void *dotu)
void liftracc_cdotc_sub (const int n, const void *x, const int incx, const void *y, const int incy, void *dotc)
void liftracc_cdotc_sub_ (const int *n, const void *x, const int *incx, const void *y, const int *incy, void *dotc)
void liftracc_zdotu_sub (const int n, const void *x, const int incx, const void *y, const int incy, void *dotu)
void liftracc_zdotu_sub_ (const int *n, const void *x, const int *incx, const void *y, const int *incy, void *dotu)
void liftracc_zdotc_sub (const int n, const void *x, const int incx, const void *y, const int incy, void *dotc)
void liftracc_zdotc_sub_ (const int *n, const void *x, const int *incx, const void *y, const int *incy, void *dotc)
float liftracc_snrm2 (const int n, const float *x, const int incx)
float liftracc_snrm2_ (const int *n, const float *x, const int *incx)
float liftracc_sasum (const int n, const float *x, const int incx)
float liftracc_sasum_ (const int *n, const float *x, const int *incx)
double liftracc_dnrm2 (const int n, const double *x, const int incx)
double liftracc_dnrm2_ (const int *n, const double *x, const int *incx)
double liftracc_dasum (const int n, const double *x, const int incx)
double liftracc_dasum_ (const int *n, const double *x, const int *incx)
float liftracc_scnrm2 (const int n, const void *x, const int incx)
float liftracc_scnrm2_ (const int *n, const void *x, const int *incx)
float liftracc_scasum (const int n, const void *x, const int incx)
float liftracc_scasum_ (const int *n, const void *x, const int *incx)
double liftracc_dznrm2 (const int n, const void *x, const int incx)
double liftracc_dznrm2_ (const int *n, const void *x, const int *incx)
double liftracc_dzasum (const int n, const void *x, const int incx)
double liftracc_dzasum_ (const int *n, const void *x, const int *incx)
liftracc_index_t liftracc_isamax (const int n, const float *x, const int incx)
liftracc_index_t liftracc_isamax_ (const int *n, const float *x, const int *incx)
liftracc_index_t liftracc_idamax (const int n, const double *x, const int incx)
liftracc_index_t liftracc_idamax_ (const int *n, const double *x, const int *incx)
liftracc_index_t liftracc_icamax (const int n, const void *x, const int incx)
liftracc_index_t liftracc_icamax_ (const int *n, const void *x, const int *incx)
liftracc_index_t liftracc_izamax (const int n, const void *x, const int incx)
liftracc_index_t liftracc_izamax_ (const int *n, const void *x, const int *incx)
void liftracc_sswap (const int n, float *x, const int incx, float *y, const int incy)
void liftracc_sswap_ (const int *n, float *x, const int *incx, float *y, const int *incy)
void liftracc_scopy (const int n, const float *x, const int incx, float *y, const int incy)
void liftracc_scopy_ (const int *n, const float *x, const int *incx, float *y, const int *incy)
void liftracc_saxpy (const int n, const float alpha, const float *x, const int incx, float *y, const int incy)
void liftracc_saxpy_ (const int *n, const float *alpha, const float *x, const int *incx, float *y, const int *incy)
void liftracc_dswap (const int n, double *x, const int incx, double *y, const int incy)
void liftracc_dswap_ (const int *n, double *x, const int *incx, double *y, const int *incy)
void liftracc_dcopy (const int n, const double *x, const int incx, double *y, const int incy)
void liftracc_dcopy_ (const int *n, const double *x, const int *incx, double *y, const int *incy)
void liftracc_daxpy (const int n, const double alpha, const double *x, const int incx, double *y, const int incy)
void liftracc_daxpy_ (const int *n, const double *alpha, const double *x, const int *incx, double *y, const int *incy)
void liftracc_cswap (const int n, void *x, const int incx, void *y, const int incy)
void liftracc_cswap_ (const int *n, void *x, const int *incx, void *y, const int *incy)
void liftracc_ccopy (const int n, const void *x, const int incx, void *y, const int incy)
void liftracc_ccopy_ (const int *n, const void *x, const int *incx, void *y, const int *incy)
void liftracc_caxpy (const int n, const void *alpha, const void *x, const int incx, void *y, const int incy)
void liftracc_caxpy_ (const int *n, const void *alpha, const void *x, const int *incx, void *y, const int *incy)
void liftracc_zswap (const int n, void *x, const int incx, void *y, const int incy)
void liftracc_zswap_ (const int *n, void *x, const int *incx, void *y, const int *incy)
void liftracc_zcopy (const int n, const void *x, const int incx, void *y, const int incy)
void liftracc_zcopy_ (const int *n, const void *x, const int *incx, void *y, const int *incy)
void liftracc_zaxpy (const int n, const void *alpha, const void *x, const int incx, void *y, const int incy)
void liftracc_zaxpy_ (const int *n, const void *alpha, const void *x, const int *incx, void *y, const int *incy)
void liftracc_srotg (float *a, float *b, float *c, float *s)
void liftracc_srotg_ (float *a, float *b, float *c, float *s)
void liftracc_srotmg (float *d1, float *d2, float *b1, const float b2, float *p)
void liftracc_srotmg_ (float *d1, float *d2, float *b1, const float *b2, float *p)
void liftracc_srot (const int n, float *x, const int incx, float *y, const int incy, const float c, const float s)
void liftracc_srot_ (const int *n, float *x, const int *incx, float *y, const int *incy, const float *c, const float *s)
void liftracc_srotm (const int n, float *x, const int incx, float *y, const int incy, const float *p)
void liftracc_srotm_ (const int *n, float *x, const int *incx, float *y, const int *incy, const float *p)
void liftracc_drotg (double *a, double *b, double *c, double *s)
void liftracc_drotg_ (double *a, double *b, double *c, double *s)
void liftracc_drotmg (double *d1, double *d2, double *b1, const double b2, double *p)
void liftracc_drotmg_ (double *d1, double *d2, double *b1, const double *b2, double *p)
void liftracc_drot (const int n, double *x, const int incx, double *y, const int incy, const double c, const double s)
void liftracc_drot_ (const int *n, double *x, const int *incx, double *y, const int *incy, const double *c, const double *s)
void liftracc_drotm (const int n, double *x, const int incx, double *y, const int incy, const double *p)
void liftracc_drotm_ (const int *n, double *x, const int *incx, double *y, const int *incy, const double *p)
void liftracc_sscal (const int n, const float alpha, float *x, const int incx)
void liftracc_sscal_ (const int *n, const float *alpha, float *x, const int *incx)
void liftracc_dscal (const int n, const double alpha, double *x, const int incx)
void liftracc_dscal_ (const int *n, const double *alpha, double *x, const int *incx)
void liftracc_cscal (const int n, const void *alpha, void *x, const int incx)
void liftracc_cscal_ (const int *n, const void *alpha, void *x, const int *incx)
void liftracc_zscal (const int n, const void *alpha, void *x, const int incx)
void liftracc_zscal_ (const int *n, const void *alpha, void *x, const int *incx)
void liftracc_csscal (const int n, const float alpha, void *x, const int incx)
void liftracc_csscal_ (const int *n, const float *alpha, void *x, const int *incx)
void liftracc_zdscal (const int n, const double alpha, void *x, const int incx)
void liftracc_zdscal_ (const int *n, const double *alpha, void *x, const int *incx)
void liftracc_sgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const float alpha, const float *a, const int lda, const float *x, const int incx, const float beta, float *y, const int incy)
void liftracc_sgemv_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const int *m, const int *n, const float *alpha, const float *a, const int *lda, const float *x, const int *incx, const float *beta, float *y, const int *incy)
void liftracc_sgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const float alpha, const float *a, const int lda, const float *x, const int incx, const float beta, float *y, const int incy)
void liftracc_sgbmv_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const int *m, const int *n, const int *kl, const int *ku, const float *alpha, const float *a, const int *lda, const float *x, const int *incx, const float *beta, float *y, const int *incy)
void liftracc_strmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float *a, const int lda, float *x, const int incx)
void liftracc_strmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const float *a, const int *lda, float *x, const int *incx)
void liftracc_stbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const float *a, const int lda, float *x, const int incx)
void liftracc_stbmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const int *k, const float *a, const int *lda, float *x, const int *incx)
void liftracc_stpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float *ap, float *x, const int incx)
void liftracc_stpmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const float *ap, float *x, const int *incx)
void liftracc_strsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float *a, const int lda, float *x, const int incx)
void liftracc_strsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const float *a, const int *lda, float *x, const int *incx)
void liftracc_stbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const float *a, const int lda, float *x, const int incx)
void liftracc_stbsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const int *k, const float *a, const int *lda, float *x, const int *incx)
void liftracc_stpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float *ap, float *x, const int incx)
void liftracc_stpsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const float *ap, float *x, const int *incx)
void liftracc_dgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const double alpha, const double *a, const int lda, const double *x, const int incx, const double beta, double *y, const int incy)
void liftracc_dgemv_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const int *m, const int *n, const double *alpha, const double *a, const int *lda, const double *x, const int *incx, const double *beta, double *y, const int *incy)
void liftracc_dgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const double alpha, const double *a, const int lda, const double *x, const int incx, const double beta, double *y, const int incy)
void liftracc_dgbmv_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const int *m, const int *n, const int *kl, const int *ku, const double *alpha, const double *a, const int *lda, const double *x, const int *incx, const double *beta, double *y, const int *incy)
void liftracc_dtrmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double *a, const int lda, double *x, const int incx)
void liftracc_dtrmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const double *a, const int *lda, double *x, const int *incx)
void liftracc_dtbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const double *a, const int lda, double *x, const int incx)
void liftracc_dtbmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const int *k, const double *a, const int *lda, double *x, const int *incx)
void liftracc_dtpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double *ap, double *x, const int incx)
void liftracc_dtpmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const double *ap, double *x, const int *incx)
void liftracc_dtrsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double *a, const int lda, double *x, const int incx)
void liftracc_dtrsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const double *a, const int *lda, double *x, const int *incx)
void liftracc_dtbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const double *a, const int lda, double *x, const int incx)
void liftracc_dtbsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const int *k, const double *a, const int *lda, double *x, const int *incx)
void liftracc_dtpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double *ap, double *x, const int incx)
void liftracc_dtpsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const double *ap, double *x, const int *incx)
void liftracc_cgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_cgemv_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const int *m, const int *n, const void *alpha, const void *a, const int *lda, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_cgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_cgbmv_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const int *m, const int *n, const int *kl, const int *ku, const void *alpha, const void *a, const int *lda, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_ctrmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *a, const int lda, void *x, const int incx)
void liftracc_ctrmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const void *a, const int *lda, void *x, const int *incx)
void liftracc_ctbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void *a, const int lda, void *x, const int incx)
void liftracc_ctbmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const int *k, const void *a, const int *lda, void *x, const int *incx)
void liftracc_ctpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *ap, void *x, const int incx)
void liftracc_ctpmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const void *ap, void *x, const int *incx)
void liftracc_ctrsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *a, const int lda, void *x, const int incx)
void liftracc_ctrsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const void *a, const int *lda, void *x, const int *incx)
void liftracc_ctbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void *a, const int lda, void *x, const int incx)
void liftracc_ctbsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const int *k, const void *a, const int *lda, void *x, const int *incx)
void liftracc_ctpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *ap, void *x, const int incx)
void liftracc_ctpsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const void *ap, void *x, const int *incx)
void liftracc_zgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_zgemv_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const int *m, const int *n, const void *alpha, const void *a, const int *lda, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_zgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_zgbmv_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const int *m, const int *n, const int *kl, const int *ku, const void *alpha, const void *a, const int *lda, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_ztrmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *a, const int lda, void *x, const int incx)
void liftracc_ztrmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const void *a, const int *lda, void *x, const int *incx)
void liftracc_ztbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void *a, const int lda, void *x, const int incx)
void liftracc_ztbmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const int *k, const void *a, const int *lda, void *x, const int *incx)
void liftracc_ztpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *ap, void *x, const int incx)
void liftracc_ztpmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const void *ap, void *x, const int *incx)
void liftracc_ztrsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *a, const int lda, void *x, const int incx)
void liftracc_ztrsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const void *a, const int *lda, void *x, const int *incx)
void liftracc_ztbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void *a, const int lda, void *x, const int incx)
void liftracc_ztbsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const int *k, const void *a, const int *lda, void *x, const int *incx)
void liftracc_ztpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void *ap, void *x, const int incx)
void liftracc_ztpsv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *n, const void *ap, void *x, const int *incx)
void liftracc_ssymv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float *a, const int lda, const float *x, const int incx, const float beta, float *y, const int incy)
void liftracc_ssymv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const float *alpha, const float *a, const int *lda, const float *x, const int *incx, const float *beta, float *y, const int *incy)
void liftracc_ssbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const float alpha, const float *a, const int lda, const float *x, const int incx, const float beta, float *y, const int incy)
void liftracc_ssbmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const int *k, const float *alpha, const float *a, const int *lda, const float *x, const int *incx, const float *beta, float *y, const int *incy)
void liftracc_sspmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float *ap, const float *x, const int incx, const float beta, float *y, const int incy)
void liftracc_sspmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const float *alpha, const float *ap, const float *x, const int *incx, const float *beta, float *y, const int *incy)
void liftracc_sger (const liftracc_order_t order, const int m, const int n, const float alpha, const float *x, const int incx, const float *y, const int incy, float *a, const int lda)
void liftracc_sger_ (const liftracc_order_t *order, const int *m, const int *n, const float *alpha, const float *x, const int *incx, const float *y, const int *incy, float *a, const int *lda)
void liftracc_ssyr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float *x, const int incx, float *a, const int lda)
void liftracc_ssyr_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const float *alpha, const float *x, const int *incx, float *a, const int *lda)
void liftracc_sspr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float *x, const int incx, float *ap)
void liftracc_sspr_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const float *alpha, const float *x, const int *incx, float *ap)
void liftracc_ssyr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float *x, const int incx, const float *y, const int incy, float *a, const int lda)
void liftracc_ssyr2_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const float *alpha, const float *x, const int *incx, const float *y, const int *incy, float *a, const int *lda)
void liftracc_sspr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float *x, const int incx, const float *y, const int incy, float *a)
void liftracc_sspr2_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const float *alpha, const float *x, const int *incx, const float *y, const int *incy, float *a)
void liftracc_dsymv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double *a, const int lda, const double *x, const int incx, const double beta, double *y, const int incy)
void liftracc_dsymv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const double *alpha, const double *a, const int *lda, const double *x, const int *incx, const double *beta, double *y, const int *incy)
void liftracc_dsbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const double alpha, const double *a, const int lda, const double *x, const int incx, const double beta, double *y, const int incy)
void liftracc_dsbmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const int *k, const double *alpha, const double *a, const int *lda, const double *x, const int *incx, const double *beta, double *y, const int *incy)
void liftracc_dspmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double *ap, const double *x, const int incx, const double beta, double *y, const int incy)
void liftracc_dspmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const double *alpha, const double *ap, const double *x, const int *incx, const double *beta, double *y, const int *incy)
void liftracc_dger (const liftracc_order_t order, const int m, const int n, const double alpha, const double *x, const int incx, const double *y, const int incy, double *a, const int lda)
void liftracc_dger_ (const liftracc_order_t *order, const int *m, const int *n, const double *alpha, const double *x, const int *incx, const double *y, const int *incy, double *a, const int *lda)
void liftracc_dsyr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double *x, const int incx, double *a, const int lda)
void liftracc_dsyr_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const double *alpha, const double *x, const int *incx, double *a, const int *lda)
void liftracc_dspr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double *x, const int incx, double *ap)
void liftracc_dspr_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const double *alpha, const double *x, const int *incx, double *ap)
void liftracc_dsyr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double *x, const int incx, const double *y, const int incy, double *a, const int lda)
void liftracc_dsyr2_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const double *alpha, const double *x, const int *incx, const double *y, const int *incy, double *a, const int *lda)
void liftracc_dspr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double *x, const int incx, const double *y, const int incy, double *a)
void liftracc_dspr2_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const double *alpha, const double *x, const int *incx, const double *y, const int *incy, double *a)
void liftracc_chemv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_chemv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const void *alpha, const void *a, const int *lda, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_chbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_chbmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_chpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *ap, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_chpmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const void *alpha, const void *ap, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_cgeru (const liftracc_order_t order, const int m, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *a, const int lda)
void liftracc_cgeru_ (const liftracc_order_t *order, const int *m, const int *n, const void *alpha, const void *x, const int *incx, const void *y, const int *incy, void *a, const int *lda)
void liftracc_cgerc (const liftracc_order_t order, const int m, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *a, const int lda)
void liftracc_cgerc_ (const liftracc_order_t *order, const int *m, const int *n, const void *alpha, const void *x, const int *incx, const void *y, const int *incy, void *a, const int *lda)
void liftracc_cher (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const void *x, const int incx, void *a, const int lda)
void liftracc_cher_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const float *alpha, const void *x, const int *incx, void *a, const int *lda)
void liftracc_chpr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const void *x, const int incx, void *a)
void liftracc_chpr_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const float *alpha, const void *x, const int *incx, void *a)
void liftracc_cher2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *a, const int lda)
void liftracc_cher2_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const void *alpha, const void *x, const int *incx, const void *y, const int *incy, void *a, const int *lda)
void liftracc_chpr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *ap)
void liftracc_chpr2_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const void *alpha, const void *x, const int *incx, const void *y, const int *incy, void *ap)
void liftracc_zhemv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_zhemv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const void *alpha, const void *a, const int *lda, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_zhbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const void *alpha, const void *a, const int lda, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_zhbmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_zhpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *ap, const void *x, const int incx, const void *beta, void *y, const int incy)
void liftracc_zhpmv_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const void *alpha, const void *ap, const void *x, const int *incx, const void *beta, void *y, const int *incy)
void liftracc_zgeru (const liftracc_order_t order, const int m, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *a, const int lda)
void liftracc_zgeru_ (const liftracc_order_t *order, const int *m, const int *n, const void *alpha, const void *x, const int *incx, const void *y, const int *incy, void *a, const int *lda)
void liftracc_zgerc (const liftracc_order_t order, const int m, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *a, const int lda)
void liftracc_zgerc_ (const liftracc_order_t *order, const int *m, const int *n, const void *alpha, const void *x, const int *incx, const void *y, const int *incy, void *a, const int *lda)
void liftracc_zher (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const void *x, const int incx, void *a, const int lda)
void liftracc_zher_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const double *alpha, const void *x, const int *incx, void *a, const int *lda)
void liftracc_zhpr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const void *x, const int incx, void *a)
void liftracc_zhpr_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const double *alpha, const void *x, const int *incx, void *a)
void liftracc_zher2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *a, const int lda)
void liftracc_zher2_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const void *alpha, const void *x, const int *incx, const void *y, const int *incy, void *a, const int *lda)
void liftracc_zhpr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void *alpha, const void *x, const int incx, const void *y, const int incy, void *ap)
void liftracc_zhpr2_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const int *n, const void *alpha, const void *x, const int *incx, const void *y, const int *incy, void *ap)
void liftracc_sgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const float alpha, const float *a, const int lda, const float *b, const int ldb, const float beta, float *c, const int ldc)
void liftracc_sgemm_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const liftracc_transpose_t *transb, const int *m, const int *n, const int *k, const float *alpha, const float *a, const int *lda, const float *b, const int *ldb, const float *beta, float *c, const int *ldc)
void liftracc_ssymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const float alpha, const float *a, const int lda, const float *b, const int ldb, const float beta, float *c, const int ldc)
void liftracc_ssymm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const int *m, const int *n, const float *alpha, const float *a, const int *lda, const float *b, const int *ldb, const float *beta, float *c, const int *ldc)
void liftracc_ssyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const float alpha, const float *a, const int lda, const float beta, float *c, const int ldc)
void liftracc_ssyrk_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const float *alpha, const float *a, const int *lda, const float *beta, float *c, const int *ldc)
void liftracc_ssyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const float alpha, const float *a, const int lda, const float *b, const int ldb, const float beta, float *c, const int ldc)
void liftracc_ssyr2k_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const float *alpha, const float *a, const int *lda, const float *b, const int *ldb, const float *beta, float *c, const int *ldc)
void liftracc_strmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const float alpha, const float *a, const int lda, float *b, const int ldb)
void liftracc_strmm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *m, const int *n, const float *alpha, const float *a, const int *lda, float *b, const int *ldb)
void liftracc_strsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const float alpha, const float *a, const int lda, float *b, const int ldb)
void liftracc_strsm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *m, const int *n, const float *alpha, const float *a, const int *lda, float *b, const int *ldb)
void liftracc_dgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const double alpha, const double *a, const int lda, const double *b, const int ldb, const double beta, double *c, const int ldc)
void liftracc_dgemm_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const liftracc_transpose_t *transb, const int *m, const int *n, const int *k, const double *alpha, const double *a, const int *lda, const double *b, const int *ldb, const double *beta, double *c, const int *ldc)
void liftracc_dsymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const double alpha, const double *a, const int lda, const double *b, const int ldb, const double beta, double *c, const int ldc)
void liftracc_dsymm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const int *m, const int *n, const double *alpha, const double *a, const int *lda, const double *b, const int *ldb, const double *beta, double *c, const int *ldc)
void liftracc_dsyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const double alpha, const double *a, const int lda, const double beta, double *c, const int ldc)
void liftracc_dsyrk_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const double *alpha, const double *a, const int *lda, const double *beta, double *c, const int *ldc)
void liftracc_dsyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const double alpha, const double *a, const int lda, const double *b, const int ldb, const double beta, double *c, const int ldc)
void liftracc_dsyr2k_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const double *alpha, const double *a, const int *lda, const double *b, const int *ldb, const double *beta, double *c, const int *ldc)
void liftracc_dtrmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const double alpha, const double *a, const int lda, double *b, const int ldb)
void liftracc_dtrmm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *m, const int *n, const double *alpha, const double *a, const int *lda, double *b, const int *ldb)
void liftracc_dtrsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const double alpha, const double *a, const int lda, double *b, const int ldb)
void liftracc_dtrsm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *m, const int *n, const double *alpha, const double *a, const int *lda, double *b, const int *ldb)
void liftracc_cgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
void liftracc_cgemm_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const liftracc_transpose_t *transb, const int *m, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const void *beta, void *c, const int *ldc)
void liftracc_csymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
void liftracc_csymm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const int *m, const int *n, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const void *beta, void *c, const int *ldc)
void liftracc_csyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void *alpha, const void *a, const int lda, const void *beta, void *c, const int ldc)
void liftracc_csyrk_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *beta, void *c, const int *ldc)
void liftracc_csyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
void liftracc_csyr2k_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const void *beta, void *c, const int *ldc)
void liftracc_ctrmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void *alpha, const void *a, const int lda, void *b, const int ldb)
void liftracc_ctrmm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *m, const int *n, const void *alpha, const void *a, const int *lda, void *b, const int *ldb)
void liftracc_ctrsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void *alpha, const void *a, const int lda, void *b, const int ldb)
void liftracc_ctrsm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *m, const int *n, const void *alpha, const void *a, const int *lda, void *b, const int *ldb)
void liftracc_zgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
void liftracc_zgemm_ (const liftracc_order_t *order, const liftracc_transpose_t *transa, const liftracc_transpose_t *transb, const int *m, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const void *beta, void *c, const int *ldc)
void liftracc_zsymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
void liftracc_zsymm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const int *m, const int *n, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const void *beta, void *c, const int *ldc)
void liftracc_zsyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void *alpha, const void *a, const int lda, const void *beta, void *c, const int ldc)
void liftracc_zsyrk_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *beta, void *c, const int *ldc)
void liftracc_zsyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
void liftracc_zsyr2k_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const void *beta, void *c, const int *ldc)
void liftracc_ztrmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void *alpha, const void *a, const int lda, void *b, const int ldb)
void liftracc_ztrmm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *m, const int *n, const void *alpha, const void *a, const int *lda, void *b, const int *ldb)
void liftracc_ztrsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void *alpha, const void *a, const int lda, void *b, const int ldb)
void liftracc_ztrsm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const liftracc_transpose_t *transa, const liftracc_diag_t *diag, const int *m, const int *n, const void *alpha, const void *a, const int *lda, void *b, const int *ldb)
void liftracc_chemm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
void liftracc_chemm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const int *m, const int *n, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const void *beta, void *c, const int *ldc)
void liftracc_cherk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const float alpha, const void *a, const int lda, const float beta, void *c, const int ldc)
void liftracc_cherk_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const float *alpha, const void *a, const int *lda, const float *beta, void *c, const int *ldc)
void liftracc_cher2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const float beta, void *c, const int ldc)
void liftracc_cher2k_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const float *beta, void *c, const int *ldc)
void liftracc_zhemm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const void *beta, void *c, const int ldc)
void liftracc_zhemm_ (const liftracc_order_t *order, const liftracc_side_t *side, const liftracc_uplo_t *uplo, const int *m, const int *n, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const void *beta, void *c, const int *ldc)
void liftracc_zherk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const double alpha, const void *a, const int lda, const double beta, void *c, const int ldc)
void liftracc_zherk_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const double *alpha, const void *a, const int *lda, const double *beta, void *c, const int *ldc)
void liftracc_zher2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void *alpha, const void *a, const int lda, const void *b, const int ldb, const double beta, void *c, const int ldc)
void liftracc_zher2k_ (const liftracc_order_t *order, const liftracc_uplo_t *uplo, const liftracc_transpose_t *trans, const int *n, const int *k, const void *alpha, const void *a, const int *lda, const void *b, const int *ldb, const double *beta, void *c, const int *ldc)
void liftracc_xerbla (int p, const char *rout, const char *form,...)
void liftracc_xerbla_ (int *p, const char *rout, const char *form,...)
Variables
liftracc_selector_problem_info_t pinfo = { }
Detailed Description
[generated file]
Definition in file liftracc_autogen.c.
Function Documentation
void liftracc_caxpy (const int n, const void * alpha, const void * x, const int incx, void * y, const int incy)
Definition at line 1631 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CAXPY.
Referenced by liftracc_caxpy_().
void liftracc_caxpy_ (const int * n, const void * alpha, const void * x, const int * incx, void * y, const int * incy)
Definition at line 1668 of file liftracc_autogen.c.
References liftracc_caxpy().
void liftracc_ccopy (const int n, const void * x, const int incx, void * y, const int incy)
Definition at line 1574 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CCOPY.
Referenced by liftracc_ccopy_().
void liftracc_ccopy_ (const int * n, const void * x, const int * incx, void * y, const int * incy)
Definition at line 1611 of file liftracc_autogen.c.
References liftracc_ccopy().
void liftracc_cdotc_sub (const int n, const void * x, const int incx, const void * y, const int incy, void * dotc)
Definition at line 320 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CDOTC_SUB.
Referenced by liftracc_cdotc_sub_().
void liftracc_cdotc_sub_ (const int * n, const void * x, const int * incx, const void * y, const int * incy, void * dotc)
Definition at line 357 of file liftracc_autogen.c.
References liftracc_cdotc_sub().
void liftracc_cdotu_sub (const int n, const void * x, const int incx, const void * y, const int incy, void * dotu)
Definition at line 263 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CDOTU_SUB.
Referenced by liftracc_cdotu_sub_().
void liftracc_cdotu_sub_ (const int * n, const void * x, const int * incx, const void * y, const int * incy, void * dotu)
Definition at line 300 of file liftracc_autogen.c.
References liftracc_cdotu_sub().
void liftracc_cgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 3626 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CGBMV.
Referenced by liftracc_cgbmv_().
void liftracc_cgbmv_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const int * m, const int * n, const int * kl, const int * ku, const void * alpha, const void * a, const int * lda, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 3663 of file liftracc_autogen.c.
References liftracc_cgbmv().
void liftracc_cgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
Definition at line 7103 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CGEMM.
Referenced by liftracc_cgemm_().
void liftracc_cgemm_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const liftracc_transpose_t * transb, const int * m, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const void * beta, void * c, const int * ldc)
Definition at line 7140 of file liftracc_autogen.c.
References liftracc_cgemm().
void liftracc_cgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 3569 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CGEMV.
Referenced by liftracc_cgemv_().
void liftracc_cgemv_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const int * m, const int * n, const void * alpha, const void * a, const int * lda, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 3606 of file liftracc_autogen.c.
References liftracc_cgemv().
void liftracc_cgerc (const liftracc_order_t order, const int m, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * a, const int lda)
Definition at line 5621 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CGERC.
Referenced by liftracc_cgerc_().
void liftracc_cgerc_ (const liftracc_order_t * order, const int * m, const int * n, const void * alpha, const void * x, const int * incx, const void * y, const int * incy, void * a, const int * lda)
Definition at line 5658 of file liftracc_autogen.c.
References liftracc_cgerc().
void liftracc_cgeru (const liftracc_order_t order, const int m, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * a, const int lda)
Definition at line 5564 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CGERU.
Referenced by liftracc_cgeru_().
void liftracc_cgeru_ (const liftracc_order_t * order, const int * m, const int * n, const void * alpha, const void * x, const int * incx, const void * y, const int * incy, void * a, const int * lda)
Definition at line 5601 of file liftracc_autogen.c.
References liftracc_cgeru().
void liftracc_chbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 5450 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CHBMV.
Referenced by liftracc_chbmv_().
void liftracc_chbmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 5487 of file liftracc_autogen.c.
References liftracc_chbmv().
void liftracc_chemm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
Definition at line 7787 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CHEMM.
Referenced by liftracc_chemm_().
void liftracc_chemm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const int * m, const int * n, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const void * beta, void * c, const int * ldc)
Definition at line 7824 of file liftracc_autogen.c.
References liftracc_chemm().
void liftracc_chemv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 5393 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CHEMV.
Referenced by liftracc_chemv_().
void liftracc_chemv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const void * alpha, const void * a, const int * lda, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 5430 of file liftracc_autogen.c.
References liftracc_chemv().
void liftracc_cher (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const void * x, const int incx, void * a, const int lda)
Definition at line 5678 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CHER.
Referenced by liftracc_cher_().
void liftracc_cher2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * a, const int lda)
Definition at line 5792 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CHER2.
Referenced by liftracc_cher2_().
void liftracc_cher2_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const void * alpha, const void * x, const int * incx, const void * y, const int * incy, void * a, const int * lda)
Definition at line 5829 of file liftracc_autogen.c.
References liftracc_cher2().
void liftracc_cher2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const float beta, void * c, const int ldc)
Definition at line 7901 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CHER2K.
Referenced by liftracc_cher2k_().
void liftracc_cher2k_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const float * beta, void * c, const int * ldc)
Definition at line 7938 of file liftracc_autogen.c.
References liftracc_cher2k().
void liftracc_cher_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const float * alpha, const void * x, const int * incx, void * a, const int * lda)
Definition at line 5715 of file liftracc_autogen.c.
References liftracc_cher().
void liftracc_cherk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const float alpha, const void * a, const int lda, const float beta, void * c, const int ldc)
Definition at line 7844 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CHERK.
Referenced by liftracc_cherk_().
void liftracc_cherk_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const float * alpha, const void * a, const int * lda, const float * beta, void * c, const int * ldc)
Definition at line 7881 of file liftracc_autogen.c.
References liftracc_cherk().
void liftracc_chpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * ap, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 5507 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CHPMV.
Referenced by liftracc_chpmv_().
void liftracc_chpmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const void * alpha, const void * ap, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 5544 of file liftracc_autogen.c.
References liftracc_chpmv().
void liftracc_chpr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const void * x, const int incx, void * a)
Definition at line 5735 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CHPR.
Referenced by liftracc_chpr_().
void liftracc_chpr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * ap)
Definition at line 5849 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CHPR2.
Referenced by liftracc_chpr2_().
void liftracc_chpr2_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const void * alpha, const void * x, const int * incx, const void * y, const int * incy, void * ap)
Definition at line 5886 of file liftracc_autogen.c.
References liftracc_chpr2().
void liftracc_chpr_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const float * alpha, const void * x, const int * incx, void * a)
Definition at line 5772 of file liftracc_autogen.c.
References liftracc_chpr().
void liftracc_cscal (const int n, const void * alpha, void * x, const int incx)
Definition at line 2429 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CSCAL.
Referenced by liftracc_cscal_().
void liftracc_cscal_ (const int * n, const void * alpha, void * x, const int * incx)
Definition at line 2466 of file liftracc_autogen.c.
References liftracc_cscal().
void liftracc_csscal (const int n, const float alpha, void * x, const int incx)
Definition at line 2543 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CSSCAL.
Referenced by liftracc_csscal_().
void liftracc_csscal_ (const int * n, const float * alpha, void * x, const int * incx)
Definition at line 2580 of file liftracc_autogen.c.
References liftracc_csscal().
void liftracc_cswap (const int n, void * x, const int incx, void * y, const int incy)
Definition at line 1517 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CSWAP.
Referenced by liftracc_cswap_().
void liftracc_cswap_ (const int * n, void * x, const int * incx, void * y, const int * incy)
Definition at line 1554 of file liftracc_autogen.c.
References liftracc_cswap().
void liftracc_csymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
Definition at line 7160 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CSYMM.
Referenced by liftracc_csymm_().
void liftracc_csymm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const int * m, const int * n, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const void * beta, void * c, const int * ldc)
Definition at line 7197 of file liftracc_autogen.c.
References liftracc_csymm().
void liftracc_csyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
Definition at line 7274 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CSYR2K.
Referenced by liftracc_csyr2k_().
void liftracc_csyr2k_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const void * beta, void * c, const int * ldc)
Definition at line 7311 of file liftracc_autogen.c.
References liftracc_csyr2k().
void liftracc_csyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void * alpha, const void * a, const int lda, const void * beta, void * c, const int ldc)
Definition at line 7217 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CSYRK.
Referenced by liftracc_csyrk_().
void liftracc_csyrk_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * beta, void * c, const int * ldc)
Definition at line 7254 of file liftracc_autogen.c.
References liftracc_csyrk().
void liftracc_ctbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void * a, const int lda, void * x, const int incx)
Definition at line 3740 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CTBMV.
Referenced by liftracc_ctbmv_().
void liftracc_ctbmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const int * k, const void * a, const int * lda, void * x, const int * incx)
Definition at line 3777 of file liftracc_autogen.c.
References liftracc_ctbmv().
void liftracc_ctbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void * a, const int lda, void * x, const int incx)
Definition at line 3911 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CTBSV.
Referenced by liftracc_ctbsv_().
void liftracc_ctbsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const int * k, const void * a, const int * lda, void * x, const int * incx)
Definition at line 3948 of file liftracc_autogen.c.
References liftracc_ctbsv().
void liftracc_ctpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * ap, void * x, const int incx)
Definition at line 3797 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CTPMV.
Referenced by liftracc_ctpmv_().
void liftracc_ctpmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const void * ap, void * x, const int * incx)
Definition at line 3834 of file liftracc_autogen.c.
References liftracc_ctpmv().
void liftracc_ctpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * ap, void * x, const int incx)
Definition at line 3968 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CTPSV.
Referenced by liftracc_ctpsv_().
void liftracc_ctpsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const void * ap, void * x, const int * incx)
Definition at line 4005 of file liftracc_autogen.c.
References liftracc_ctpsv().
void liftracc_ctrmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void * alpha, const void * a, const int lda, void * b, const int ldb)
Definition at line 7331 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CTRMM.
Referenced by liftracc_ctrmm_().
void liftracc_ctrmm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * m, const int * n, const void * alpha, const void * a, const int * lda, void * b, const int * ldb)
Definition at line 7368 of file liftracc_autogen.c.
References liftracc_ctrmm().
void liftracc_ctrmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * a, const int lda, void * x, const int incx)
Definition at line 3683 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CTRMV.
Referenced by liftracc_ctrmv_().
void liftracc_ctrmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const void * a, const int * lda, void * x, const int * incx)
Definition at line 3720 of file liftracc_autogen.c.
References liftracc_ctrmv().
void liftracc_ctrsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void * alpha, const void * a, const int lda, void * b, const int ldb)
Definition at line 7388 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CTRSM.
Referenced by liftracc_ctrsm_().
void liftracc_ctrsm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * m, const int * n, const void * alpha, const void * a, const int * lda, void * b, const int * ldb)
Definition at line 7425 of file liftracc_autogen.c.
References liftracc_ctrsm().
void liftracc_ctrsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * a, const int lda, void * x, const int incx)
Definition at line 3854 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_CTRSV.
Referenced by liftracc_ctrsv_().
void liftracc_ctrsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const void * a, const int * lda, void * x, const int * incx)
Definition at line 3891 of file liftracc_autogen.c.
References liftracc_ctrsv().
double liftracc_dasum (const int n, const double * x, const int incx)
Definition at line 662 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DASUM.
Referenced by liftracc_dasum_().
double liftracc_dasum_ (const int * n, const double * x, const int * incx)
Definition at line 699 of file liftracc_autogen.c.
References liftracc_dasum().
void liftracc_daxpy (const int n, const double alpha, const double * x, const int incx, double * y, const int incy)
Definition at line 1460 of file liftracc_autogen.c.
Referenced by liftracc_daxpy_().
void liftracc_daxpy_ (const int * n, const double * alpha, const double * x, const int * incx, double * y, const int * incy)
Definition at line 1497 of file liftracc_autogen.c.
References liftracc_daxpy().
void liftracc_dcopy (const int n, const double * x, const int incx, double * y, const int incy)
Definition at line 1403 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DCOPY.
Referenced by liftracc_dcopy_().
void liftracc_dcopy_ (const int * n, const double * x, const int * incx, double * y, const int * incy)
Definition at line 1440 of file liftracc_autogen.c.
References liftracc_dcopy().
double liftracc_ddot (const int n, const double * x, const int incx, const double * y, const int incy)
Definition at line 206 of file liftracc_autogen.c.
Referenced by liftracc_ddot_().
double liftracc_ddot_ (const int * n, const double * x, const int * incx, const double * y, const int * incy)
Definition at line 243 of file liftracc_autogen.c.
void liftracc_dgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const double alpha, const double * a, const int lda, const double * x, const int incx, const double beta, double * y, const int incy)
Definition at line 3170 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DGBMV.
Referenced by liftracc_dgbmv_().
void liftracc_dgbmv_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const int * m, const int * n, const int * kl, const int * ku, const double * alpha, const double * a, const int * lda, const double * x, const int * incx, const double * beta, double * y, const int * incy)
Definition at line 3207 of file liftracc_autogen.c.
References liftracc_dgbmv().
void liftracc_dgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const double alpha, const double * a, const int lda, const double * b, const int ldb, const double beta, double * c, const int ldc)
Definition at line 6761 of file liftracc_autogen.c.
Referenced by liftracc_dgemm_().
void liftracc_dgemm_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const liftracc_transpose_t * transb, const int * m, const int * n, const int * k, const double * alpha, const double * a, const int * lda, const double * b, const int * ldb, const double * beta, double * c, const int * ldc)
Definition at line 6798 of file liftracc_autogen.c.
References liftracc_dgemm().
void liftracc_dgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const double alpha, const double * a, const int lda, const double * x, const int incx, const double beta, double * y, const int incy)
Definition at line 3113 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DGEMV.
Referenced by liftracc_dgemv_().
void liftracc_dgemv_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const int * m, const int * n, const double * alpha, const double * a, const int * lda, const double * x, const int * incx, const double * beta, double * y, const int * incy)
Definition at line 3150 of file liftracc_autogen.c.
References liftracc_dgemv().
void liftracc_dger (const liftracc_order_t order, const int m, const int n, const double alpha, const double * x, const int incx, const double * y, const int incy, double * a, const int lda)
Definition at line 5108 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DGER.
Referenced by liftracc_dger_().
void liftracc_dger_ (const liftracc_order_t * order, const int * m, const int * n, const double * alpha, const double * x, const int * incx, const double * y, const int * incy, double * a, const int * lda)
Definition at line 5145 of file liftracc_autogen.c.
References liftracc_dger().
double liftracc_dnrm2 (const int n, const double * x, const int incx)
Definition at line 605 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DNRM2.
Referenced by liftracc_dnrm2_().
double liftracc_dnrm2_ (const int * n, const double * x, const int * incx)
Definition at line 642 of file liftracc_autogen.c.
References liftracc_dnrm2().
void liftracc_drot (const int n, double * x, const int incx, double * y, const int incy, const double c, const double s)
Definition at line 2201 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DROT.
Referenced by liftracc_drot_().
void liftracc_drot_ (const int * n, double * x, const int * incx, double * y, const int * incy, const double * c, const double * s)
Definition at line 2238 of file liftracc_autogen.c.
References liftracc_drot().
void liftracc_drotg (double * a, double * b, double * c, double * s)
Definition at line 2087 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DROTG.
Referenced by liftracc_drotg_().
void liftracc_drotg_ (double * a, double * b, double * c, double * s)
Definition at line 2124 of file liftracc_autogen.c.
References liftracc_drotg().
void liftracc_drotm (const int n, double * x, const int incx, double * y, const int incy, const double * p)
Definition at line 2258 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DROTM.
Referenced by liftracc_drotm_().
void liftracc_drotm_ (const int * n, double * x, const int * incx, double * y, const int * incy, const double * p)
Definition at line 2295 of file liftracc_autogen.c.
References liftracc_drotm().
void liftracc_drotmg (double * d1, double * d2, double * b1, const double b2, double * p)
Definition at line 2144 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DROTMG.
Referenced by liftracc_drotmg_().
void liftracc_drotmg_ (double * d1, double * d2, double * b1, const double * b2, double * p)
Definition at line 2181 of file liftracc_autogen.c.
References liftracc_drotmg().
void liftracc_dsbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const double alpha, const double * a, const int lda, const double * x, const int incx, const double beta, double * y, const int incy)
Definition at line 4994 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DSBMV.
Referenced by liftracc_dsbmv_().
void liftracc_dsbmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const int * k, const double * alpha, const double * a, const int * lda, const double * x, const int * incx, const double * beta, double * y, const int * incy)
Definition at line 5031 of file liftracc_autogen.c.
References liftracc_dsbmv().
void liftracc_dscal (const int n, const double alpha, double * x, const int incx)
Definition at line 2372 of file liftracc_autogen.c.
Referenced by liftracc_dscal_().
void liftracc_dscal_ (const int * n, const double * alpha, double * x, const int * incx)
Definition at line 2409 of file liftracc_autogen.c.
References liftracc_dscal().
double liftracc_dsdot (const int n, const float * x, const int incx, const float * y, const int incy)
Definition at line 92 of file liftracc_autogen.c.
Referenced by liftracc_dsdot_().
double liftracc_dsdot_ (const int * n, const float * x, const int * incx, const float * y, const int * incy)
Definition at line 129 of file liftracc_autogen.c.
void liftracc_dspmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double * ap, const double * x, const int incx, const double beta, double * y, const int incy)
Definition at line 5051 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DSPMV.
Referenced by liftracc_dspmv_().
void liftracc_dspmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const double * alpha, const double * ap, const double * x, const int * incx, const double * beta, double * y, const int * incy)
Definition at line 5088 of file liftracc_autogen.c.
References liftracc_dspmv().
void liftracc_dspr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double * x, const int incx, double * ap)
Definition at line 5222 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DSPR.
Referenced by liftracc_dspr_().
void liftracc_dspr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double * x, const int incx, const double * y, const int incy, double * a)
Definition at line 5336 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DSPR2.
Referenced by liftracc_dspr2_().
void liftracc_dspr2_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const double * alpha, const double * x, const int * incx, const double * y, const int * incy, double * a)
Definition at line 5373 of file liftracc_autogen.c.
References liftracc_dspr2().
void liftracc_dspr_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const double * alpha, const double * x, const int * incx, double * ap)
Definition at line 5259 of file liftracc_autogen.c.
References liftracc_dspr().
void liftracc_dswap (const int n, double * x, const int incx, double * y, const int incy)
Definition at line 1346 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DSWAP.
Referenced by liftracc_dswap_().
void liftracc_dswap_ (const int * n, double * x, const int * incx, double * y, const int * incy)
Definition at line 1383 of file liftracc_autogen.c.
References liftracc_dswap().
void liftracc_dsymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const double alpha, const double * a, const int lda, const double * b, const int ldb, const double beta, double * c, const int ldc)
Definition at line 6818 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DSYMM.
Referenced by liftracc_dsymm_().
void liftracc_dsymm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const int * m, const int * n, const double * alpha, const double * a, const int * lda, const double * b, const int * ldb, const double * beta, double * c, const int * ldc)
Definition at line 6855 of file liftracc_autogen.c.
References liftracc_dsymm().
void liftracc_dsymv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double * a, const int lda, const double * x, const int incx, const double beta, double * y, const int incy)
Definition at line 4937 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DSYMV.
Referenced by liftracc_dsymv_().
void liftracc_dsymv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const double * alpha, const double * a, const int * lda, const double * x, const int * incx, const double * beta, double * y, const int * incy)
Definition at line 4974 of file liftracc_autogen.c.
References liftracc_dsymv().
void liftracc_dsyr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double * x, const int incx, double * a, const int lda)
Definition at line 5165 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DSYR.
Referenced by liftracc_dsyr_().
void liftracc_dsyr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const double * x, const int incx, const double * y, const int incy, double * a, const int lda)
Definition at line 5279 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DSYR2.
Referenced by liftracc_dsyr2_().
void liftracc_dsyr2_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const double * alpha, const double * x, const int * incx, const double * y, const int * incy, double * a, const int * lda)
Definition at line 5316 of file liftracc_autogen.c.
References liftracc_dsyr2().
void liftracc_dsyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const double alpha, const double * a, const int lda, const double * b, const int ldb, const double beta, double * c, const int ldc)
Definition at line 6932 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DSYR2K.
Referenced by liftracc_dsyr2k_().
void liftracc_dsyr2k_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const double * alpha, const double * a, const int * lda, const double * b, const int * ldb, const double * beta, double * c, const int * ldc)
Definition at line 6969 of file liftracc_autogen.c.
References liftracc_dsyr2k().
void liftracc_dsyr_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const double * alpha, const double * x, const int * incx, double * a, const int * lda)
Definition at line 5202 of file liftracc_autogen.c.
References liftracc_dsyr().
void liftracc_dsyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const double alpha, const double * a, const int lda, const double beta, double * c, const int ldc)
Definition at line 6875 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DSYRK.
Referenced by liftracc_dsyrk_().
void liftracc_dsyrk_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const double * alpha, const double * a, const int * lda, const double * beta, double * c, const int * ldc)
Definition at line 6912 of file liftracc_autogen.c.
References liftracc_dsyrk().
void liftracc_dtbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const double * a, const int lda, double * x, const int incx)
Definition at line 3284 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DTBMV.
Referenced by liftracc_dtbmv_().
void liftracc_dtbmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const int * k, const double * a, const int * lda, double * x, const int * incx)
Definition at line 3321 of file liftracc_autogen.c.
References liftracc_dtbmv().
void liftracc_dtbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const double * a, const int lda, double * x, const int incx)
Definition at line 3455 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DTBSV.
Referenced by liftracc_dtbsv_().
void liftracc_dtbsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const int * k, const double * a, const int * lda, double * x, const int * incx)
Definition at line 3492 of file liftracc_autogen.c.
References liftracc_dtbsv().
void liftracc_dtpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double * ap, double * x, const int incx)
Definition at line 3341 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DTPMV.
Referenced by liftracc_dtpmv_().
void liftracc_dtpmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const double * ap, double * x, const int * incx)
Definition at line 3378 of file liftracc_autogen.c.
References liftracc_dtpmv().
void liftracc_dtpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double * ap, double * x, const int incx)
Definition at line 3512 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DTPSV.
Referenced by liftracc_dtpsv_().
void liftracc_dtpsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const double * ap, double * x, const int * incx)
Definition at line 3549 of file liftracc_autogen.c.
References liftracc_dtpsv().
void liftracc_dtrmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const double alpha, const double * a, const int lda, double * b, const int ldb)
Definition at line 6989 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DTRMM.
Referenced by liftracc_dtrmm_().
void liftracc_dtrmm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * m, const int * n, const double * alpha, const double * a, const int * lda, double * b, const int * ldb)
Definition at line 7026 of file liftracc_autogen.c.
References liftracc_dtrmm().
void liftracc_dtrmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double * a, const int lda, double * x, const int incx)
Definition at line 3227 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DTRMV.
Referenced by liftracc_dtrmv_().
void liftracc_dtrmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const double * a, const int * lda, double * x, const int * incx)
Definition at line 3264 of file liftracc_autogen.c.
References liftracc_dtrmv().
void liftracc_dtrsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const double alpha, const double * a, const int lda, double * b, const int ldb)
Definition at line 7046 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DTRSM.
Referenced by liftracc_dtrsm_().
void liftracc_dtrsm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * m, const int * n, const double * alpha, const double * a, const int * lda, double * b, const int * ldb)
Definition at line 7083 of file liftracc_autogen.c.
References liftracc_dtrsm().
void liftracc_dtrsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const double * a, const int lda, double * x, const int incx)
Definition at line 3398 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DTRSV.
Referenced by liftracc_dtrsv_().
void liftracc_dtrsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const double * a, const int * lda, double * x, const int * incx)
Definition at line 3435 of file liftracc_autogen.c.
References liftracc_dtrsv().
double liftracc_dzasum (const int n, const void * x, const int incx)
Definition at line 890 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DZASUM.
Referenced by liftracc_dzasum_().
double liftracc_dzasum_ (const int * n, const void * x, const int * incx)
Definition at line 927 of file liftracc_autogen.c.
References liftracc_dzasum().
double liftracc_dznrm2 (const int n, const void * x, const int incx)
Definition at line 833 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_DZNRM2.
Referenced by liftracc_dznrm2_().
double liftracc_dznrm2_ (const int * n, const void * x, const int * incx)
Definition at line 870 of file liftracc_autogen.c.
References liftracc_dznrm2().
liftracc_index_t liftracc_icamax (const int n, const void * x, const int incx)
Definition at line 1061 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ICAMAX.
Referenced by liftracc_icamax_().
liftracc_index_t liftracc_icamax_ (const int * n, const void * x, const int * incx)
Definition at line 1098 of file liftracc_autogen.c.
References liftracc_icamax().
liftracc_index_t liftracc_idamax (const int n, const double * x, const int incx)
Definition at line 1004 of file liftracc_autogen.c.
Referenced by liftracc_idamax_().
liftracc_index_t liftracc_idamax_ (const int * n, const double * x, const int * incx)
Definition at line 1041 of file liftracc_autogen.c.
References liftracc_idamax().
liftracc_index_t liftracc_isamax (const int n, const float * x, const int incx)
Definition at line 947 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ISAMAX.
Referenced by liftracc_isamax_().
liftracc_index_t liftracc_isamax_ (const int * n, const float * x, const int * incx)
Definition at line 984 of file liftracc_autogen.c.
References liftracc_isamax().
liftracc_index_t liftracc_izamax (const int n, const void * x, const int incx)
Definition at line 1118 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_IZAMAX.
Referenced by liftracc_izamax_().
liftracc_index_t liftracc_izamax_ (const int * n, const void * x, const int * incx)
Definition at line 1155 of file liftracc_autogen.c.
References liftracc_izamax().
float liftracc_sasum (const int n, const float * x, const int incx)
Definition at line 548 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SASUM.
Referenced by liftracc_sasum_().
float liftracc_sasum_ (const int * n, const float * x, const int * incx)
Definition at line 585 of file liftracc_autogen.c.
References liftracc_sasum().
void liftracc_saxpy (const int n, const float alpha, const float * x, const int incx, float * y, const int incy)
Definition at line 1289 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SAXPY.
Referenced by liftracc_saxpy_().
void liftracc_saxpy_ (const int * n, const float * alpha, const float * x, const int * incx, float * y, const int * incy)
Definition at line 1326 of file liftracc_autogen.c.
References liftracc_saxpy().
float liftracc_scasum (const int n, const void * x, const int incx)
Definition at line 776 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SCASUM.
Referenced by liftracc_scasum_().
float liftracc_scasum_ (const int * n, const void * x, const int * incx)
Definition at line 813 of file liftracc_autogen.c.
References liftracc_scasum().
float liftracc_scnrm2 (const int n, const void * x, const int incx)
Definition at line 719 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SCNRM2.
Referenced by liftracc_scnrm2_().
float liftracc_scnrm2_ (const int * n, const void * x, const int * incx)
Definition at line 756 of file liftracc_autogen.c.
References liftracc_scnrm2().
void liftracc_scopy (const int n, const float * x, const int incx, float * y, const int incy)
Definition at line 1232 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SCOPY.
Referenced by liftracc_scopy_().
void liftracc_scopy_ (const int * n, const float * x, const int * incx, float * y, const int * incy)
Definition at line 1269 of file liftracc_autogen.c.
References liftracc_scopy().
float liftracc_sdot (const int n, const float * x, const int incx, const float * y, const int incy)
Definition at line 149 of file liftracc_autogen.c.
Referenced by liftracc_sdot_().
float liftracc_sdot_ (const int * n, const float * x, const int * incx, const float * y, const int * incy)
Definition at line 186 of file liftracc_autogen.c.
float liftracc_sdsdot (const int n, const float alpha, const float * x, const int incx, const float * y, const int incy)
Definition at line 35 of file liftracc_autogen.c.
Referenced by liftracc_sdsdot_().
float liftracc_sdsdot_ (const int * n, const float * alpha, const float * x, const int * incx, const float * y, const int * incy)
Definition at line 72 of file liftracc_autogen.c.
void liftracc_sgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const float alpha, const float * a, const int lda, const float * x, const int incx, const float beta, float * y, const int incy)
Definition at line 2714 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SGBMV.
Referenced by liftracc_sgbmv_().
void liftracc_sgbmv_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const int * m, const int * n, const int * kl, const int * ku, const float * alpha, const float * a, const int * lda, const float * x, const int * incx, const float * beta, float * y, const int * incy)
Definition at line 2751 of file liftracc_autogen.c.
References liftracc_sgbmv().
void liftracc_sgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const float alpha, const float * a, const int lda, const float * b, const int ldb, const float beta, float * c, const int ldc)
Definition at line 6419 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SGEMM.
Referenced by liftracc_sgemm_().
void liftracc_sgemm_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const liftracc_transpose_t * transb, const int * m, const int * n, const int * k, const float * alpha, const float * a, const int * lda, const float * b, const int * ldb, const float * beta, float * c, const int * ldc)
Definition at line 6456 of file liftracc_autogen.c.
References liftracc_sgemm().
void liftracc_sgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const float alpha, const float * a, const int lda, const float * x, const int incx, const float beta, float * y, const int incy)
Definition at line 2657 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SGEMV.
Referenced by liftracc_sgemv_().
void liftracc_sgemv_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const int * m, const int * n, const float * alpha, const float * a, const int * lda, const float * x, const int * incx, const float * beta, float * y, const int * incy)
Definition at line 2694 of file liftracc_autogen.c.
References liftracc_sgemv().
void liftracc_sger (const liftracc_order_t order, const int m, const int n, const float alpha, const float * x, const int incx, const float * y, const int incy, float * a, const int lda)
Definition at line 4652 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SGER.
Referenced by liftracc_sger_().
void liftracc_sger_ (const liftracc_order_t * order, const int * m, const int * n, const float * alpha, const float * x, const int * incx, const float * y, const int * incy, float * a, const int * lda)
Definition at line 4689 of file liftracc_autogen.c.
References liftracc_sger().
float liftracc_snrm2 (const int n, const float * x, const int incx)
Definition at line 491 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SNRM2.
Referenced by liftracc_snrm2_().
float liftracc_snrm2_ (const int * n, const float * x, const int * incx)
Definition at line 528 of file liftracc_autogen.c.
References liftracc_snrm2().
void liftracc_srot (const int n, float * x, const int incx, float * y, const int incy, const float c, const float s)
Definition at line 1973 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SROT.
Referenced by liftracc_srot_().
void liftracc_srot_ (const int * n, float * x, const int * incx, float * y, const int * incy, const float * c, const float * s)
Definition at line 2010 of file liftracc_autogen.c.
References liftracc_srot().
void liftracc_srotg (float * a, float * b, float * c, float * s)
Definition at line 1859 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SROTG.
Referenced by liftracc_srotg_().
void liftracc_srotg_ (float * a, float * b, float * c, float * s)
Definition at line 1896 of file liftracc_autogen.c.
References liftracc_srotg().
void liftracc_srotm (const int n, float * x, const int incx, float * y, const int incy, const float * p)
Definition at line 2030 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SROTM.
Referenced by liftracc_srotm_().
void liftracc_srotm_ (const int * n, float * x, const int * incx, float * y, const int * incy, const float * p)
Definition at line 2067 of file liftracc_autogen.c.
References liftracc_srotm().
void liftracc_srotmg (float * d1, float * d2, float * b1, const float b2, float * p)
Definition at line 1916 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SROTMG.
Referenced by liftracc_srotmg_().
void liftracc_srotmg_ (float * d1, float * d2, float * b1, const float * b2, float * p)
Definition at line 1953 of file liftracc_autogen.c.
References liftracc_srotmg().
void liftracc_ssbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const float alpha, const float * a, const int lda, const float * x, const int incx, const float beta, float * y, const int incy)
Definition at line 4538 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SSBMV.
Referenced by liftracc_ssbmv_().
void liftracc_ssbmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const int * k, const float * alpha, const float * a, const int * lda, const float * x, const int * incx, const float * beta, float * y, const int * incy)
Definition at line 4575 of file liftracc_autogen.c.
References liftracc_ssbmv().
void liftracc_sscal (const int n, const float alpha, float * x, const int incx)
Definition at line 2315 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SSCAL.
Referenced by liftracc_sscal_().
void liftracc_sscal_ (const int * n, const float * alpha, float * x, const int * incx)
Definition at line 2352 of file liftracc_autogen.c.
References liftracc_sscal().
void liftracc_sspmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float * ap, const float * x, const int incx, const float beta, float * y, const int incy)
Definition at line 4595 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SSPMV.
Referenced by liftracc_sspmv_().
void liftracc_sspmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const float * alpha, const float * ap, const float * x, const int * incx, const float * beta, float * y, const int * incy)
Definition at line 4632 of file liftracc_autogen.c.
References liftracc_sspmv().
void liftracc_sspr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float * x, const int incx, float * ap)
Definition at line 4766 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SSPR.
Referenced by liftracc_sspr_().
void liftracc_sspr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float * x, const int incx, const float * y, const int incy, float * a)
Definition at line 4880 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SSPR2.
Referenced by liftracc_sspr2_().
void liftracc_sspr2_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const float * alpha, const float * x, const int * incx, const float * y, const int * incy, float * a)
Definition at line 4917 of file liftracc_autogen.c.
References liftracc_sspr2().
void liftracc_sspr_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const float * alpha, const float * x, const int * incx, float * ap)
Definition at line 4803 of file liftracc_autogen.c.
References liftracc_sspr().
void liftracc_sswap (const int n, float * x, const int incx, float * y, const int incy)
Definition at line 1175 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SSWAP.
Referenced by liftracc_sswap_().
void liftracc_sswap_ (const int * n, float * x, const int * incx, float * y, const int * incy)
Definition at line 1212 of file liftracc_autogen.c.
References liftracc_sswap().
void liftracc_ssymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const float alpha, const float * a, const int lda, const float * b, const int ldb, const float beta, float * c, const int ldc)
Definition at line 6476 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SSYMM.
Referenced by liftracc_ssymm_().
void liftracc_ssymm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const int * m, const int * n, const float * alpha, const float * a, const int * lda, const float * b, const int * ldb, const float * beta, float * c, const int * ldc)
Definition at line 6513 of file liftracc_autogen.c.
References liftracc_ssymm().
void liftracc_ssymv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float * a, const int lda, const float * x, const int incx, const float beta, float * y, const int incy)
Definition at line 4481 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SSYMV.
Referenced by liftracc_ssymv_().
void liftracc_ssymv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const float * alpha, const float * a, const int * lda, const float * x, const int * incx, const float * beta, float * y, const int * incy)
Definition at line 4518 of file liftracc_autogen.c.
References liftracc_ssymv().
void liftracc_ssyr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float * x, const int incx, float * a, const int lda)
Definition at line 4709 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SSYR.
Referenced by liftracc_ssyr_().
void liftracc_ssyr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const float alpha, const float * x, const int incx, const float * y, const int incy, float * a, const int lda)
Definition at line 4823 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SSYR2.
Referenced by liftracc_ssyr2_().
void liftracc_ssyr2_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const float * alpha, const float * x, const int * incx, const float * y, const int * incy, float * a, const int * lda)
Definition at line 4860 of file liftracc_autogen.c.
References liftracc_ssyr2().
void liftracc_ssyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const float alpha, const float * a, const int lda, const float * b, const int ldb, const float beta, float * c, const int ldc)
Definition at line 6590 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SSYR2K.
Referenced by liftracc_ssyr2k_().
void liftracc_ssyr2k_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const float * alpha, const float * a, const int * lda, const float * b, const int * ldb, const float * beta, float * c, const int * ldc)
Definition at line 6627 of file liftracc_autogen.c.
References liftracc_ssyr2k().
void liftracc_ssyr_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const float * alpha, const float * x, const int * incx, float * a, const int * lda)
Definition at line 4746 of file liftracc_autogen.c.
References liftracc_ssyr().
void liftracc_ssyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const float alpha, const float * a, const int lda, const float beta, float * c, const int ldc)
Definition at line 6533 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_SSYRK.
Referenced by liftracc_ssyrk_().
void liftracc_ssyrk_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const float * alpha, const float * a, const int * lda, const float * beta, float * c, const int * ldc)
Definition at line 6570 of file liftracc_autogen.c.
References liftracc_ssyrk().
void liftracc_stbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const float * a, const int lda, float * x, const int incx)
Definition at line 2828 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_STBMV.
Referenced by liftracc_stbmv_().
void liftracc_stbmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const int * k, const float * a, const int * lda, float * x, const int * incx)
Definition at line 2865 of file liftracc_autogen.c.
References liftracc_stbmv().
void liftracc_stbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const float * a, const int lda, float * x, const int incx)
Definition at line 2999 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_STBSV.
Referenced by liftracc_stbsv_().
void liftracc_stbsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const int * k, const float * a, const int * lda, float * x, const int * incx)
Definition at line 3036 of file liftracc_autogen.c.
References liftracc_stbsv().
void liftracc_stpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float * ap, float * x, const int incx)
Definition at line 2885 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_STPMV.
Referenced by liftracc_stpmv_().
void liftracc_stpmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const float * ap, float * x, const int * incx)
Definition at line 2922 of file liftracc_autogen.c.
References liftracc_stpmv().
void liftracc_stpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float * ap, float * x, const int incx)
Definition at line 3056 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_STPSV.
Referenced by liftracc_stpsv_().
void liftracc_stpsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const float * ap, float * x, const int * incx)
Definition at line 3093 of file liftracc_autogen.c.
References liftracc_stpsv().
void liftracc_strmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const float alpha, const float * a, const int lda, float * b, const int ldb)
Definition at line 6647 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_STRMM.
Referenced by liftracc_strmm_().
void liftracc_strmm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * m, const int * n, const float * alpha, const float * a, const int * lda, float * b, const int * ldb)
Definition at line 6684 of file liftracc_autogen.c.
References liftracc_strmm().
void liftracc_strmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float * a, const int lda, float * x, const int incx)
Definition at line 2771 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_STRMV.
Referenced by liftracc_strmv_().
void liftracc_strmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const float * a, const int * lda, float * x, const int * incx)
Definition at line 2808 of file liftracc_autogen.c.
References liftracc_strmv().
void liftracc_strsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const float alpha, const float * a, const int lda, float * b, const int ldb)
Definition at line 6704 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_STRSM.
Referenced by liftracc_strsm_().
void liftracc_strsm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * m, const int * n, const float * alpha, const float * a, const int * lda, float * b, const int * ldb)
Definition at line 6741 of file liftracc_autogen.c.
References liftracc_strsm().
void liftracc_strsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const float * a, const int lda, float * x, const int incx)
Definition at line 2942 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_STRSV.
Referenced by liftracc_strsv_().
void liftracc_strsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const float * a, const int * lda, float * x, const int * incx)
Definition at line 2979 of file liftracc_autogen.c.
References liftracc_strsv().
void liftracc_xerbla (int p, const char * rout, const char * form, ...)
Definition at line 8129 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_XERBLA.
Referenced by liftracc_xerbla_().
void liftracc_xerbla_ (int * p, const char * rout, const char * form, ...)
Definition at line 8174 of file liftracc_autogen.c.
References liftracc_xerbla().
void liftracc_zaxpy (const int n, const void * alpha, const void * x, const int incx, void * y, const int incy)
Definition at line 1802 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZAXPY.
Referenced by liftracc_zaxpy_().
void liftracc_zaxpy_ (const int * n, const void * alpha, const void * x, const int * incx, void * y, const int * incy)
Definition at line 1839 of file liftracc_autogen.c.
References liftracc_zaxpy().
void liftracc_zcopy (const int n, const void * x, const int incx, void * y, const int incy)
Definition at line 1745 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZCOPY.
Referenced by liftracc_zcopy_().
void liftracc_zcopy_ (const int * n, const void * x, const int * incx, void * y, const int * incy)
Definition at line 1782 of file liftracc_autogen.c.
References liftracc_zcopy().
void liftracc_zdotc_sub (const int n, const void * x, const int incx, const void * y, const int incy, void * dotc)
Definition at line 434 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZDOTC_SUB.
Referenced by liftracc_zdotc_sub_().
void liftracc_zdotc_sub_ (const int * n, const void * x, const int * incx, const void * y, const int * incy, void * dotc)
Definition at line 471 of file liftracc_autogen.c.
References liftracc_zdotc_sub().
void liftracc_zdotu_sub (const int n, const void * x, const int incx, const void * y, const int incy, void * dotu)
Definition at line 377 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZDOTU_SUB.
Referenced by liftracc_zdotu_sub_().
void liftracc_zdotu_sub_ (const int * n, const void * x, const int * incx, const void * y, const int * incy, void * dotu)
Definition at line 414 of file liftracc_autogen.c.
References liftracc_zdotu_sub().
void liftracc_zdscal (const int n, const double alpha, void * x, const int incx)
Definition at line 2600 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZDSCAL.
Referenced by liftracc_zdscal_().
void liftracc_zdscal_ (const int * n, const double * alpha, void * x, const int * incx)
Definition at line 2637 of file liftracc_autogen.c.
References liftracc_zdscal().
void liftracc_zgbmv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const int kl, const int ku, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 4082 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZGBMV.
Referenced by liftracc_zgbmv_().
void liftracc_zgbmv_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const int * m, const int * n, const int * kl, const int * ku, const void * alpha, const void * a, const int * lda, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 4119 of file liftracc_autogen.c.
References liftracc_zgbmv().
void liftracc_zgemm (const liftracc_order_t order, const liftracc_transpose_t transa, const liftracc_transpose_t transb, const int m, const int n, const int k, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
Definition at line 7445 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZGEMM.
Referenced by liftracc_zgemm_().
void liftracc_zgemm_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const liftracc_transpose_t * transb, const int * m, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const void * beta, void * c, const int * ldc)
Definition at line 7482 of file liftracc_autogen.c.
References liftracc_zgemm().
void liftracc_zgemv (const liftracc_order_t order, const liftracc_transpose_t transa, const int m, const int n, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 4025 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZGEMV.
Referenced by liftracc_zgemv_().
void liftracc_zgemv_ (const liftracc_order_t * order, const liftracc_transpose_t * transa, const int * m, const int * n, const void * alpha, const void * a, const int * lda, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 4062 of file liftracc_autogen.c.
References liftracc_zgemv().
void liftracc_zgerc (const liftracc_order_t order, const int m, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * a, const int lda)
Definition at line 6134 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZGERC.
Referenced by liftracc_zgerc_().
void liftracc_zgerc_ (const liftracc_order_t * order, const int * m, const int * n, const void * alpha, const void * x, const int * incx, const void * y, const int * incy, void * a, const int * lda)
Definition at line 6171 of file liftracc_autogen.c.
References liftracc_zgerc().
void liftracc_zgeru (const liftracc_order_t order, const int m, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * a, const int lda)
Definition at line 6077 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZGERU.
Referenced by liftracc_zgeru_().
void liftracc_zgeru_ (const liftracc_order_t * order, const int * m, const int * n, const void * alpha, const void * x, const int * incx, const void * y, const int * incy, void * a, const int * lda)
Definition at line 6114 of file liftracc_autogen.c.
References liftracc_zgeru().
void liftracc_zhbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const int k, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 5963 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZHBMV.
Referenced by liftracc_zhbmv_().
void liftracc_zhbmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 6000 of file liftracc_autogen.c.
References liftracc_zhbmv().
void liftracc_zhemm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
Definition at line 7958 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZHEMM.
Referenced by liftracc_zhemm_().
void liftracc_zhemm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const int * m, const int * n, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const void * beta, void * c, const int * ldc)
Definition at line 7995 of file liftracc_autogen.c.
References liftracc_zhemm().
void liftracc_zhemv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * a, const int lda, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 5906 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZHEMV.
Referenced by liftracc_zhemv_().
void liftracc_zhemv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const void * alpha, const void * a, const int * lda, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 5943 of file liftracc_autogen.c.
References liftracc_zhemv().
void liftracc_zher (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const void * x, const int incx, void * a, const int lda)
Definition at line 6191 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZHER.
Referenced by liftracc_zher_().
void liftracc_zher2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * a, const int lda)
Definition at line 6305 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZHER2.
Referenced by liftracc_zher2_().
void liftracc_zher2_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const void * alpha, const void * x, const int * incx, const void * y, const int * incy, void * a, const int * lda)
Definition at line 6342 of file liftracc_autogen.c.
References liftracc_zher2().
void liftracc_zher2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const double beta, void * c, const int ldc)
Definition at line 8072 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZHER2K.
Referenced by liftracc_zher2k_().
void liftracc_zher2k_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const double * beta, void * c, const int * ldc)
Definition at line 8109 of file liftracc_autogen.c.
References liftracc_zher2k().
void liftracc_zher_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const double * alpha, const void * x, const int * incx, void * a, const int * lda)
Definition at line 6228 of file liftracc_autogen.c.
References liftracc_zher().
void liftracc_zherk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const double alpha, const void * a, const int lda, const double beta, void * c, const int ldc)
Definition at line 8015 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZHERK.
Referenced by liftracc_zherk_().
void liftracc_zherk_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const double * alpha, const void * a, const int * lda, const double * beta, void * c, const int * ldc)
Definition at line 8052 of file liftracc_autogen.c.
References liftracc_zherk().
void liftracc_zhpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * ap, const void * x, const int incx, const void * beta, void * y, const int incy)
Definition at line 6020 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZHPMV.
Referenced by liftracc_zhpmv_().
void liftracc_zhpmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const void * alpha, const void * ap, const void * x, const int * incx, const void * beta, void * y, const int * incy)
Definition at line 6057 of file liftracc_autogen.c.
References liftracc_zhpmv().
void liftracc_zhpr (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const double alpha, const void * x, const int incx, void * a)
Definition at line 6248 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZHPR.
Referenced by liftracc_zhpr_().
void liftracc_zhpr2 (const liftracc_order_t order, const liftracc_uplo_t uplo, const int n, const void * alpha, const void * x, const int incx, const void * y, const int incy, void * ap)
Definition at line 6362 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZHPR2.
Referenced by liftracc_zhpr2_().
void liftracc_zhpr2_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const void * alpha, const void * x, const int * incx, const void * y, const int * incy, void * ap)
Definition at line 6399 of file liftracc_autogen.c.
References liftracc_zhpr2().
void liftracc_zhpr_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const int * n, const double * alpha, const void * x, const int * incx, void * a)
Definition at line 6285 of file liftracc_autogen.c.
References liftracc_zhpr().
void liftracc_zscal (const int n, const void * alpha, void * x, const int incx)
Definition at line 2486 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZSCAL.
Referenced by liftracc_zscal_().
void liftracc_zscal_ (const int * n, const void * alpha, void * x, const int * incx)
Definition at line 2523 of file liftracc_autogen.c.
References liftracc_zscal().
void liftracc_zswap (const int n, void * x, const int incx, void * y, const int incy)
Definition at line 1688 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZSWAP.
Referenced by liftracc_zswap_().
void liftracc_zswap_ (const int * n, void * x, const int * incx, void * y, const int * incy)
Definition at line 1725 of file liftracc_autogen.c.
References liftracc_zswap().
void liftracc_zsymm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const int m, const int n, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
Definition at line 7502 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZSYMM.
Referenced by liftracc_zsymm_().
void liftracc_zsymm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const int * m, const int * n, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const void * beta, void * c, const int * ldc)
Definition at line 7539 of file liftracc_autogen.c.
References liftracc_zsymm().
void liftracc_zsyr2k (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void * alpha, const void * a, const int lda, const void * b, const int ldb, const void * beta, void * c, const int ldc)
Definition at line 7616 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZSYR2K.
Referenced by liftracc_zsyr2k_().
void liftracc_zsyr2k_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * b, const int * ldb, const void * beta, void * c, const int * ldc)
Definition at line 7653 of file liftracc_autogen.c.
References liftracc_zsyr2k().
void liftracc_zsyrk (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t trans, const int n, const int k, const void * alpha, const void * a, const int lda, const void * beta, void * c, const int ldc)
Definition at line 7559 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZSYRK.
Referenced by liftracc_zsyrk_().
void liftracc_zsyrk_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * trans, const int * n, const int * k, const void * alpha, const void * a, const int * lda, const void * beta, void * c, const int * ldc)
Definition at line 7596 of file liftracc_autogen.c.
References liftracc_zsyrk().
void liftracc_ztbmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void * a, const int lda, void * x, const int incx)
Definition at line 4196 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZTBMV.
Referenced by liftracc_ztbmv_().
void liftracc_ztbmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const int * k, const void * a, const int * lda, void * x, const int * incx)
Definition at line 4233 of file liftracc_autogen.c.
References liftracc_ztbmv().
void liftracc_ztbsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const int k, const void * a, const int lda, void * x, const int incx)
Definition at line 4367 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZTBSV.
Referenced by liftracc_ztbsv_().
void liftracc_ztbsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const int * k, const void * a, const int * lda, void * x, const int * incx)
Definition at line 4404 of file liftracc_autogen.c.
References liftracc_ztbsv().
void liftracc_ztpmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * ap, void * x, const int incx)
Definition at line 4253 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZTPMV.
Referenced by liftracc_ztpmv_().
void liftracc_ztpmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const void * ap, void * x, const int * incx)
Definition at line 4290 of file liftracc_autogen.c.
References liftracc_ztpmv().
void liftracc_ztpsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * ap, void * x, const int incx)
Definition at line 4424 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZTPSV.
Referenced by liftracc_ztpsv_().
void liftracc_ztpsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const void * ap, void * x, const int * incx)
Definition at line 4461 of file liftracc_autogen.c.
References liftracc_ztpsv().
void liftracc_ztrmm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void * alpha, const void * a, const int lda, void * b, const int ldb)
Definition at line 7673 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZTRMM.
Referenced by liftracc_ztrmm_().
void liftracc_ztrmm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * m, const int * n, const void * alpha, const void * a, const int * lda, void * b, const int * ldb)
Definition at line 7710 of file liftracc_autogen.c.
References liftracc_ztrmm().
void liftracc_ztrmv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * a, const int lda, void * x, const int incx)
Definition at line 4139 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZTRMV.
Referenced by liftracc_ztrmv_().
void liftracc_ztrmv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const void * a, const int * lda, void * x, const int * incx)
Definition at line 4176 of file liftracc_autogen.c.
References liftracc_ztrmv().
void liftracc_ztrsm (const liftracc_order_t order, const liftracc_side_t side, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int m, const int n, const void * alpha, const void * a, const int lda, void * b, const int ldb)
Definition at line 7730 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZTRSM.
Referenced by liftracc_ztrsm_().
void liftracc_ztrsm_ (const liftracc_order_t * order, const liftracc_side_t * side, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * m, const int * n, const void * alpha, const void * a, const int * lda, void * b, const int * ldb)
Definition at line 7767 of file liftracc_autogen.c.
References liftracc_ztrsm().
void liftracc_ztrsv (const liftracc_order_t order, const liftracc_uplo_t uplo, const liftracc_transpose_t transa, const liftracc_diag_t diag, const int n, const void * a, const int lda, void * x, const int incx)
Definition at line 4310 of file liftracc_autogen.c.
References ERROR, liftracc_selector_problem_info_t::info1, liftracc_selector_select(), and SELECT_ZTRSV.
Referenced by liftracc_ztrsv_().
void liftracc_ztrsv_ (const liftracc_order_t * order, const liftracc_uplo_t * uplo, const liftracc_transpose_t * transa, const liftracc_diag_t * diag, const int * n, const void * a, const int * lda, void * x, const int * incx)
Definition at line 4347 of file liftracc_autogen.c.
References liftracc_ztrsv().
Variable Documentation
liftracc_selector_problem_info_t pinfo = { }
Definition at line 27 of file liftracc_autogen.c.