libliftracc: src/liftracc_selector.h File Reference
src/liftracc_selector.h File Reference
Header file of the selector module.
#include "cycle.h"
Data Structures
struct liftracc_selector_problem_info_t
Defines
#define ARRAY_SIZE 15
Typedefs
typedef unsigned char decision_data_t
Enumerations
enum liftracc_selector_error_t {
NO_ERROR, NO_LIBS_FOUND_ERROR, LIBS_OPEN_ERROR, LIBS_CLOSE_ERROR,
FUNCTION_NOT_FOUND_ERROR, FILE_NOT_FOUND_ERROR, DATA_READ_ERROR, DATA_WRITE_ERROR
}
enum liftracc_selector_funcid_t {
SELECT_SDSDOT, SELECT_DSDOT, SELECT_SDOT, SELECT_DDOT,
SELECT_CDOTU_SUB, SELECT_CDOTC_SUB, SELECT_ZDOTU_SUB, SELECT_ZDOTC_SUB,
SELECT_SNRM2, SELECT_SASUM, SELECT_DNRM2, SELECT_DASUM,
SELECT_SCNRM2, SELECT_SCASUM, SELECT_DZNRM2, SELECT_DZASUM,
SELECT_ISAMAX, SELECT_IDAMAX, SELECT_ICAMAX, SELECT_IZAMAX,
SELECT_SSWAP, SELECT_SCOPY, SELECT_SAXPY, SELECT_DSWAP,
SELECT_DCOPY, SELECT_DAXPY, SELECT_CSWAP, SELECT_CCOPY,
SELECT_CAXPY, SELECT_ZSWAP, SELECT_ZCOPY, SELECT_ZAXPY,
SELECT_SROTG, SELECT_SROTMG, SELECT_SROT, SELECT_SROTM,
SELECT_DROTG, SELECT_DROTMG, SELECT_DROT, SELECT_DROTM,
SELECT_SSCAL, SELECT_DSCAL, SELECT_CSCAL, SELECT_ZSCAL,
SELECT_CSSCAL, SELECT_ZDSCAL, SELECT_SGEMV, SELECT_SGBMV,
SELECT_STRMV, SELECT_STBMV, SELECT_STPMV, SELECT_STRSV,
SELECT_STBSV, SELECT_STPSV, SELECT_DGEMV, SELECT_DGBMV,
SELECT_DTRMV, SELECT_DTBMV, SELECT_DTPMV, SELECT_DTRSV,
SELECT_DTBSV, SELECT_DTPSV, SELECT_CGEMV, SELECT_CGBMV,
SELECT_CTRMV, SELECT_CTBMV, SELECT_CTPMV, SELECT_CTRSV,
SELECT_CTBSV, SELECT_CTPSV, SELECT_ZGEMV, SELECT_ZGBMV,
SELECT_ZTRMV, SELECT_ZTBMV, SELECT_ZTPMV, SELECT_ZTRSV,
SELECT_ZTBSV, SELECT_ZTPSV, SELECT_SSYMV, SELECT_SSBMV,
SELECT_SSPMV, SELECT_SGER, SELECT_SSYR, SELECT_SSPR,
SELECT_SSYR2, SELECT_SSPR2, SELECT_DSYMV, SELECT_DSBMV,
SELECT_DSPMV, SELECT_DGER, SELECT_DSYR, SELECT_DSPR,
SELECT_DSYR2, SELECT_DSPR2, SELECT_CHEMV, SELECT_CHBMV,
SELECT_CHPMV, SELECT_CGERU, SELECT_CGERC, SELECT_CHER,
SELECT_CHPR, SELECT_CHER2, SELECT_CHPR2, SELECT_ZHEMV,
SELECT_ZHBMV, SELECT_ZHPMV, SELECT_ZGERU, SELECT_ZGERC,
SELECT_ZHER, SELECT_ZHPR, SELECT_ZHER2, SELECT_ZHPR2,
SELECT_SGEMM, SELECT_SSYMM, SELECT_SSYRK, SELECT_SSYR2K,
SELECT_STRMM, SELECT_STRSM, SELECT_DGEMM, SELECT_DSYMM,
SELECT_DSYRK, SELECT_DSYR2K, SELECT_DTRMM, SELECT_DTRSM,
SELECT_CGEMM, SELECT_CSYMM, SELECT_CSYRK, SELECT_CSYR2K,
SELECT_CTRMM, SELECT_CTRSM, SELECT_ZGEMM, SELECT_ZSYMM,
SELECT_ZSYRK, SELECT_ZSYR2K, SELECT_ZTRMM, SELECT_ZTRSM,
SELECT_CHEMM, SELECT_CHERK, SELECT_CHER2K, SELECT_ZHEMM,
SELECT_ZHERK, SELECT_ZHER2K, SELECT_XERBLA, CALLTEST_DYNAMIC,
FUNCTION_COUNT
}
Functions
liftracc_selector_error_t liftracc_selector_init ()
Selector component init function. All init stuff is done here. This includes loading the plugins and generating the look up table.
liftracc_selector_error_t liftracc_selector_fini ()
Selector component finalize function. Clean up is done here.
void * liftracc_selector_select (const char *symbol_name)
Select function pointer to use in LUT.
liftracc_selector_error_t liftracc_selector_loadinfo (const char *file_name, decision_data_t array[FUNCTION_COUNT][15])
Load decision info's from file.
Variables
char liftracc_library_path []
const char * liftracc_selector_funcnames []
Detailed Description
Header file of the selector module.
Author:
Manuel Niekamp <niekma@upb.de>
Version:
0.1
Date:
10/2009-03/2010
This file defines the interface to the selector component. The selector is used inside the wrapper library to select the best function out of a function pool. The functions selected match the calling one from the wrapper library.
Definition in file liftracc_selector.h.
Define Documentation
#define ARRAY_SIZE 15
Definition at line 19 of file liftracc_selector.h.
Referenced by liftracc_selector_select().
Typedef Documentation
typedef unsigned char decision_data_t
Definition at line 26 of file liftracc_selector.h.
Enumeration Type Documentation
enum liftracc_selector_error_t
Enumeration of error states. This enum covers all possible error states the selector can get in.
Enumerator:
NO_ERROR
NO_LIBS_FOUND_ERROR
LIBS_OPEN_ERROR
LIBS_CLOSE_ERROR
FUNCTION_NOT_FOUND_ERROR
FILE_NOT_FOUND_ERROR
DATA_READ_ERROR
DATA_WRITE_ERROR
Definition at line 34 of file liftracc_selector.h.
enum liftracc_selector_funcid_t
Enumeration of selector function ids. There is an id to every blas function supported. One of these ids is passed to the selector in order to decide which function should be selected. (candidate for autogen!)
Enumerator:
SELECT_SDSDOT
SELECT_DSDOT
SELECT_SDOT
SELECT_DDOT
SELECT_CDOTU_SUB
SELECT_CDOTC_SUB
SELECT_ZDOTU_SUB
SELECT_ZDOTC_SUB
SELECT_SNRM2
SELECT_SASUM
SELECT_DNRM2
SELECT_DASUM
SELECT_SCNRM2
SELECT_SCASUM
SELECT_DZNRM2
SELECT_DZASUM
SELECT_ISAMAX
SELECT_IDAMAX
SELECT_ICAMAX
SELECT_IZAMAX
SELECT_SSWAP
SELECT_SCOPY
SELECT_SAXPY
SELECT_DSWAP
SELECT_DCOPY
SELECT_DAXPY
SELECT_CSWAP
SELECT_CCOPY
SELECT_CAXPY
SELECT_ZSWAP
SELECT_ZCOPY
SELECT_ZAXPY
SELECT_SROTG
SELECT_SROTMG
SELECT_SROT
SELECT_SROTM
SELECT_DROTG
SELECT_DROTMG
SELECT_DROT
SELECT_DROTM
SELECT_SSCAL
SELECT_DSCAL
SELECT_CSCAL
SELECT_ZSCAL
SELECT_CSSCAL
SELECT_ZDSCAL
SELECT_SGEMV
SELECT_SGBMV
SELECT_STRMV
SELECT_STBMV
SELECT_STPMV
SELECT_STRSV
SELECT_STBSV
SELECT_STPSV
SELECT_DGEMV
SELECT_DGBMV
SELECT_DTRMV
SELECT_DTBMV
SELECT_DTPMV
SELECT_DTRSV
SELECT_DTBSV
SELECT_DTPSV
SELECT_CGEMV
SELECT_CGBMV
SELECT_CTRMV
SELECT_CTBMV
SELECT_CTPMV
SELECT_CTRSV
SELECT_CTBSV
SELECT_CTPSV
SELECT_ZGEMV
SELECT_ZGBMV
SELECT_ZTRMV
SELECT_ZTBMV
SELECT_ZTPMV
SELECT_ZTRSV
SELECT_ZTBSV
SELECT_ZTPSV
SELECT_SSYMV
SELECT_SSBMV
SELECT_SSPMV
SELECT_SGER
SELECT_SSYR
SELECT_SSPR
SELECT_SSYR2
SELECT_SSPR2
SELECT_DSYMV
SELECT_DSBMV
SELECT_DSPMV
SELECT_DGER
SELECT_DSYR
SELECT_DSPR
SELECT_DSYR2
SELECT_DSPR2
SELECT_CHEMV
SELECT_CHBMV
SELECT_CHPMV
SELECT_CGERU
SELECT_CGERC
SELECT_CHER
SELECT_CHPR
SELECT_CHER2
SELECT_CHPR2
SELECT_ZHEMV
SELECT_ZHBMV
SELECT_ZHPMV
SELECT_ZGERU
SELECT_ZGERC
SELECT_ZHER
SELECT_ZHPR
SELECT_ZHER2
SELECT_ZHPR2
SELECT_SGEMM
SELECT_SSYMM
SELECT_SSYRK
SELECT_SSYR2K
SELECT_STRMM
SELECT_STRSM
SELECT_DGEMM
SELECT_DSYMM
SELECT_DSYRK
SELECT_DSYR2K
SELECT_DTRMM
SELECT_DTRSM
SELECT_CGEMM
SELECT_CSYMM
SELECT_CSYRK
SELECT_CSYR2K
SELECT_CTRMM
SELECT_CTRSM
SELECT_ZGEMM
SELECT_ZSYMM
SELECT_ZSYRK
SELECT_ZSYR2K
SELECT_ZTRMM
SELECT_ZTRSM
SELECT_CHEMM
SELECT_CHERK
SELECT_CHER2K
SELECT_ZHEMM
SELECT_ZHERK
SELECT_ZHER2K
SELECT_XERBLA
CALLTEST_DYNAMIC
FUNCTION_COUNT
Definition at line 52 of file liftracc_selector.h.
Function Documentation
liftracc_selector_error_t liftracc_selector_fini ()
Selector component finalize function. Clean up is done here.
Returns:
Error state or NO_ERROR
Definition at line 136 of file liftracc_selector.c.
References ERROR, error, found_libs, library_handles, liftracc_plugin_handles, and prio_list.
Referenced by __attribute__().
liftracc_selector_error_t liftracc_selector_init ()
Selector component init function. All init stuff is done here. This includes loading the plugins and generating the look up table.
Returns:
Error state or NO_ERROR
Definition at line 77 of file liftracc_selector.c.
References plugin_info_t::desc, error, ERROR, found_libs, handle, library_handles, library_path, liftracc_decision_table, liftracc_found_libs, liftracc_fptr_lut, liftracc_plugin_handles, liftracc_selector_funcnames, liftracc_selector_init(), liftracc_selector_load_plugins(), MSG, plugin_info_t::name, NO_ERROR, plugin_info_t::prio, prio_list, and plugin_info_t::uuid.
Referenced by __attribute__(), liftracc_selector_init(), and liftracc_selector_load_plugins().
liftracc_selector_error_t liftracc_selector_loadinfo (const char * file_name, decision_data_t array[FUNCTION_COUNT][15])
Load decision info's from file.
This method loads the array containing infos used by the selector to decide with function is the fastest an should therefor be used as entry in the function pointer LUT.
Parameters:
file_name Name of file to load data from
array Pointer to array to store data into
Returns:
liftracc selector error code
void* liftracc_selector_select (const char * symbol_name)
Select function pointer to use in LUT.
This function selects a function pointer. It is one of the function pointers available in one of the sublibraries. The selection is based on a per library priority.
Parameters:
symbol_name Symbol name of function that should be selected.
Returns:
The selected function pointer
Definition at line 111 of file liftracc_selector_old.c.
References error, found_libs, library_handles, and prio_list.
Variable Documentation
char liftracc_library_path[]
Path to lib liftracc.
Definition at line 38 of file liftracc_selector.c.
Referenced by liftracc_selector_load_plugins().
const char* liftracc_selector_funcnames[]
Definition at line 2 of file liftracc_selector_autogen.c.
Referenced by liftracc_selector_init(), and liftracc_selector_load_plugins().